### ISSUE TITLE
Error with the "withFilename" method

### ISSUE THREAD

**Issue by beeInteractive** [plank/laravel-mediable#1]
Hi!

When I want to upload and change the file name with the "withFilename()" method, it throws me this error: 

Call to undefined method Plank\Mediable\MediaUploader::withFilename()

Did I miss something? Some "use" or something else?

**Comment by frasmage** [comment]
Hi @beeInteractive ,

The example in the documentation displayed the wrong method name. The method is actually called `setFilename()`. I have updated the documentation accordingly.

Thanks for pointing that out!
