### ISSUE TITLE
Testing with Faker->imageURL() fails 

### ISSUE THREAD

**Issue by PayteR** [plank/laravel-mediable#101]
Hi, i'm trying to write unit test for storing/retrieve/delete images from media with faker. My code is 

```
$image = $this->faker->imageUrl();
$media = \MediaUploader::fromSource($image)->upload();
```
and it will result fails with

```
Illuminate\Database\QueryException : SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: media.size (SQL: insert into "media" ("size", "mime_type", "extension", "aggregate_type", "disk", "directory", "filename", "updated_at", "created_at") values (, image/jpeg, jpeg, image, uploads, , -94283, 2018-03-25 13:59:00, 2018-03-25 13:59:00))
```
url for image looks like this
```
https://lorempixel.com/640/480/?64031
```
images are stored like this
![2018-03-25_1356](https://user-images.githubusercontent.com/1248565/37874768-8773ac22-3035-11e8-945d-f4fd18871b30.png)

It could be due lacking of image name? Maybe there could be some default file name for files that have no extension and this extension will be created from mime type? Btw, great library.

**Comment by PayteR** [comment]
I found another issue, when i want to download any image with `?get=params` for example `http://www.personal.psu.edu/oeo5025/jpg.jpg?sdfsd` then this error occurs  

`ErrorException : file_put_contents(/vagrant/public/uploads/test/jpg.jpg?sdfsd): failed to open stream: Protocol error`

**Comment by frasmage** [comment]
Hi @PayteR,

Thanks for pointing this out,  I hadn't encountered this before. The lack of proper filename/extension on that faker url might be the issue. Does specifying the destination filename help?

The extension including the query string params is definitely a bug, you can open a PR with your proposed fix. 

I'm occupied with Easter events this weekend, but will try to take another look at this sometime this week.

**Comment by PayteR** [comment]
Hi @frasmage, thx for response, no setting filename didn't help. There needs to be set some default name and size somehow somewhere.

For second issue i already made proposal https://github.com/PayteR/laravel-mediable/commit/b9f19c4e4f945e704d3f80c53695d945d6142654

Take your time, for my needs i already made fixes :)

**Comment by PayteR** [comment]
I come across this another issue, and when i fixed it with default file size set to 0, this issue will not occurs anymore

https://github.com/plank/laravel-mediable/compare/master...PayteR:patch-6

**Comment by leouze** [comment]
+1 
I need  this as well on my project please.

**Comment by PayteR** [comment]
@frasmage i don't use this package anymore, sorry
