### ISSUE TITLE
Changing visibility of MediaUploader attributes and methods

### ISSUE THREAD

**Issue by JulesPrimo** [plank/laravel-mediable#104]
Hello,

I have to encrypt some files before upload and it would be nice if the MediaUploader could handle it.
Sadly, everything is declared private so there's no way to use the attributes or existing methods in a child class.

Is changing the visibility of attributes/methods from private to protected is conceivable ?

**Comment by frasmage** [comment]
Hi @JulesPrimo,

No, that will not be changed in the core library. Private methods or attributes marked as such intentionally as they are part of the private internal API of the package. If they were changed to public/protected any adjustment or optimization of their use would constitute a breaking change, as developers could be hooking into their existing functionality.

You are welcome to fork the package and make the changes you need for the purposes of your own project, though I will not accept a PR back into the main codebase for this kind of change.

That said, there is an open feature request to build a `beforeSave()` callback into the MediaUploader which might suit your purposes? You are welcome to help with that as well.

**Comment by JulesPrimo** [comment]
Okay, thanks for the quick answer, I got your point.

I'll be glad to help with #98, I'll see that tomorrow.
