### ISSUE TITLE
Integrate 3rd party cloud service

### ISSUE THREAD

**Issue by jayeshanandani** [plank/laravel-mediable#106]
Hi,

Thanks for such an awesome plugin! It is indeed a great one!

We are using https://cloudinary.com/ to store our image and referencing same in the database.

This plugin has many useful things so I was hoping to replace the one we have with this to use great functions that this plugin supports.

However was not able to find any documentation on how can we integrate or keep links rather than the path from 3rd party cloud-like above?

I saw that we have s3 adapters but I will like to know if we can extend some classes and make our own or how can we go about doing same?

**Comment by JulesPrimo** [comment]
It uses the laravel file library and laravel uses Flysystem in the back, you just have to make an adapter for it.

https://flysystem.thephpleague.com/

**Comment by frasmage** [comment]
Hi @jayeshanandani,

I'm glad you enjoy the package! 

As @JulesPrimo said, you can either write your own flysystem adapter for cloudinary or find an existing one and register your disk to use that adapter in laravel's `config/filesystem.php`. As far as this package is concerned, it just needs to know how to create URLs for files on this host. You can create a UrlGenerator subclass and register it in `config/mediable.php`

I hope this helps.
