### ISSUE TITLE
Authorization & Gate

### ISSUE THREAD

**Issue by Arcesilas** [plank/laravel-mediable#107]
Hi,

I'm about using this package which seems really awesome.

I would like to store files which would not be public, but reserved for certain members (members may decide who can see their pictures/files).

What is the best way to implement this?

For now, I'm considering doing this:
- write a controller for the files with restricted access
- write a middleware to check the abilities of the user for the requested file
- extend the `Media` class with a public `getMimeType()` method (to send the file to the browser)
- write a `UrlGenerator` to handle the custom url to the controller
- configure the `UrlGeneratorFactory` to inform it to use the new `UrlGenerator` for this disk

If I'm on the right track, I think it would be worth adding such a feature in a future release... :innocent:

**Comment by Arcesilas** [comment]
Thanks for your answer!

I did not mention the User-Media relation, since it's handled by the permission package I use ([Bouncer](https://github.com/JosephSilber/bouncer)).

What I had in mind was not that the package should handle this whole process, but at least the media-side of the authorization. For instance, a media could be `restricted` instead of just `public` or `private` (actually, it should be `private` -- for the filesystem-- and `restricted`). When getting the url of the media, the URL to the controller would be returned.
The package could provide a controller (which would be "publishable" via artisan command `vendor:publish`) which would simply check at the gate if the user can access the file, with something like that:

`if (Gate::allows('display-media', $media))`

If you consider it's not worth adding, maybe simply add a method to send a Response with the file (which would set the appropriate headers: mime type, file size, etc and then send the file content to the browser).

What do you think?

**Comment by frasmage** [comment]
public/private has to do with the filesystem permissions. It's a feature of flysystem, not something I can change.

That said, a `$media->toResponse()` or `$media->toDownloadResponse()` could be a useful feature, since that is pretty agnostic to the controller logic but neatly encapsulates some common functionality. I'll add that to the todo list for the next version.
