### ISSUE TITLE
Non static call to $media = MediaUploader::fromSource()

### ISSUE THREAD

**Issue by M-Abdullahi** [plank/laravel-mediable#108]
Hi. Thank you for creating this package.
I installed it yesterday and when i try to upload a file using 

$media = MediaUploader::fromSource($request->file('thumbnail'))->upload();

i get a non static call exception thrown. After hours of searching, I decided to inject it to my controller
 and it worked. 
public function store(StoreArticleRequest $request, MediaUploader $mediaUploader) {

 $media = $mediaUploader->fromSource($request->file('image'))->upload();
// foo
}

Kindly take a look at it and maybe correct me if it did it wrong

**Comment by frasmage** [comment]
Hi @M-Abdullahi,

did you properly register the MediableServiceProvider and MediaUploaderFacade in Laravel's configs?

Also, if you `use Plank/Mediable/MediaUploader;` in a file, then you won't be able to use the `MediaUploader` as a facade with the same name. If you have a need for both, consider aliasing one of them with your `use` statement or changing the facade name in your aliases config.

That said, there nothing wrong with using dependency injection in lieu of the facade.

**Comment by larshaw** [comment]
I'm running into the same  issue as @M-Abdullahi...I'm trying to use the MediaUploader facade in my model. I'm running laravel 5.6.25 so my assumption is that package auto-discovery would take care of adding MediableServiceProvider and MediaUploaderFacade.  Here's my model....

<?php
namespace App\Models\Events;

use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;

class Event extends Model 
{
    use Mediable;
    ......
    ......
   public function updateAttributes(array $request)
    {
        if (isset($request['event_cover_image'])) {          
          
       $coverImage =  MediaUploader::fromSource($request['event_cover_image'])
                                  ->toDirectory('event-cover-images')
                                  ->onDuplicateReplace()                                  
                                  ->upload();
        }

     }
}

I even tried to manually add the provider and alias to my config.app...mind you all of this is a little smoke and mirrors for but I'm running out of guesses. Great package by the way...really looking forward to working with it.

**Comment by frasmage** [comment]
Hi @larshaw,

See my comment above. If you use the MediaUploader fully qualified namespace in a file it will supercede the facade. So either alias your `use` statement or rename the facade in your configs.
