### ISSUE TITLE
Is it possible to encrypt files easily before attaching them to models?

### ISSUE THREAD

**Issue by shabaz-ejaz** [plank/laravel-mediable#109]
I was wondering if it is easy to encrypt and decrypt files with this library using Laravel's encryption mechanisms?

So something like this?

`attachMedia(Crypt::encrypt(file_get_contents($file)), 'thumbnail')`

and then the same for decrypting the contents of the file.

Is this possible and if so, what ramifications are there?

**Comment by frasmage** [comment]
I imagine this would be possible, though you might need to do a little bit of extra work. 

You could encrypt the file before upload, but then the uploader probably won't recognize the mime type. If the filename/extension doesn't change, you could encrypt the file after it is saved and the media record is created. Then, whenever you read the file's contents, you would need to run it through `Crypt::decrypt()` before using it.

This seems like a great feature to add first class support for in an upcoming version. PRs welcome!

**Comment by shabaz-ejaz** [comment]
Thanks for the feedback.

I think encrypting the file after it is saved / uploaded sort of defeats the purpose of encrypting the file as a whole. I guess the the goal is to prevent any normal (non-encrypted) files from residing on the server. 

Unless I've misunderstood you, I'm not sure what use cases we might have for encrypting the files once they've been uploaded. Or do you mean store the files as normal, then encrypt them and overwrite those same files?

**Comment by shabaz-ejaz** [comment]
Thanks. I'll have a go at implementing this first. If it goes well I'll look to maybe submit a PR. Do you require unit tests?

**Comment by frasmage** [comment]
Great, let me know how it goes. Yes, unit tests are required. As this would be adding a new feature, adding a brief explanation of how to use it to the documentation pages would also be greatly appreciated.

**Comment by JulesPrimo** [comment]
That's exactly why I've done #105, here's how I use it : 

```
                $this->mediaUploader
                        ->fromSource($file)
                        ->setAllowedAggregateTypes([
                            Media::TYPE_IMAGE,
                            Media::TYPE_SPREADSHEET,
                            Media::TYPE_DOCUMENT,
                            Media::TYPE_PDF
                        ])
                        ->verifyFile();

                    $encrypted = Crypto::encrypt(
                        new HiddenString(
                            $file->openFile()->fread($file->getSize())
                        ),
                        $user->getEncryptionKey()
                    );

                    $media = $this->mediaUploader->fromString($encrypted)
                        ->useFilename(
                            uniqid() . '.' . $file->getClientOriginalExtension()
                        )
                        ->toDisk('encrypted')
                        ->toDirectory('attachment/' . $email->id)
                        ->beforeSave(function ($model) use ($file) {
                            $model->setAttribute(
                                'mime_type',
                                $file->getMimeType()
                            );
                        })
                        ->upload();
```

**Comment by JulesPrimo** [comment]
You can run VerifyFile on the original file to be sure everything's good then chance the source with the encrypted version.
