### ISSUE TITLE
Can't tag numerical strings

### ISSUE THREAD

**Issue by josiahmann** [plank/laravel-mediable#110]
Hey guys, 

Love the package, but I'm having trouble when trying to tag my media with the year. 

Whether I save it as a string or an integer, I get the same error.

The following code
`$investor->attachMedia($media, "2018");`

produces the following result

`Undefined offset: {{number}}`

Is there a workaround for this?

**Comment by frasmage** [comment]
Hi @josiahmann,

That appears to be a bug. I will try to push a fix for that when I get a chance tomorrow.

Thank you for pointing this out!

**Comment by frasmage** [comment]
Hi @josiahmann,
 
This should now be fixed in 2.7.1

**Comment by josiahmann** [comment]
Awesome @frasmage, I might have to migrate over from laravel-medialibrary now 🥇
