### ISSUE TITLE
list all medias

### ISSUE THREAD

**Issue by JDias** [plank/laravel-mediable#111]
Hi,
im really starting with php/laravel.
could someone give me a light on this?
is possible to do something like $medias = $Media::all() to retrieve erverything? does it make sense?
in the bellow code it doesnt recognize
Class 'App\Http\Controllers\Media' not found
or
Call to undefined method Plank\Mediable\Mediable::inOrUnderDirectory()

thanks in advance,

```
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Plank\Mediable\Mediable;

class MediasController extends Controller
{
  use Mediable;
    public function index(){
      $medias = Media::inOrUnderDirectory('uploads', '/');
      dd($medias);
    }
}
```

**Comment by JDias** [comment]
sorry for that. working like a charm now! :)

**Comment by riseoflex88** [comment]
@JDias can you let us know what the fix was?
