### ISSUE TITLE
Syncing

### ISSUE THREAD

**Issue by JDias** [plank/laravel-mediable#112]
hi,
i noticed 3 commands for artisan: syncing, import and prune.

can i fire any of this 3 from php?

(im tring to get it up with laravel file manager, that has events hooks, so if someone have some recipe allready, im open to suggestions)

**Comment by frasmage** [comment]
Hi @JDias,

If you are trying to populate your database with all existing files on a disk, the media:import command is what you should use. Yes you can call directly from the command line.

```
php artisan media:import {disk : the name of the filesystem disk.}
        {--d|directory= : import files in or below a given directory.}
        {--non-recursive : only import files in the specified directory.}
        {--f|force : re-process existing media.}
```

**Comment by frasmage** [comment]
sorry, I didn't catch that. Yes, laravel supports calling commands directly from php with `Artisan::call('command-name');`

This package was in fact written as the backend to a custom file manager, but released as a stand alone component.

**Comment by JDias** [comment]
Very thanks! :)
