### ISSUE TITLE
Bug on_duplicate_increment 

### ISSUE THREAD

**Issue by AlbertMulaki** [plank/laravel-mediable#113]
Lets say we have two files stored in the database, like this `avatar.jpg` and `avatar-2.jpg`, and i want to upload a file with name `avatar.jpg` in the same form twice, i get the error that it should be unique, I'll update for more details, how can i help to solve this problem?

**Comment by frasmage** [comment]
Hi @AlbertMulaki,

can you provide me with the exact exception (class/message) that you are receiving and the code showing how you are using `MediaUploader`? If you are getting `Plank\Mediable\Exceptions\MediaUpload\FileExistsException`, then you probably didn't apply your onDuplicate behaviour correctly as that is a different mode.

**Comment by AlbertMulaki** [comment]
Hello, thanks for the response.
The version i am using is `"plank/laravel-mediable": "^2.6"`

The error message that i get is this:

> SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'public-images/children/oldImg/LowRes-1-1-png' for key 'media_disk_directory_filename_extension_unique' (SQL: insert into `media` (`size`, `mime_type`, `extension`, `aggregate_type`, `disk`, `directory`, `filename`, `CreatedBy`, `Modifiedby`, `updated_at`, `created_at`) values (1408, image/png, png, image, public, images/children/oldImg/LowRes, 1-1, 1, 1, 2018-06-14 13:32:50, 2018-06-14 13:32:50))

The mediable.php configuration is like this:
`'on_duplicate' => Plank\Mediable\MediaUploader::ON_DUPLICATE_INCREMENT,`

I upload six files with the name 1.jpg, and they get incremented, and remove one file(manually) from storage, 
If i try to upload the same name again 1.jpg then i got the error, like above.

Maybe it doesnt make sense at all, but i am using it on the production server, and sometime users, get that same error too, without me deleting them or anything, But the only way i generated the same error was by doing like i described you.

The code i use is this:

>   $media = MediaUploader::fromSource($servicePhotoData['file'])->toDestination('public','images/children/oldImg/LowRes')->upload();

Let me know if you doubt it is my fault, or does it have to do something with the package.

Thanks in advance.

**Comment by frasmage** [comment]
Ok, I see the issue. If you manually remove a file from the filesystem, it is still in your database. So when the increment behaviour looks for an available file name it sees the deleted one as being available. However, since you didn't clear out your database when you deleted the original, the new one conflicts.

You should make sure to keep your db and disk in sync. Instead of manually deleting the file from disk, use the `$media->delete()` method, which will properly clean up that file in both the filesystem and database. If you must manually delete a file, be sure to delete the related row in the db.

**Comment by AlbertMulaki** [comment]
Alright, thank you very much, it makes sense the way that you explained it, however does the on duplicate increment behaviour, apply on the import commands ?!

**Comment by frasmage** [comment]
No it does not, media:import takes files that already exist on disk and makes a record for them in the database. Since the file is already in position, there is no need to modify it's filename to not conflict with other files.

**Comment by AlbertMulaki** [comment]
Alright thanks, sorry for being so noob and asking silly questions, I think you can close the issue, thank you very much for your explanation. Very kind from you.

**Comment by frasmage** [comment]
My pleasure.
