### ISSUE TITLE
Any function for detaching media matches all of specified tags?

### ISSUE THREAD

**Issue by nnasirzada** [plank/laravel-mediable#117]
Hi @frasmage ,
I read the docs and found the function `$post->detachMediaTags(['feature', 'thumbnail']);` which removes all media assigned to one or more tags, but I couldn't find a shortcut to remove all media assigned to all of specified tags. 

I can remove media from multiple tags by doing so: 
```
$post->getMediaMatchAll(['featured', 'thumbnail']);
foreach($post->media as $media) {
    $post->detachMedia($media, ['featured', 'thumbnail']); //remove media from multiple tags
}
```
Although this method works as desired it requires to load all media first then loop through them and detach one-by-one. I'm looking for something like 
`$post->detachMediaMatchAll(['featured', 'thumbnail']);`  
similar to 
`$post->loadMediaMatchAll(['featured', 'thumbnail']); // attached to both tags` 
or 
`$post->getMediaMatchAll(['header', 'footer']); //alias`

Is there any way to achieve the same goal without loading all media? Are you planning on adding detachMediaMatchAll function? 

Thanks

**Comment by frasmage** [comment]
Hi @nnasirzada,

I'm scratching my head as to why that doesn't exist. Must bee something that got overlooked.

Your proposed solution is not ideal, as you noted, since it is N+1 queries. The preferred solution should be run in one or two queries. I remember some of the match-all queries were tricky, but there are some examples there already.

If you can come up with a solution to make this work, please open a pull request, as contributions are always welcome. Otherwise, I will take a stab at this the next time I have some time to devote to this project.

**Comment by nnasirzada** [comment]
I wish I had spare time to devote to this project. If I wasn't busy with my projects, I would take the lead and work on optimal solution. Can we use current N+1 solution temporarily until someone comes up with an ideal solution? If you are positive, I will open a pull request.

**Comment by frasmage** [comment]
@nnasirzada, understandable!

I would prefer not make something suboptimal part of the main package, but you are more than welcome to make use of it in your own package. 

That said, you might want to adjust your approach to run getMediaMatchAll(), then run a manual delete query from `mediables` where `mediable_id` is IN the list of ids from getMediaMatchAll(), `mediable_type` matches your current class and `tag` is IN the list of tags you want to match. Still not perfect, but much better than N+1.

**Comment by nnasirzada** [comment]
@frasmage, yeah as you said that's better than N+1. 
I just want to make one thing clear. Did you mean `media_id` in your statement?

> where `mediable_id` is IN the list of ids from getMediaMatchAll()?

**Comment by frasmage** [comment]
Yes that's what I meant, sorry.
