### ISSUE TITLE
Using non-integer id's

### ISSUE THREAD

**Issue by liran-co** [plank/laravel-mediable#119]
Is it safe to change the mediable_id column type? I have some models that use non-integer id's and this causes errors when attaching media. Would there be any side effects of changing the mediable_id type to a VARCHAR?

**Comment by frasmage** [comment]
Hi @liran-co,

Absolutely no problem editing the migration files that get generated. The package makes no assumptions on the actual type of the primary key, so INT and VARCHAR work equally well. I have used this package in projects using UUIDs for primary keys before.

Cheers
