### ISSUE TITLE
Question regarding a comparison

### ISSUE THREAD

**Issue by kamov** [plank/laravel-mediable#122]
I was looking for an alternative of https://docs.spatie.be/laravel-medialibrary/v7/introduction which require mysql 5.7+ since use JSON fields..

I would like to know since you know the library, a comparison of your and this one.

Seem offer almost the same features.

Thanks

**Comment by frasmage** [comment]
Hi @kamov,

When this package was originally published, I wrote a [blog post](https://www.plankdesign.com/en/journal/introducing-laravel-mediable) comparing the features of these two libraries and to explain why I created a new package in the first place (comparison table at the bottom of the article). Hopefully this helps. If you have any specific questions, let me know.


PS: sorry for the slow responses, I have been away for the last week.

**Comment by kamov** [comment]
Thank You! I will definitely use your.
