### ISSUE TITLE
Trait collision when using with Lazychaser Nestedset

### ISSUE THREAD

**Issue by rzksbr** [plank/laravel-mediable#130]
I am using Lazychaser Nestedset for Categories and it throws following error when using it together

> Trait method newCollection has not been applied, because there are collisions with other trait methods on App\Model\Category.

Is there any way to avoid the trait collision?

**Comment by frasmage** [comment]
Hi @rzksbr,

Yes, PHP provides [mechanisms](http://php.net/manual/en/language.oop5.traits.php#language.oop5.traits.conflict
) for specifying which one should take precedence or to rename one of the methods.

Note that in this case, you will probably have to pick one or the other. So you won't have the additional collection utilities provided by one library or the other.

**Comment by rzksbr** [comment]
HI @frasmage ,

Are you saying that I can't use both library together? I tried couple of alternatives and the result was in vain. 
It will be really great if you can help me with the code as I am not an expert in this. 

Thanks in advance

**Comment by frasmage** [comment]
You can totally use both libraries, but you have a little work to do to have access to all features of both.

If you aren't using the helpers applied to Collection from one class or the other, just use `Mediable::newCollection insteadof NestedSet::newCollection`, or vice versa. Mediable's collection mostly just provides [lazy loading helpers](https://laravel-mediable.readthedocs.io/en/latest/mediable.html#lazy-eager-loading), and you can work around that by eager loading from your queries instead (scroll up in the same documentation page).

If you do need the features of both, you should create a new Collection class with the methods of both MediableCollection and whatever NestedSet provides and register your own `newCollection` method which returns an instance of that class.

**Comment by rzksbr** [comment]
Thanks @frasmage ,

It worked
