### ISSUE TITLE
Access to source attribute on MediaUploader instances

### ISSUE THREAD

**Issue by jpenaroche** [plank/laravel-mediable#131]
Hi, is there any way to access, the $source attribute on MediaUploader instance. I mean..., i'm loading an element as an url, but i need to know the mime_type after load the media element, but to access to that property i need to access to the private source attribute, and i believe it is a little frustrating to make a fork for only set a getter method on MediaUploader class, to achieve this need :\

here is my example code:
```php
  $media = MediaUploader::fromSource($url);
  // i had to set the getter method get $source and mime_type
   $mime = $media->getSource()->mimeType();
```

**Comment by frasmage** [comment]
Hi @jpenaroche,

The source adapters are mostly intended to be internal implementation of the adapter. But if you need access to it, you can build the sourceAdapter yourself before passing it to the uploader.

```php
$factory = app(Plank\Mediable\SourceAdapters\SourceAdapterFactory::class);
$adapter = $factory->create($url);
// do something with mimetype
MediaUploader::fromSource($adapter);
```

**Comment by jpenaroche** [comment]
@frasmage worked like a charm thanks man, for your help and for developing this awesome library ;)
