### ISSUE TITLE
detachMedia didn't delete the files in disk

### ISSUE THREAD

**Issue by winter-ice** [plank/laravel-mediable#133]
detachMedia didn't delete the files in disk.Is this expected behavior?

**Comment by winter-ice** [comment]
I read source code,in media model,defined deleted event, but `detachMedia` is not Instantiate model,and the deleted event will not trigger.

**Comment by frasmage** [comment]
Hi @winter-ice, detachMedia is not intended to delete the media record or file. It simply breaks the relationship between a Mediable model and a media record.

To delete the media record and file, use `$media->delete();`
