### ISSUE TITLE
Querying for one tag returns results for other tags as well

### ISSUE THREAD

**Issue by sherkhanz** [plank/laravel-mediable#136]
Hi, 

Thanks for the great package. It saved me considerable time from creating my own implementation. 

I have one issue though and I am not sure if I am doing anything wrong or is it the default behavior of the package. 
I have a multi tenant system where I am assigning media in the following way for a user:

` $post->attachMedia($media, [$hostname, Auth::id()]);`

Where $hostname is the domain and is the primary way I segregate data in my app for multiple tenants. 

The issue is that when I query the media, I get two records for each file type with separate media tags. My query is simple as this:

`$post->getMedia([Auth::id()]);`

let say I have attached a single file called image.png to the $post for user with id 1. Using the above query, I get two records one for tag `1` while other for tag `$hostname`. Is there a way to strictly get results only for a single tag?

Best

**Comment by frasmage** [comment]
Hi @sherkhanz,

I'm not sure, I follow. When you say you get back two records, are you referring to Media models? 

The getMedia() method should return all media records matching at least one of the provided tags. If you are getting back the same record multiple times, is it possible that you somehow either uploading the same file multiple times or attaching the same record multiple times? The first parameter of attachMedia also accepts an array of ids or a collection of Media models.

Let me know if this helps or you are able to provide a little more context.

**Comment by sherkhanz** [comment]
Hi @frasmage, 

Thanks for response. I will try to explain a bit more. 

You are right I am getting two Model records. I save every file with two tags. But do querying only with one tag. (the second one is just for my internal use). However the returned collection contains two records for each file (with same media id), one for each tag. 

What I want to know is how to get Model results only for the tag I have queried and not the other associated tag

**Comment by sherkhanz** [comment]
As an example, I upload and then attach it as follow:

`  $post->attachMedia($media, ['media4', 11]);`

Then I get the media as follow:

`$post->getMedia(11);`

but the results I get contains model record for 'media4' tag as well as follow:

`[
{ aggregate_type: "pdf",
created_at: "2019-07-25 19:08:54",
directory: "attachments",
disk: "public",
extension: "pdf",
filename: "05298",
id: 1,
mime_type: "application/pdf",
pivot: {
   media_id: 1
   mediable_id: 1
   order: 1
   tag: "11"
},
size: 36427,
updated_at: "2019-07-25 19:08:54"},
{ aggregate_type: "pdf",
created_at: "2019-07-25 19:08:54",
directory: "attachments",
disk: "public",
extension: "pdf",
filename: "05298",
id: 1,
mime_type: "application/pdf",
pivot: {
   media_id: 1
   mediable_id: 1
   order: 1
   tag: "media4"
},
size: 36427,
updated_at: "2019-07-25 19:08:54"}
]
`

What I wanted to know was is it possible to get only the Models for the tag I queried and not the related tags? As I have to currently loop over the entire results and remove the 'media4' tag objects. 

Hope I am clear this time. Thanks again

**Comment by frasmage** [comment]
Ok, I think I see where your misunderstanding lies.

So `$media = $posr->getMedia()` is intended to be used to return the media attached to a specific tag. It looks like you are using it to load the relationship then serializing the whole object graph. 

getMedia by default eager loads all media relationships (all tags) from the db then filters down to return the ones you requested.

Check out the `$query->withMedia($tags)` and `$mediable->loadMedia($tags)` methods in the docs to explicitly load only the tags you want before serializing.

**Comment by sherkhanz** [comment]
That work perfectly. Thank you. 
I went through the documents though but as the methods were listed under eager and lazy loading so I didn't gave it a read. My bad and apology for taking your time on something that's already clearly documented. 

Best,
