### ISSUE TITLE
Is it possible to import an entire directory at once?

### ISSUE THREAD

**Issue by adrienne** [plank/laravel-mediable#137]
So I understand that it's possible to do something like this:

```
$disk='uploads';
$path = 'myimg.jpg';
$media = MediaUploader::importPath($disk,$path);
dd($media->getUrl());
```

But that imports one file at a time. What I would like to do is pull in the entire directory, because I have a ton of files from before using mediable. Something like this:

```
$disk='uploads';
$path = '/';
$media = MediaUploader::importPath($disk,$path);
dd($media->getUrl());
```

Is that possible, or do i really have to do it one file at a time?

**Comment by frasmage** [comment]
Bulk import is currently only supported from the artisan command line:
https://laravel-mediable.readthedocs.io/en/latest/commands.html

This effectively just globs the directory and runs importPath on each file in a loop.

**Comment by adrienne** [comment]
That's good enough, thank you!
