### ISSUE TITLE
Get all objects attached to a Media ?

### ISSUE THREAD

**Issue by AurelienMendes** [plank/laravel-mediable#138]
Hi,

Perhaps a stupid question, but does it exist a method to get all attached objects to a Media ?
Something like :
`$objs = $media->getAttached('tag1 tag2')`

Thanks a lot,
Aurelien

**Comment by frasmage** [comment]
Hi @AurelienMendes,

It is possible to get all objects attached to a media for one model type at a time.

`$posts = $media->models('Post')->all()`

If you need to restrict by tags, you can play with the pivot relationship.
