### ISSUE TITLE
S3 file url - $media->fileUrl() not respecting S3 root prefix

### ISSUE THREAD

**Issue by hasnatbabur** [plank/laravel-mediable#139]
Test:
--- Expected
+++ Actual
@@ @@

$media->getUrl() is:
'https://example.com/photos/2019/08/sZ2miLlAa4BRUdpZ7QP05OGxKUxMsNtyQBFIKvKwKw.jpeg'

Storage::disk('s3')->url($media->getDiskPath()) is:
+'https://example.com/public/photos/2019/08/sZ2miLlAa4BRUdpZ7QP05OGxKUxMsNtyQBFIKvKwKw.jpeg'

Please notice that, getUrl() method not including public/ path prefix in the URL.

Am I wrong? Or can the library respect to the root option defined in filesystem config file for s3 driver anyway? Thanks

**Comment by frasmage** [comment]
Hi @hasnatbabur,

Can you give me a little more information about how your filesystem disk is configured?

**Comment by frasmage** [comment]
@hasnatbabur is this still an issue or has this been fixed by 3.0?

**Comment by hasnatbabur** [comment]
@frasmage Thanks for checking.

Please see #143 

For version 3 $media->getUrl() raises this error:
Plank\Mediable\Exceptions\MediaUrlException: Media file /var/www/watchcrunch/storage/app/public/photos/2019/09/photo.jpeg is not part of the public path /var/www/watchcrunch/public

I first if we look at $media->getUrl() issue that will be good for us. Thanks.

**Comment by grafikkaos** [comment]
I have managed to get around this issue by extending the LocalUrlGenerator class and commenting out the lines that check if the path is publicly accessible.

At least for now, everything is working well for my needs especially as I am using tags to get different image sizes.
