### ISSUE TITLE
getVisibility() causing excessive s3 calls

### ISSUE THREAD

**Issue by liran-co** [plank/laravel-mediable#145]
I noticed that when generating URL's to media files, getVisibility() is called, which leads to huge performance issues when there are many media files being loaded. Is this really necessary? Aren't the Laravel disks configured with a 'visibility' key?

<img width="1400" alt="Screen Shot 2019-10-02 at 11 43 18 AM 1" src="https://user-images.githubusercontent.com/5923787/66059358-e753b580-e509-11e9-8245-29a88f411d49.png">

**Comment by frasmage** [comment]
Fixed in version 4.0.0
