### ISSUE TITLE
getUrl() throws an exception in laravel v6

### ISSUE THREAD

**Issue by VeRJiL** [plank/laravel-mediable#150]
Hi, I was using laravel v5.8 and mediable v2.9 but when I install laravel v6 and installed mediable v6, all the modules which were working fine in mediable v2,9 is not working anymore and for every single object that I called `getUrl()` throws an exception.
I dumped the `$post->firstMedia('myTag'); `and It has an object but when I use `->getUrl()` it throws an exception and showing me the absolute path of file not relative. i.e: `file "C:/wamp64/www/project/img/fake.jpg" not found` but there is an image in that path.

**Comment by frasmage** [comment]
Hi @VeRJiL, what version of this package are you using? There was a change in the underlying  flysystem implementation that comes with Laravel 6.0 which caused some issues when upgrading to laravel-mediable 3.x (see discussion #143).

Version 4.0 was released a few days ago which addresses these issues. Does this solve your problem?

**Comment by alexgap360** [comment]
I believe I had the same issue as the OP after upgrading to Lavel v6, can confirm this was resolved by upgrading to mediable 4.0

**Comment by hasnatbabur** [comment]
@VeRJiL I had same issue with version 3. After upgrading to version 4, all is okay.
