### ISSUE TITLE
Any possibility for adding a Uploader (User) ID column or extra json field?

### ISSUE THREAD

**Issue by hasnatbabur** [plank/laravel-mediable#151]
Hi, thanks for awesome support.

I think adding the uploader info into database will help us to track which user uploaded what media for both analytics and security.

Can you consider this feature? Thanks.

**Comment by frasmage** [comment]
Hi @hasnatbabur,

We have no interest in including this kind of custom logic in the core library, but it is easy enough to implement this yourself.

First, add whatever custom columns you need to the database table.
Then, when you upload the file, do something like this

```php
MediaUploader::fromSource(...)
    ->beforeSave(function(Media $media) use ($request, $user) {
        $media->user_agent = $request->getHeader('User-Agent');
        $media->uploader_id = $user->id
    })->upload()
```

If you need to add functionality to the Media class to support these fields (e.g. adding relationship methods), you can extend the Media class and tell the system to use that class instead in the [config](https://laravel-mediable.readthedocs.io/en/latest/configuration.html#extending-functionality):
