### ISSUE TITLE
custom MediaUploader

### ISSUE THREAD

**Issue by Surt** [plank/laravel-mediable#152]
HI all,

I'm triying to create my own MediaUploader with a new method `toLocation` where I simple make a `toDestination` to a on-the-fly disk. 

There is no problem at all, extending MediaUploader, a new facade...

But now I want to `populateModel` with new info (my `media` table does have some info about the "on the fly disk". The problem here is: almost all methods on MediaUploader are private so I can not add my custom information there. 

It is possible to make those methods protected instead of private? Any way to do it in another way?

P.D. Thanks for the this great library

**Comment by frasmage** [comment]
Hi @Surt,

Anything `private` is done intentionally as it indicates internals that could change in the future without warning. You could override the method that calls it and point to a new method, though you would be doing so at your own risk of conflicts with future versions.

Can you not just use the `MediaUploader::beforeSave()` callback to add or modify the fields on the Media model before it is saved to the DB?

**Comment by Surt** [comment]
You are right! I was absorbed in the extension and didn't think of it. Sorry for bothering here.

Thanks!
