### ISSUE TITLE
Integrate Google Drive Service

### ISSUE THREAD

**Issue by achatzi78** [plank/laravel-mediable#153]
Hi.

First of all, congrats on your package, it really saved my behind on the project I am working on.  It made handling of files a breeze.

I have a new requirement for this project and I was wondering if it can be implemented with your package.

The project owner wants to use Google Drive for storing media, so I used this guide https://github.com/ivanvermeyen/laravel-google-drive-demo to set it up.  I have managed to upload files just fine but now the real fun begins.

These are the issues I have (so far):

1. Since the GDrive works with id and not with filename, I have to find a way to save the id that the api returns in the Media model.
2. Also, I have to modify your replace function to search with id and not with filename, so to delete the previous file and upload the new one.
3. Finally, I have to find make an new UrlGenerator for retrieving the files.

Do you have some idea or guidelines where to begin with all that?  If I can solve even the first one, I could work my way to the other ones.

Looking forward for any assistance.

Thanks.

**Comment by frasmage** [comment]
Hey there, happy to hear you are enjoying the package!

I would start by recommending the usual extension points:
- use the MediaUploader::beforeSave() to add additional fields to the Media
record, such as your ID. You might also be able to assign the ID as the
filename
- you can extend the Media class as long as you register yours in the
config.
- creating a custom UrlGenerator is also fairly straightforward, once again
extend the class and register it to the config.

If you feel so inclined you are also welcome to put up a PR if you think
your solution would be worth including in the core package.
