### ISSUE TITLE
Get all "mediables" for Media

### ISSUE THREAD

**Issue by Surt** [plank/laravel-mediable#155]
Hi all,

Having a `Media`, I want to retrieve all the `MorphedBy` elements.
The only way I know is doing:

```php

   // Media.php

      public function mediables()
    {
        return $this->hasMany(Mediables::class, 'media_id');
    }

    public function getRelated()
    {
        return $this->load('mediables.mediable')->mediables->pluck('mediable')->flatten();
    }

```

```php

   // mediables table pivot model

  
    protected $table = 'mediables';

    /**
     * @return MorphTo
     */
    public function mediable()
    {
        return $this->morphTo('mediable', 'mediable_type', 'mediable_id');
    }

    /**
     * @return BelongsTo
     */
    public function media()
    {
        return $this->belongsTo(Media::class, 'media_id');
    }


```  

in this way, I can use it like:

```php
$media->getRelated();
``` 

I created the `Mediables` model etc. everything is working as expected but I was wondering if the library already have a method to do this.

**Comment by frasmage** [comment]
Hi @Surt,

Yes, the laravel polymorphic relationship doesn't provide a particularly easy way to do this. Your solution seems decent though. You might want to check how many queries are getting executed here (I'm not sure if this would cause N+1).

I'm curious what the use case for this would be?
