### ISSUE TITLE
Creating a mock file for unit test

### ISSUE THREAD

**Issue by VeRJiL** [plank/laravel-mediable#156]
Hi,
I am trying to test my `store()` method which inserts a record in the database for a article and also attachs a mediable to the article if there is a file in the form.
how should I build a proper mock or fake file in-order to test my method or any other way.

There are ways to mock a file but I get this exception when I am trying to test the `store() `method with a mock file.

Plank\Mediable\Exceptions\MediaUpload\FileNotSupportedException: File with mime of `application/octet-stream` and extension `` is not recognized`.

**Comment by frasmage** [comment]
Hi @VeRJiL,

I'm guessing the mock file has empty file contents which the mime-type guesser will interpret as being `application/octet-stream`. Could you try setting up your test to allow that particular mime type with `$uploader->setAllowedMimeTypes()`?

Alternatively mock the source adapter passed to the MediaUploader to return the mimes/extensions that you expect.

**Comment by VeRJiL** [comment]
@frasmage Thanks for the response, It seems that I am making the mock file in a wrong way.
the `isValid() `method from  `Symfony\Component\HttpFoundation\File\UploadedFile ` class is rejecting my file because` is_uploaded_file($this->getPathname())` is returning false.

the way I mocked my file:

```
        $file = new UploadedFile(
            public_path('test/images/m16.jpg'),
            'm16.jpg',
            'image/jpg',
            $error = null,
            $test = false
        );

        $response = $this->post("/admin/category-items/{$category->id}", [
            'name' => 'category 1',
            'profilePicture' => $file
        ]);
```

**Comment by VeRJiL** [comment]
@frasmage 
I think there should be a way which we can  test mock files when using this package. Because it is always checking if the file is posted or not and if it is not then it returns an exception.

```

namespace Plank\Mediable;

/**
 * Media Uploader.
 *
 * Validates files, uploads them to disk and generates Media
 */
class MediaUploader
{

    /**
     * Ensure that a valid source has been provided.
     * @return void
     * @throws ConfigurationException If no source is provided
     * @throws FileNotFoundException If the source is invalid
     */
    private function verifySource(): void
    {
        if (empty($this->source)) {
            throw ConfigurationException::noSourceProvided();
        }

       // this line of code is not working for mock files.
        if (!$this->source->valid()) {
            throw FileNotFoundException::fileNotFound($this->source->path());
        }
    }
}
```

**Comment by Surt** [comment]
Any clue on this? I can't test it using any Uploaded file fake or not.

**Comment by frasmage** [comment]
Hi @Surt,

The validity check is happening within the Symfony component. I would recommend mocking the UploadedFile itself. Perhaps try something like this?

```
$file = $this
->getMockBuilder('Symfony\Component\HttpFoundation\File\UploadedFile')
->enableOriginalConstructor()
->setConstructorArgs(...)
->setMethods(['isValid'])
->getMock();

$file->expects($this->any())
->method('isValid')
->willReturn(true);
```
