### ISSUE TITLE
Eloquent Query returning Plank\Mediable\MediableCollection

### ISSUE THREAD

**Issue by hasnatbabur** [plank/laravel-mediable#158]
Database query Collection of Mediable Model returning Plank\Mediable\MediableCollection instead of Illuminate\Support\Collection.

Is there any special reason for setting Plank\Mediable\MediableCollection as collection instead default Illuminate\Support\Collection for mediable models? Can not we use the default one?

Can anyone please help? If you need more details please ask. Thanks

**Comment by frasmage** [comment]
Hi @hasnatbabur,

`MediableCollection` extends `Illuminate\Database\Eloquent\Collection`, so it should have all features of the base class while also adding a few additional features.

If you need to use the custom collections of another package instead, you can change which collection class your model is using by overriding the [newCollection()](https://github.com/plank/laravel-mediable/blob/master/src/Mediable.php#L544) method in the classes use the Mediable trait.

**Comment by hasnatbabur** [comment]
Thanks @frasmage . You are so great person.
