### ISSUE TITLE
sync by media id

### ISSUE THREAD

**Issue by zefexdeveloper** [plank/laravel-mediable#159]
I have an use case where I receive a list of `id`s of `Media` (instead of the model itself) and I need to sync with `gallery` tag. I noticed that `syncMedia`  asks for `$model`. Is there a way for me to do that using the `id`s?

**Comment by frasmage** [comment]
Yes, `syncMedia()` (and all other attachment methods) accept an array of IDs, [among other things](https://laravel-mediable.readthedocs.io/en/latest/mediable.html#attaching-media).

**Comment by zefexdeveloper** [comment]
@frasmage Weird, I tested and it didn't work, I tested again and now works, sorry.
