### ISSUE TITLE
error migrate in laravel 5.3

### ISSUE THREAD

**Issue by thandonguocmo2020** [plank/laravel-mediable#16]
migrate in laravel 5.3 error use package 

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `media` add uniq
  ue `media_disk_directory_filename_extension_unique`(`disk`, `directory`, `filename`, `extension`))
  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

**Comment by thandonguocmo2020** [comment]
run sql :+1: 

set GLOBAL storage_engine='InnoDb';

**Comment by frasmage** [comment]
Hi @thandonguocmo2020,

Yes, some storage engines have tighter limits on index size. If changing to a newer engine, as you did, isn't an option, then one could also reduce the size of those columns or remove the index altogether. It is there as the recommended behaviour, providing a little security against accidental duplication.

(sorry about the slow reply, just got back from vacation)

**Comment by thandonguocmo2020** [comment]
Hi thank your.

**Comment by gitbjorn** [comment]
For other and for myself as a reference, I handled it this way:

media
  ALTER TABLE media ADD UNIQUE KEY `media_disk_directory_filename_extension_unique` (`disk`,`directory`(30),`filename`(140),`extension`(6));
  ALTER TABLE media ADD KEY `media_disk_directory_index` (`disk`,`directory`);
  ALTER TABLE media ADD   KEY `media_aggregate_type_index` (`aggregate_type`)

mediables
  ALTER TABLE mediables ADD PRIMARY KEY (`media_id`,`mediable_type`,`mediable_id`,`tag`);
  ALTER TABLE mediables ADD KEY `mediables_mediable_id_mediable_type_index` (`mediable_id`,`mediable_type`);
  ALTER TABLE mediables ADD KEY `mediables_tag_index` (`tag`);
  ALTER TABLE mediables ADD KEY `mediables_order_index` (`order`);
  ALTER TABLE mediables ADD CONSTRAINT `mediables_media_id_foreign` FOREIGN KEY (`media_id`) REFERENCES `media` (`id`) ON DELETE CASCADE;
