### ISSUE TITLE
Working with mediable tags

### ISSUE THREAD

**Issue by steveerg** [plank/laravel-mediable#161]
HI, first of all, thank you for sharing this good laravel package.

Now, i'm facing problem to update mediable tags.

I've got a mediable traited **Product** model with many media attached to it under one tag "media_collection".
Now I need that one of this media must be tagged as "default_media" without attaching a new mediable and duplicate entry.

This "defautl_media" tags must be a "toggle" between the mediables of the same product.

Is there a "simple" or "clean" way provided by this package to working directly on mediable tags?
Thank you!

**Comment by frasmage** [comment]
You can absolutely tag the the same media and mediable combination multiple times. Doing so will always add an extra row to the mediables pivot table, but that doesn't mean you have duplicated your media. The tag relations can be loaded individually or together.

**Comment by steveerg** [comment]
Wow, how fast! 👍 All is clear...but what about transform the tag column into a "tags" json column with multiple tags? Suppose this will be a good enhancement for this package.
Thank you.

**Comment by frasmage** [comment]
You can iterate the $media relation to see all of your tags. There are a few methods that do basic operations you might want

- getMediaMatchAll($tags), get media matching all specified tags
- getAllMediaByTag(), group media by tag name
- getTagsForMedia($media), list tags that a media is attached to
