### ISSUE TITLE
Error when installing on Laravel 6.17

### ISSUE THREAD

**Issue by alsahlawi** [plank/laravel-mediable#165]
When I tried to include this package into my project, using composer, it throws an exception. here is an exception trace: 

  Exception trace:
` 1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError("Invalid argument supplied for foreach()", "C:\laragon\www\restro\vendor\plank\laravel-mediable\src\MediableServiceProvider.php", [Object(Illuminate\Foundation\Application), Object(Plank\Mediable\SourceAdapters\SourceAdapterFactory)])
      C:\laragon\www\restro\vendor\plank\laravel-mediable\src\MediableServiceProvider.php:70

  2   Plank\Mediable\MediableServiceProvider::Plank\Mediable\{closure}(Object(Illuminate\Foundation\Application), [])
      C:\laragon\www\restro\vendor\laravel\framework\src\Illuminate\Container\Container.php:799`

**Comment by frasmage** [comment]
Hello @alsahlawi,

It sounds like you have not properly set up your config. Have you published your config files to your project?

```
php artisan vendor:publish --provider="Plank\Mediable\MediableServiceProvider"
```

If you have, it sounds lie you deleted or changed something incorrectly. The `mediable.source_adapters.class` and `mediable.source_adapters.pattern` configs are both expected to be arrays. Somehow you are getting a different datatype there. If you are not able to figure out what you changed, could you paste the contents of your /config/mediable.php file?
