### ISSUE TITLE
Issue with latest doctrine/inflector update

### ISSUE THREAD

**Issue by Dopey117** [plank/laravel-mediable#175]
Just ran composer update and doctrine/inflector (1.3.1 => 1.4.0) is now throwing an error for table "medias" does not exist when trying to use mediables. 

I justed added "doctrine/inflector": "1.3.1" to my composer.json for now and reverted to that

**Comment by frasmage** [comment]
Hi @Dopey117, seems to be a bug in doctrine/inflector:1.4.0, doesn't seem to occur in either 1.4.1 or 2.0.1.

That said I will push a quick change to explicitly define the table name on the `Media` model, so that Laravel doesn't need to depend on the inflector.
