### ISSUE TITLE
What's the easiest way to update an existing media ?

### ISSUE THREAD

**Issue by nicolasbinet** [plank/laravel-mediable#18]
I'm trying to figure out a way to update a saved media. 
Relations can be updated, but not the base file.
Am-I right ?

**Comment by frasmage** [comment]
Hi Nicholas,

What do you mean by update? Media is just an eloquent model, so you can
adjust any of its attributes manually, I.e. `$media->mime_type =
'image/jpeg';` then call the save() method to update the records.

(On vacation so I might be slow to reply)

**Comment by nicolasbinet** [comment]
Let me know if I'm wrong, but I'm using MediaUploader::fromSource to upload and create a new Media.
But, there is no "updateFromSource" method to update an existing one.

**Comment by frasmage** [comment]
Hi Nicolas,

What exactly has changed between the file on disk and the data stored in
the db record?

For the most part, the library considers media files to be constant once
uploaded, as this fits with the most common usage. That said, if you are
manipulating the file and you know what might change (e.g. size, mime,
etc.), you can update the fields manually, as described in the message
above.

You can also simply delete and reimport the media record.

Alternatively, the `media:import` command has a `--force` option, which
checks if any files in a directory no longer match their records and update
accordingly.

Finally, adding a proper `MediaUploader::update()` method is on my to-do
list for the next major or minor version. This would behave like
`media:import --force` for a single file at a time. Still in the works
though.

Hope this helps.

**Comment by nicolasbinet** [comment]
Hi frasmage,

Thanks for your extensive answer.

In my case, I'm trying to create a mediamanager the "wordpress way". Have a centralized repositories for medias, and associate them along the way to different models. 
And sometimes I will, or one of my client will, want to re-upload a new version of a file, thus updating all it's uses.
In that case I don't want to delete the file, as it would break all relations.

I hope this clarifies my need.

Nicolas

**Comment by frasmage** [comment]
Hi Nicolas,

OK, I see what you mean. The MediaUploader class wouldn't be able to do
that out of the box (though the update feature I'm working on would help).

In the meantime, you could use the uploader to place the file in a temp
location (for validation, media generation,  etc.), then manually swap the
two files on disk and update the original record with the attributes of the
new one.

**Comment by frasmage** [comment]
Hi @nicolasbinet, this is now implemented in version 2.0, see [the docs](http://laravel-mediable.readthedocs.io/en/latest/uploader.html#importing-files) for instructions on this feature.
