### ISSUE TITLE
Instagram Avatar Url resolves to wrong file extension

### ISSUE THREAD

**Issue by simonschaufi** [plank/laravel-mediable#182]
Hi, I'm using this package after i have done a social login, fetched the avatar url from instagram and then generate a thumbnail from it.

My instagram avatar has this url: https://scontent.cdninstagram.com/v/t51.2885-19/s150x150/16788506_1448219765208665_6129095846685310976_a.jpg?_nc_ht=scontent.cdninstagram.com&_nc_ohc=NQ07gFabSIgAX_8Qk0x&oh=a1f873fc40509a8ff4104b94999af6e1&oe=5EFFE079 and I'm using this code to generate the thumbnail:

```php
 $thumbnail = MediaUploader::fromSource($source)
    ->useFilename('avatar')
    ->toDirectory('avatars')
    ->upload();
```

and when i put in the url as `$source`, this line in the RemoteUrlAdapter `$extension = pathinfo($this->source, PATHINFO_EXTENSION);` resolves the extension as `com&_nc_ohc=NQ07gFabSIgAX_8Qk0x&oh=a1f873fc40509a8ff4104b94999af6e1&oe=5EFFE079` (everything after the last dot) which is course not what I expect. Instead the query parameters should be removed before the pathinfo is fetched and then the file extension should be `jpg`

**Comment by frasmage** [comment]
Good catch! I should be able to pull a fix together fairly quickly.

**Comment by frasmage** [comment]
Fixed in 4.2.3

**Comment by simonschaufi** [comment]
See #183

**Comment by simonschaufi** [comment]
@frasmage thank you for the quick fix!
