### ISSUE TITLE
Error Incorrect integer value: '' for column 'media_id' 

### ISSUE THREAD

**Issue by Younesi** [plank/laravel-mediable#185]
I'm uploading files according to documentation from **local** storage:
```
        $media = MediaUploader::fromSource($path)
                ->toDestination('public', $directory)
                ->onDuplicateUpdate()
                ->upload();
```
But i get this error:

```SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'media_id' at row 1 (SQL: insert into `mediables` (`media_id`, `mediable_id`, `mediable_type`, `order`, `tag`) values (, 17, App\Models\MyModel, 1, image))```

Any help would be appreciated.

**Comment by frasmage** [comment]
Hi there, 

Uploading media writes to the `media` table, not `mediables` which is used for assignment. I believe you are doing something wrong when trying to attach the media record to your MyModel entity. Most likely the Media record hasn't actually been saved to the database first. 

Can you provide a complete snippet of the code that you are using for uploading and assigning the Media to your entity?

**Comment by ivantree** [comment]
#190
