### ISSUE TITLE
Improvement: generate unique filename if not passed during moving to disk

### ISSUE THREAD

**Issue by siarheipashkevich** [plank/laravel-mediable#189]
Hi @frasmage.

I'm getting the error of the filename duplication during moving file from public disk to cloud with the same name of the prev file uploading and moving.
Because prev file deleted from public disk and I possible upload file with the same name to public disk. But when I try to move this file to cloud `moveToDisk` I got the error of the duplication and in my code I should generate unique filename for **target** disk and only after that should call `moveToDisk` with generated unique filename.

I think will be better to generate unique filename for target disk inside `moveToDisk` method if the `filename` parameter not passed.

What do you think about this suggestion?

**Comment by frasmage** [comment]
I'm not interested in changing the base behaviour, which is consistent with the other move/copy methods. This sounds like it is specific to your use case. If you want a randomized filename, just pass in your own value to the `$filename` parameter. For example, you could try something like:

```
$media->moveToDisk($disk, $directory, bin2hex(random_bytes(32));
```

**Comment by siarheipashkevich** [comment]
@frasmage I agree with you. In your case the filename will be random but will be better to save original file name with any numeric postfix.

**Comment by frasmage** [comment]
That would be easily done the same way.

```
$media->moveToDisk($disk, $directory, $media->filename . '-' . bin2hex(random_bytes(8)));
```
