### ISSUE TITLE
Would-it be possible to add a sortable behavior on the Mediables

### ISSUE THREAD

**Issue by nicolasbinet** [plank/laravel-mediable#19]
your package allows versatile usages, I'm justing missing a "sortable" on Mediables grouped by tags.
That would allow even more use cases.

**Comment by frasmage** [comment]
Hi Nicholas,

That is a good idea, if a sister complex one. I'll think about an
implementation when I return from vacation.

I'm the meantime, you are welcome to take a stab at it yourself. Pull
requests always welcome :)

**Comment by nicolasbinet** [comment]
HI @frasmage ,

thanks for your answer, in fact I'm trying to implement boxfrommars/rutorika-sortable but I face multiple problems (many to many polymorphic support, trait function "move" name conflict). I'm reverting to a more simple implementation for the moment.

Nicolas

**Comment by frasmage** [comment]
Hi @nicolasbinet, I have added a simple implementation of this to the freshly released version 2.0.
