### ISSUE TITLE
attachMedia() - duplicate record with media

### ISSUE THREAD

**Issue by ivantree** [plank/laravel-mediable#190]
$user = Auth()->guard()->user();

$media = MediaUploader::fromSource($request->file('avatar'))
            ->useHashForFilename()
            ->upload();
$user->attachMedia($media, 'avatar');

![20200801203159](https://user-images.githubusercontent.com/9014680/89101802-1b537c00-d436-11ea-9323-d903e8d91c71.png)

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-App\Models\Access\User\User-1-avatar' for key 'PRIMARY' (SQL: insert into `mediables` (`media_id`, `mediable_id`, `mediable_type`, `order`, `tag`) values (0, 1, App\Models\Access\User\User, 2, avatar))

env: laravel 6.18
        mediable 4.3.1

**Comment by ivantree** [comment]
mediable 4.3.1

**Comment by frasmage** [comment]
Hi @ivantree,

Could you provide the output of ``SHOW CREATE TABLE `media`;``? Is it possible your primary key on the `media` table is not correctly set up to be auto-incrementing? Somehow you are getting a primary ID of `0`.

**Comment by ivantree** [comment]
media   CREATE TABLE `media` (                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
          `id` int(11) unsigned NOT NULL AUTO_INCREMENT,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
          `uuid` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
          `disk` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
          `directory` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
          `filename` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
          `extension` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
          `mime_type` varchar(128) COLLATE utf8mb4_unicode_ci NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       
          `aggregate_type` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
          `size` int(10) unsigned NOT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
          `created_at` timestamp NULL DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
          `updated_at` timestamp NULL DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
          `created_by` int(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          `updated_by` int(11) DEFAULT NULL,                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  
          PRIMARY KEY (`id`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
          UNIQUE KEY `media_disk_directory_filename_extension_unique` (`disk`,`directory`,`filename`,`extension`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
          UNIQUE KEY `uuid` (`uuid`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         
          KEY `media_disk_directory_index` (`disk`,`directory`),                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              
          KEY `media_aggregate_type_index` (`aggregate_type`)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 
        ) ENGINE=MyISAM AUTO_INCREMENT=73 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci

**Comment by ivantree** [comment]
media data 👍 
![20200808140608](https://user-images.githubusercontent.com/9014680/89703770-69a9d300-d980-11ea-8388-df4dbefa3f05.png)

**Comment by frasmage** [comment]
Hmm, that all looks correct. if you were to breakpoint or dump and die (`dd()`) after the `upload()` statement, does the $media record  have a value for the `id` field?

**Comment by ivantree** [comment]
method:
![E2584073-2BBC-4acf-B221-8B50AB0CAF9E](https://user-images.githubusercontent.com/9014680/90250710-14356080-de6f-11ea-92c3-79f8b2cc2217.png)

return:
![B059DE6D-8680-438b-8B17-5A13374CC2C3](https://user-images.githubusercontent.com/9014680/90250730-1d263200-de6f-11ea-80ea-db0a7ed64f64.png)

**Comment by frasmage** [comment]
This is really strange. I am able to run that exact snippet (minus your extra columns) and receive an integer ID as expected.

I'm thinking something is preventing the model from saving correctly. Guessing wildly here: do you have any event listeners on the `'saving'` or `'creating'` model events (possibly intended for other model types) that might be returning `false`? Similarly if you add a listener for the `'created'` and `'saved'` model events, do you actually get a hit when you run this code?

Alternatively, could there be a reason why PDO's lastInsertID is returning false?
