### ISSUE TITLE
Could not recognize source, `Illuminate\Http\UploadedFile` provided.

### ISSUE THREAD

**Issue by Wikiki** [plank/laravel-mediable#193]
Hi,

I'm trying to integrate this package with my Laravel 7 application but I'm facing this issue `Could not recognize source, `Illuminate\Http\UploadedFile` provided. ` when trying to upload an image.

Here is my code:

```php
// In controller:
MyModel::create($request->only([
	'name',
	'logo',
]));


// In model
public function setLogoAttribute($logo)
	{
		if ($logo) {
			$media = \MediaUploader::fromSource($logo)
				->useHashForFilename()
				->setModelClass(self::class)
				->setAllowedAggregateTypes(['image'])
				->upload();

			$this->attachMedia($media, 'logo');
		}

		return $this;
	}
```

**Comment by frasmage** [comment]
Hi @Wikiki,

Can you provide the contents of your `config/mediable.php` file? You may have misconfigured the mapping of your source adapters. You should have one like the following.

```php
source_adapters' => [
        'class' => [
                Symfony\Component\HttpFoundation\File\UploadedFile::class => Plank\Mediable\SourceAdapters\UploadedFileAdapter::class
                // ...
```

`Illuminate\Http\UploadedFile` extends the symfony equivalent, so it should be handled by that as well

**Comment by Wikiki** [comment]
Thanks a lot. I forgot to run `php artisan config cache` artisan command after installin the package. It's working perfectly now :-).

**Comment by Wikiki** [comment]
Unfortunately I'm facing a  new issue: media are stored in DB correctly with the right disk, and information but when trying to get the medi Url I having the wrong path:

Here are my data in dB:
<img width="699" alt="Screenshot 2020-08-17 at 09 23 12" src="https://user-images.githubusercontent.com/24766179/90369060-5d520400-e06b-11ea-9824-6d79377b55bb.png">

The Url path I get when calling `$myModel->firstMedia('logo')->getUrl()` : `http://127.0.0.1:8000/storage/brands/7b603230c30fd1daaf9e0ab5d30a094b.png`. As you can see the disk in path is `storage`but instead of `uploads` like in DB.

My Config for disks is:
```php
// mediable.php
/*
     * Name to be used for mediables joining table
     */
    'mediables_table' => 'mediables',

    /*
     * Filesystem disk to use if none is specified
     */
    'default_disk' => 'uploads',


// filesystem.php
'disks' => [

        'local' => [
            'driver' => 'local',
            'root' => storage_path('app'),
        ],

        'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],
    
        'uploads' => [
            'driver' => 'local',
            'root'   => public_path('uploads'),
            'visibility' => 'public',
        ],


```

**Comment by Wikiki** [comment]
Found it. I had to add `url`property to my disk definition:
```php
'uploads' => [
            'driver' => 'local',
            'root'   => public_path('uploads'),
            'url' => env('APP_URL').'/uploads',
            'visibility' => 'public',
        ],
```
