### ISSUE TITLE
Mediable 4.3.1 requires league/flysystem ~1.0.23 and unable to install on Laravel v6.18.35

### ISSUE THREAD

**Issue by 01011010** [plank/laravel-mediable#194]
Hey I'm running into the following problem on a fresh Laravel installation:

league/flysystem 1.1.1 Filesystem abstraction: Many filesystems, one API.
├──laravel/framework v6.18.35 (requires league/flysystem ^1.0.34)

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Conclusion: don't install plank/laravel-mediable 4.3.1
    - Conclusion: remove league/flysystem 1.1.1
    - Installation request for plank/laravel-mediable ^4.3 -> satisfiable by plank/laravel-mediable[4.3.0, 4.3.1].
    - Conclusion: don't install league/flysystem 1.1.1

plank/laravel-mediable 4.3.0 requires league/flysystem ~1.0.23 -> satisfiable by league/flysystem[1.0.23, 1.0.24, 1.0.25, 1.0.26, 1.0.27, 1.0.28, 1.0.29, 1.0.30, 1.0.31, 1.0.32, 1.0.33, 1.0.34, 1.0.35, 1.0.36, 1.0.37, 1.0.38, 1.0.39, 1.0.40, 1.0.41, 1.0.42, 1.0.43, 1.0.44, 1.0.45, 1.0.46, 1.0.47, 1.0.48, 1.0.49, 1.0.50, 1.0.51, 1.0.52, 1.0.53, 1.0.54, 1.0.55, 1.0.56, 1.0.57, 1.0.58, 1.0.59, 1.0.60, 1.0.61, 1.0.62, 1.0.63, 1.0.64, 1.0.65, 1.0.66, 1.0.67, 1.0.68, 1.0.69, 1.0.70, 1.0.x-dev].

On my local dev server, under a previous Laravel installation I don't have this issue:
league/flysystem 1.0.69 Filesystem abstraction: Many filesystems, one API.
├──laravel/framework v6.18.15 (requires league/flysystem ^1.0.8)

Is it me doing something wrong, or what should be the preferred option here?

**Comment by frasmage** [comment]
Hi @01011010, 

My bad. Those version constraints should be using carets instead of tildes (`^1.0.23` vs. `~1.0.23`), so it allows minor version bumps. I'll prepare a quick patch release to address that shortly.

**Comment by frasmage** [comment]
Fixed in version 4.3.2
