### ISSUE TITLE
Could not recognize source

### ISSUE THREAD

**Issue by borisdamevin** [plank/laravel-mediable#2]
Hi,

When I want upload a file, I have this error : `Could not recognize source, 'poster_3_fury_road_mad_max_by_cesaria_yohann-d8rd450.jpg' provided.`

My code, is the exemple code from documentation:

    $media = MediaUploader::fromSource($request->input('media'))
        ->toDestination('public', 'thumbnails')
        ->upload();

One idea ?
Thank you.

**Comment by frasmage** [comment]
Hi There,

It sounds like you are trying to pass a string with a filename to the uploader, when you should be passing a file reference.

Make sure that your `<form>` has the `enctype="multipart/form-data"` attribute, then use the `$request->file($field)` method to refer to the input, where `$field` is the name attribute of the file input input. For example:

```html
<form action="..." method="..." enctype="multipart/form-data">
    <input type="file" name="media">
    <button type="submit">Submit</button>
</form>
```


```php
$media = MediaUploader::fromSource($request->file('media'))->toDestination('public', 'thumbnails')->upload();
```

Let me know if you still have issues.

**Comment by borisdamevin** [comment]
Of course, the `enctype="multipart/form-data"` was missing, my bad :).

Thank you.
