### ISSUE TITLE
define model in config/mediable.php

### ISSUE THREAD

**Issue by zyimm** [plank/laravel-mediable#201]
**Define model in config/mediable.php**
```php
    /*
     * FQCN of the model to use for media
     *
     * Should extend `Plank\Mediable\Media`
     */
    'model' => \App\Models\Item::class,
```

**But in vendor/plank/laravel-mediable/src/MediaUploader.php  line 826**

``` php
//If you redefine the value of the $table property in the model, the table  in the database will not be found
 $model->{$model->getKeyName()} = Media::where('disk', $model->disk);

Base table or view not found: 1146 Table 'image_host.media' doesn't exist
```
Should be used ？
``` php
//This correction will prevent the table names of the database from being dependent on being modified
 $model->{$model->getKeyName()} = $this->makeModel()::where('disk', $model->disk);
```

**env: laravel 8.0**
**mediable:4.4.1**

**Comment by frasmage** [comment]
Hi @zyimm,

Thanks for bringing this to my attention, should be fixed in 4.4.2!

I guess you are the first person to try using a custom table name 😄

**Comment by zyimm** [comment]
If I already have a table name in my database that media is using for other data storage, there will be a table name conflict？

**Comment by frasmage** [comment]
Hi @zyimm, are you saying that you are still having issues? This should now use the table name of the model using in the config for all operations
