### ISSUE TITLE
Eloquent model relationship does not exist on Plank\Mediable\MediableCollection

### ISSUE THREAD

**Issue by smccoy78** [plank/laravel-mediable#208]
I am trying to access a relationship on my model that is using the Mediable trait. When I do I get an error that "Method Plank\Mediable\MediableCollection::settings does not exist.". I am just trying to query the settings relationship on my model.

**Comment by frasmage** [comment]
Hi @smccoy78,

MediableCollection is not a model, but a set of models (it extends Laravel's Collection class). As such the relationship that you want isn't on the collection, but on the models within it. Aside from the particular subclass that you are seeing, your questions isn't anything specific to this package, this is just how Eloquent presents result sets.


You can simply iterate over the contents of the collection to access all of the attributes of the models

```php
foreach($mediableCollection as $model) {
    $settings = $model->settings
}
```

or retrieve the first result from the collection to do the same

```php
$settings = $mediaCollection->first()->settings;
```

**Comment by smccoy78** [comment]
That is the problem, I am not trying to access MediableCollection. I am trying to access my Product models settings relationship. I don't understand how the issue I am seeing isn't specific to this package. Why would Product::settings return Plank\Mediable\MediableCollection::settings if it wasn't related to this package? If I remove the Mediable trait I do not get the error, but I lose the functionality given by the trait.

**Comment by ls-sean-fraser** [comment]
MediableCollection extends the Laravel Eloquent Collection. Please provide the code snippet that is causing the issue.
