### ISSUE TITLE
Signed Urls for private files

### ISSUE THREAD

**Issue by ravdeepsingh22** [plank/laravel-mediable#209]
How to generate Signed URL with timeout for S3 and relevant services

**Comment by frasmage** [comment]
Hi there, someone started looking into adding this feature, but never got around to finishing it: #135

You are more than welcome to either work his partial solution into your own code or open another PR to get it merged into the base library

**Comment by frasmage** [comment]
These feature has been released as part of 5.0.0

**Comment by ravdeepsingh22** [comment]
@frasmage Awesome!
Thankyou so much !!

**Comment by ravdeepsingh22** [comment]
@frasmage Any Documentation on How to generate the Signed Urls ?

**Comment by ls-sean-fraser** [comment]
Yes: https://laravel-mediable.readthedocs.io/en/latest/media.html#urls-and-downloads
