### ISSUE TITLE
Feature Request: Saving original filename in database?

### ISSUE THREAD

**Issue by hasnatbabur** [plank/laravel-mediable#211]
It will be nice if we can show original filename instead long random string, while showing a bunch of files. Do you think implementing it worth? Thanks

**Comment by frasmage** [comment]
Hi @hasnatbabur,

I'm a little confused by this request, the MediaUploader already allows for either the original filename (default), a custom name or the md5 hash of the file to be used as the filename. 

Are you asking to have both the hash and the original filename? In that case I would recommend customizing your model, add add another column `original_filename` to your database and populating it from the beforeSave callback like this:

```php
MediaUploader::fromSource(...)
    ->beforeSave(function(Media $media, SourceAdapter $source) {
        $media->original_filename = $source->filename();
    )->upload();

**Comment by hasnatbabur** [comment]
@frasmage Thanks I was asking for both name. Your solution should work perfectly. Thanks a lot for giving your time on this. <3
