### ISSUE TITLE
Feature Request: Configurable table names for migrations

### ISSUE THREAD

**Issue by Towanime** [plank/laravel-mediable#219]
We currently have a media and mediable table in our system and we were planning to migrate to this library but there was some naming conflicts in the database, I managed to do it locally by changing the name directly in the vendor package but this won't work when automatically deployed. 

What I could see happening is adding a new key `media_table` in [config](https://github.com/plank/laravel-mediable/blob/master/config/mediable.php) and make migrations get it from the config, after that I could extend the media model and set the custom table (or leave the default one but I'm not sure how it would get the custom table name when initializing [here](https://github.com/plank/laravel-mediable/blob/master/src/Media.php#L65))

Do you think is possible to add this? Any other thoughts?

**Comment by frasmage** [comment]
What exactly is the use case that you already have a `media` and `mediable` in your database?

Are you trying to upgrade from 4.x to 5.x? The migration mechanism changed, please see the the [upgrading](https://github.com/plank/laravel-mediable/blob/master/UPGRADING.md) notes

**Comment by Towanime** [comment]
My current `media` table is coming from another library ([Laravel Media Library](https://github.com/spatie/laravel-medialibrary) and `mediable` is another table part of our system. Eventually the current `media` table would go away but for now there's this conflict.

**Comment by frasmage** [comment]
Cool, I'm honoured that you are making the switch to our package!

My recommendation:
- Copy the migration file from this package under the same name (see that upgrading link)
- Rename the tables in the migration file to your intended names
- Create your own custom `Media` class extending `Plank\Mediable\Media`, set the `$table` property on that class to your media table
- Set the `'model'` key in the config file to your custom class
- Set the `'mediables_table'` key in the config file to your mediable table name

**Comment by siarheipashkevich** [comment]
@Towanime why are you switching from your current package to this one?

**Comment by Towanime** [comment]
@frasmage thanks for this! I haven't had a chance to try it but I'll comment here when it's done.

@siarheipashkevich the "handling duplicates" feature out of the box and the current one being overkill to what we are doing.

**Comment by Towanime** [comment]
@frasmage I ended up doing what you suggested and updating the foreign keys in the migrations. Thank you.
