### ISSUE TITLE
How to get image varation with eager loading ?

### ISSUE THREAD

**Issue by shankhadevpadam** [plank/laravel-mediable#222]
I want to get an image with variation with the eager loading without assocating model.

For problem is.

I created the wordpress like filemanger system using this package and used media id for the post_thumbnail_id for posts table and i have created eager loading in Post model.

```
public function media()
{
     return $this->belongsTo('Plank\Mediable\Media', 'post_thumbnail_id');
}
```

```
$posts = Post::with('media')->get();
```
This gives all posts with media which work fine. just run 2 queries.
```
@foreach($posts as $post)
	<tr>
		<td>{{ $post->post_title }}</td>
		<td>{{ $post->post_content }}</td>
		<td>
			<img src="{{ $post->media->getUrl() }}">
		</td>
	</tr>
@endforeach
```
But when i try this, it run extra query for each thumbnail. I want eager load for this one also.
```
@foreach($posts as $post)
	<tr>
		<td>{{ $post->post_title }}</td>
		<td>{{ $post->post_content }}</td>
		<td>
			@if ($post->media->hasVariant('thumbnail'))
				<img src="{{ $post->media->findVariant('thumbnail')->getUrl() }}">
			@else
				<img src="{{ $post->media->getUrl() }}" width="100" height="100">
			@endif
		</td>
	</tr>
@endforeach
```

**Comment by frasmage** [comment]
Hi @shankhadevpadam,

This is covered in the [documentation](https://laravel-mediable.readthedocs.io/en/latest/variants.html#eager-loading).

**Comment by shankhadevpadam** [comment]
It works when using Mediable trait.

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;

class Post extends Model
{
    use Mediable;
	
    public function media()
    {
    	return $this->belongsTo('Plank\Mediable\Media', 'post_thumbnail_id');
    }
}

```
But not work if i remove media method.
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Plank\Mediable\Mediable;

class Post extends Model
{
    use Mediable;
}

```

**Comment by frasmage** [comment]
Wait, what are you doing with that custom relation? The reason it probably "doesn't work" is that you have been using the package incorrectly. You are overriding the behaviour of the package with that method. You don't need that `post_thumbnail_id` foreign key in your `posts` table. Instead of putting a media ID there, you should be assigning media using `$post->attachMedia($media, 'post_thumbnail')`, then in your view you can use `$post->getMedia('post_thumbnail')->findVariant('thumbnail')->getUrl()`

**Comment by shankhadevpadam** [comment]
Ok thanks.
