### ISSUE TITLE
Question: will further migrations only be added in major versions?

### ISSUE THREAD

**Issue by timacdonald** [plank/laravel-mediable#224]
Thanks heaps for creating and maintaining this package. It is really useful!

I had a question regarding new migrations. We are in the process of upgrading to `v5.0`. In our application, we have _all_ id's as UUID's, including those on the tables related to this package.

I've noted in your upgrading guide that migrations are now served from within the package now. 

So to my question: Will future migrations only be added in major versions?

Reason being that new migrations that reference any ID column would be a breaking change for us. Obviously this is not the intended use of the package and you might not support this, but I just wanted to check. If it is the case that migrations will be added in minor releases, I'll just make sure our team knows that we need to review each minor version before updating.

Thanks again for this great package!

**Comment by frasmage** [comment]
Yes, schema changes will always require a major version bump.

**Comment by timacdonald** [comment]
Sweet! Thanks for the info
