### ISSUE TITLE
Error with CreateImageVariants::dispatch

### ISSUE THREAD

**Issue by Jimmylet** [plank/laravel-mediable#228]
Hello,

I'm trying to get `CreateImageVariants::dispatch` to work. The classic method with `ImageManipulator` works fine.

I get an error : 

```
exception: "ErrorException"
file: "/home/vagrant/projects/myapp/myapp-api/vendor/laravel/framework/src/Illuminate/Queue/Queue.php"
line: 139
message: "serialize(): &quot;date&quot; returned as member variable from __sleep() but does not exist"
```

Here is what I do:

```
 $image = $request->file('file');
        $media = MediaUploader::fromSource($image)
            ->toDestination('s3', Auth::user()->currentTeam->slug . '/' . $user_id . '/gallery')
            ->upload();

$animal->attachMedia($media, 'gallery');
CreateImageVariants::dispatch($media, ['thumb']);
```

I've run queue: work before but it's completely ignored. What do you think this is due to? 

Thank you

**Comment by frasmage** [comment]
Hi there,

have you extended your Media model class? This error indicates that their is a property `$date` that seems to be set on serialization, but doesn't exist on unserialization. Perhaps a property that is not properly declared? There is a no `->date` symbol or property anywhere in this codebase, so I would image this is coming from your codebase.

**Comment by Jimmylet** [comment]
Thank you for your reply !

No, I use the default Media model. I looked where I could have used "date" but I can't find it. This is quite strange.
