### ISSUE TITLE
Change migration to id() or BigIncrements

### ISSUE THREAD

**Issue by Surt** [plank/laravel-mediable#229]
Hi,

It would be good to have migrations to follow the new convention of using Bigintegers for ids and foreigns or even better, to use ```id``` and ```foreignId```  (bigintegers autoincremente unsigned)

I did migrate ```change``` on my migrations some time ago, but now, with the ```AddVariantsToMedia``` migrations all is falling apart. (My fault for executing migration changes on something that is not my code)

```php
        if (!Schema::hasTable('media')) {
            Schema::create(
                'media',
                function (Blueprint $table) {
                    $table->id('id');
                    $table->string('disk', 32);
                    $table->string('directory');
                    $table->string('filename');
                    $table->string('extension', 32);
                    $table->string('mime_type', 128);
                    $table->string('aggregate_type', 32);
                    $table->integer('size')->unsigned();
                    $table->timestamps();

                    $table->unique(['disk', 'directory', 'filename', 'extension']);
                    $table->index('aggregate_type');
                }
            );
        }

        if (!Schema::hasTable('mediables')) {
            Schema::create(
                'mediables',
                function (Blueprint $table) {
                    $table->foreignId('media_id')->unsigned();
                    $table->string('mediable_type');
                    $table->integer('mediable_id')->unsigned();
                    $table->string('tag');
                    $table->integer('order')->unsigned();

                    $table->primary(['media_id', 'mediable_type', 'mediable_id', 'tag']);
                    $table->index(['mediable_id', 'mediable_type']);
                    $table->index('tag');
                    $table->index('order');
                    $table->foreign('media_id')
                        ->references('id')->on('media')
                        ->cascadeOnDelete();
                }
            );
        }
    }

```

**Comment by frasmage** [comment]
Hi there,

You definitely can run your own migrations to update columns as needed (i.e. many people use uuid). If the migrations in this package cause conflicts with your own change, you can copy the migrations out of package into your own database migrations folder, just make sure to use exactly the same filename. You can then modify it as necessary, and when you run migrations Laravel should pick up your copy first.

As for changing the defaults of this package, that might be difficult to do for legacy reasons. Something to perhaps keep in mind for the next major version, but even then that might be a painful migration.
