### ISSUE TITLE
Azure Support 

### ISSUE THREAD

**Issue by ubxtydev** [plank/laravel-mediable#230]
Looks like Azure is currently not supported .
Any chances of supporting azure any soon ?

**Comment by frasmage** [comment]
Hi @ubxtydev,

It's not currently supported out of the box, as Laravel doesn't support it by default either, but would not be too difficult to add. You need two things to work with a different storage provider: Laravel needs to recognize it as a valid storage [filesystem](https://laravel.com/docs/5.1/filesystem#custom-filesystems) , and you need to register a custom UrlGenerator with this package for the disk type.

If you find a solution that you think is useful to others, PRs are always welcome!

**Comment by ubxtydev** [comment]
Hi Thanks for the response , I was able to implement this by adding support for azure blob in Laravel Filesystem using matthewbdaly/laravel-azure-storage for Azure Support and with few simple tweaks in S3 Url generator , I created Azure Generator and the results were awesome :+1:
