### ISSUE TITLE
On Laravel 8, $media->getUrl() returning relative path instead full url!

### ISSUE THREAD

**Issue by hasnatbabur** [plank/laravel-mediable#231]
This was working fine on Laravel 6. But $media->getUrl() not working good suddenly!

I am only providing these 4 values and others are empty/commented for the AWS S3 in filesystem config:
'key' => env('AWS_ACCESS_KEY_ID'),
'secret' => env('AWS_SECRET_ACCESS_KEY'),
'bucket' => env('AWS_BUCKET'),
'region' => env('AWS_DEFAULT_REGION'),

**Comment by frasmage** [comment]
Hi there,

Laravel might have changed the way these disks are handled internally. Have you tried specifying the ['url' key](https://github.com/laravel/laravel/blob/8.x/config/filesystems.php#L51) on the disk config?

**Comment by hasnatbabur** [comment]
@frasmage Thanks a lot for your time. Giving 'url' value to 'https://{{bucket}}.s3.amazonaws.com' works like charms.
