### ISSUE TITLE
Variant Creation Error , When generating Variants for Cloud Directories 

### ISSUE THREAD

**Issue by ubxtydev** [plank/laravel-mediable#232]
When generating variant for cloud directory , it throws an error : : ExceptionIntervention\Image\Exception\NotReadableException: Unable to init from given stream , 
Probably this feature currently only supports the local files , or i am missing some configuration ?

**Comment by frasmage** [comment]
I've tested it with S3, and it works. The underlying filesystem needs to support the readStream() method, which [Azure seems to](https://github.com/thephpleague/flysystem-azure/blob/master/src/AzureAdapter.php#L190)?

A few things to try:
- make sure that your Media have an appropriate extension and mime type. That is used as part of the instantiation.
- try writing `$media->stream()` to local disk, is it still recognizable as an image?

**Comment by ubxtydev** [comment]
Thanks for the feedback : 
This is a saved media object , seems like the data is saved correctly as you suggested .
`{"size":91813,"mime_type":"image\/jpeg","extension":"jpg","aggregate_type":"image","disk":"azurefiles","directory":"mediable\/test_files","filename":"76d9c8-12-02-2020-0657","original_filename":"sFrxkMUtkhI.jpg","uuid":"fe8e0965-5513-4933-9310-8330785a4bb2","updated_at":"2020-12-02T06:57:26.000000Z","created_at":"2020-12-02T06:57:26.000000Z","id":18} `

Here is my AzureUrlGenerator 
`<?php

namespace App\Mediable;

use Plank\Mediable\UrlGenerators\BaseUrlGenerator;
use Illuminate\Contracts\Config\Repository as Config;
use Illuminate\Contracts\Filesystem\Cloud;
use Illuminate\Filesystem\FilesystemManager;

class AzureUrlGenerator extends BaseUrlGenerator
{
    /**
     * Filesystem Manager.
     * @var FilesystemManager
     */
    protected $filesystem;

    /**
     * Constructor.
     * @param \Illuminate\Contracts\Config\Repository $config
     * @param \Illuminate\Filesystem\FilesystemManager $filesystem
     */
    public function __construct(Config $config, FilesystemManager $filesystem)
    {
        parent::__construct($config);
        $this->filesystem = $filesystem;
    }

    public function getAbsolutePath(): string
    {
        return $this->getUrl();
    }

    public function getUrl(): string
    {
        /** @var Cloud $filesystem */
        $filesystem = $this->filesystem->disk($this->media->disk);
        return $filesystem->url($this->media->getDiskPath());
    }
}
`
The image format is jpg and readable 

The generated file is accessible at (Hidden Actual bucket name for privacy reasons) mycustombucket.blob.core.windows.net/files/mediable/test_files/76d9c8-12-02-2020-0657.jpg

I did some debugging in  [AzureBlobStorageAdapter.php](https://github.com/thephpleague/flysystem-azure-blob-storage/blob/fbfd44cd758fefa6d3de26a962fba5db663497c4/src/AzureBlobStorageAdapter.php#L170)

$response->getContentStream() seems to have all the needed data 

So the Adapter seems Good 

Next i went to Image Manipulator , where it calls $image = $this->imageManager->make($media->stream());
at this point we get the error Intervention\Image\Exception\NotReadableException

Looks like an issue with InterventionImage initFromStream

Updated the ImageManipulator [changed stream to getUrl()](https://github.com/ubxtydev/laravel-mediable/blob/fee903c9c892ad5b7097a78f91b180c7c689b4b6/src/ImageManipulator.php#L99)

Please check if you can update the library or add option to read from stream vs url

**Comment by frasmage** [comment]
What happens if you try instantiating with `$media->contents()` instead of `$media->getUrl()`? It seems like Imagick ultimately loads the whole file into memory then calls the same `loadFromBinary()` with the results, so we could change it to that. Not all disks are accessible over URL and a round trip to the network and back for a file on the local disk doesn't make a ton of sense either.

**Comment by ubxtydev** [comment]
$media->contents() seems to be working :+1:

**Comment by ubxtydev** [comment]
@frasmage Please update the library to use $media->contents()

**Comment by frasmage** [comment]
Yes, I will look into that this evening if I have some time. Since it seems like the whole file gets loaded into memory anyways, we can keep it simple on our end.

**Comment by frasmage** [comment]
A pull request is also welcome 😃
