### ISSUE TITLE
Variant job creation serialization error

### ISSUE THREAD

**Issue by Towanime** [plank/laravel-mediable#233]
When running the CreateImageVariants job the following exception is thrown:

`local.ERROR: serialize(): "date" returned as member variable from __sleep() but does not exist {"exception":"[object] (ErrorException(code: 0): serialize(): \"date\" returned as member variable from __sleep() but does not exist at /sites/juilliardcreativeclassroom/vendor/laravel/framework/src/Illuminate/Queue/Queue.php:147)`

I believe this happens because the job is using the incorrect serialization trait [here](https://github.com/plank/laravel-mediable/blob/master/src/Jobs/CreateImageVariants.php#L17), it should be `SerializesModels` instead.

Making a similar job with `Illuminate\Queue\SerializesModels` instead of `Carbon\Traits\Serialization` fixes the issue.

**Comment by frasmage** [comment]
🤦 Oh man, that's pretty bad. Autocompleted that a little too quickly. Fix incoming.

**Comment by frasmage** [comment]
Fixed in 5.0.4.
