### ISSUE TITLE
Conflicts in case of multiple upload context

### ISSUE THREAD

**Issue by gaetan-hexadog** [plank/laravel-mediable#237]
Hi,

due to singleton generated by MediaUploader facade I'm not able to defines different options for 2 differents uploads sets. For example I want to be able to upload a `set of images` which respects the aggrated types `['images', 'vector']` and a `set of files` which can be anything (even unrecognized types).

To do this I use the following code:
```php
foreach($images as $source) {
    $media = MediaUploader::fromSource($source)
        ->useOriginalFilename()
        ->setAllowedAggregateTypes(['image', 'vector'])
        ->upload();
}

foreach($files as $source) {
    $media = MediaUploader::fromSource($source)
        ->useOriginalFilename()
        ->setAllowUnrecognizedTypes(true)
        ->upload();
}
```

unfortunately when getting to the files `MediaUploader` checks aggregated type previously set (when uploading images).

How to manage multiple upload context without any risk of conflicts between options ?

**Comment by frasmage** [comment]
Hi @gaetan-hexadog, The MediaUploader is not bound to the container as a singleton. Every access to the `MediaUploader` facade should create a new instance to which you can apply different configurations to. Each uploader instance will load up the default settings specified in `config/mediable.php`, however, so make sure to override anything from there that does not apply to your current context.

**Comment by gaetan-hexadog** [comment]
Hi @frasmage ,

thanks for your answer (my bad it the source factory which is a singleton).

Nevertheless why, in my example, the first allowed aggregated types are still applied in the second call ?

Using the code given as example all images are well uploaded by the first MediaUploader call but a zip file is rejected due to the non allowerd archive type (onyl image, vector) by the second MediaUploader call.

The configuration used is the default one provided by the package. There is no default aggregated file types limit.

**Comment by frasmage** [comment]
What is the exact error that gets output? If you were to `dd()` that second MediaUploader just before you call the upload method, what is the output? I'm assuming changing the order of operation (i.e. handle files first, then images) makes no difference?

**Comment by gaetan-hexadog** [comment]
The error is the following:
```php
Plank\Mediable\Exceptions\MediaUpload\FileNotSupportedException
Cannot upload file of aggregate type `archive`. Only files of type(s) `image`, `vector` are permitted. 
```


MediaUploader dump for images
```php
Plank\Mediable\MediaUploader {#1803 ▼
  -filesystem: Illuminate\Filesystem\FilesystemManager {#1744 ▶}
  -factory: Plank\Mediable\SourceAdapters\SourceAdapterFactory {#1932 ▶}
  -config: array:16 [▼
    "model" => "Plank\Mediable\Media"
    "mediables_table" => "mediables"
    "default_disk" => "uploads"
    "allowed_disks" => array:2 [▶]
    "max_size" => 10485760
    "on_duplicate" => "increment"
    "strict_type_checking" => false
    "allow_unrecognized_types" => false
    "allowed_mime_types" => []
    "allowed_extensions" => []
    "allowed_aggregate_types" => array:2 [▼
      0 => "image"
      1 => "vector"
    ]
    "aggregate_types" => array:9 [▶]
    "source_adapters" => array:2 [▶]
    "url_generators" => array:2 [▶]
    "rehydrate_media" => true
    "detach_on_soft_delete" => false
  ]
  -source: Plank\Mediable\SourceAdapters\StreamResourceAdapter {#1995 ▶}
  -disk: null
  -directory: "products/16"
  -filename: null
  -hashFilename: false
  -visibility: "public"
  -before_save: null
}
```


MediaUploader dump for files (.zip in my test)
```php
Plank\Mediable\MediaUploader {#1803 ▼
  -filesystem: Illuminate\Filesystem\FilesystemManager {#1744 ▶}
  -factory: Plank\Mediable\SourceAdapters\SourceAdapterFactory {#1932 ▶}
  -config: array:16 [▼
    "model" => "Plank\Mediable\Media"
    "mediables_table" => "mediables"
    "default_disk" => "uploads"
    "allowed_disks" => array:2 [▶]
    "max_size" => 10485760
    "on_duplicate" => "increment"
    "strict_type_checking" => false
    "allow_unrecognized_types" => true
    "allowed_mime_types" => []
    "allowed_extensions" => []
    "allowed_aggregate_types" => array:2 [▼
      0 => "image"
      1 => "vector"
    ]
    "aggregate_types" => array:9 [▶]
    "source_adapters" => array:2 [▶]
    "url_generators" => array:2 [▶]
    "rehydrate_media" => true
    "detach_on_soft_delete" => false
  ]
  -source: Plank\Mediable\SourceAdapters\StreamResourceAdapter {#2066 ▶}
  -disk: null
  -directory: "products/16"
  -filename: null
  -hashFilename: false
  -visibility: "public"
  -before_save: null
}
```

As you can see config still have aggregated types set by the previous instanciation (but has the new config flags : allow unrecognized types set to true only in second operation in my example).


If I change the order of operation it works (in this specific use case): because aggregated types limit is not set by the files uploader, only by the one handling images. But doing this the flag "allowUnrecognizedTypes" is set to true also for images.

I guess there is a bug because config seems to be shared between calls. And the new instance should not have any configuration data from a previous instance. Right ? Otherwise anytime we use MediaUplaoder we should reset all config flag manually.

In addition is there a way to reallow any aggregated type ?

**Comment by frasmage** [comment]
Ok, I found the problem. The container is config is not singleton, however Laravel Facades retain an instance. In the short term, you can instantiate the uploader from the container instead with `app(MediaUploader::class)`. I will work on overriding the behaviour of the Facade tonight

**Comment by gaetan-hexadog** [comment]
Thanks a lot.
It's working with `app(MediaUploader::class)` workaround. I'll try the fix you published very soon.
