### ISSUE TITLE
File Visibility Issue , All files are public

### ISSUE THREAD

**Issue by ravdeepsingh22** [plank/laravel-mediable#239]
Have set the visibility as    'visibility' => 'private' in filesystem.php , But the uploaded file is always Public

**Comment by frasmage** [comment]
can you provide the entire disk config that you are using and a stat of the file?

From your other question, I'm assuming you are using the 'public' disk. For local filesystem, file visibility is equivalent to the unix permission level of the file (see [Laravel docs](https://laravel.com/docs/8.x/filesystem#local-files-and-visibility)). However, if you are using a disk within the webroot, it is still being read by the apache/nginx user when accessed via URL so will still be returned. 

For disks not in the webroot, you could apply your own logic to determine which files to expose from a controller ([relevant docs](https://laravel-mediable.readthedocs.io/en/latest/media.html#urls-and-downloads)).

**Comment by ravdeepsingh22** [comment]
I am referring to S3 storage here 

` 's3dream' => [
            'driver' => 's3',
            'key' => env('AWS_ACCESS_KEY_ID_D', ""),
            'secret' => env('AWS_SECRET_ACCESS_KEY_D', ""),
            'region' => env('AWS_DEFAULT_REGION_D', "us-east-1"),
            'bucket' => env('AWS_BUCKET_D', 'mybucket'),
            'url' => 'https://mybucket.objects-us-east-1.dream.io',
            'endpoint' => 'https://objects-us-east-1.dream.io',
            'visibility' => 'private',
        ],`

**Comment by frasmage** [comment]
For cloud disks, you should double check the permissions of the bucket itself in AWS (or dreamhost?). You might have the bucket set to have all files be publicly accessible.

**Comment by ravdeepsingh22** [comment]
Using Dreamhost : DreamObjects Double checked the Bucket is private + Object permissions default to private in DreamObjects

**Comment by frasmage** [comment]
Can you clarify what you mean by the objects being public? Is the object accessible via URL? Does `$media->isVisible()` return true? Does `$media->getUrl()` return a URL when you don't expect it to?

**Comment by ravdeepsingh22** [comment]
Is the object directly accessible via URL? Yes
 Does $media->isVisible() return true? Yes

Does $media->getUrl() return a URL when you don't expect it to? It returns the correct url , but that url is supposed to be private

**Comment by frasmage** [comment]
ok, I see the issue. The uploader is defaulting to public. Use `makePrivate()` for now, I will adjust the behaviour when I get a chance

**Comment by ravdeepsingh22** [comment]
Looks like this messed up the Variant Generation .
The uploaded image is public , but the generated variants are now Private
