### ISSUE TITLE
Temporary URLs are not supported for files on disk 'public'

### ISSUE THREAD

**Issue by ravdeepsingh22** [plank/laravel-mediable#240]
We should probably add the support for temporary signed Routes for public disk files as well

**Comment by frasmage** [comment]
Hi @ravdeepsingh22,

I assume by the 'public' disk you mean the local filesystem? This functionality is based on the Flysystem library which does not support that temporary URLs for local files either. 

By definition, there is no need to generate temporary URLs for a disk that is in the webroot such as the 'public' disk, those are always accessible. You theoretically create your own URL signing mechanism and controller that streams the contents of the file only if the signature is valid for a a file on a local filesystem disk that is outside of the webroot.

**Comment by ravdeepsingh22** [comment]
Thanks for the feedback
