### ISSUE TITLE
Plank\Mediable\Jobs\CreateImageVariants :  Integrity constraint violation

### ISSUE THREAD

**Issue by ravdeepsingh22** [plank/laravel-mediable#241]
PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'azurefiles-mediable/checklist_images-7f6bc3-12-10-2020-1944-medi' for key 'media_disk_directory_filename_extension_unique' in /var/www/html/abc/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115

The variant is getting generated and the data in media table is fine , However there are a lots of entries of similar error in Horizon

**Comment by frasmage** [comment]
I will need more information than that. What are the fields of the original Media file? What are the configurations of the ImageManipulation for this variant? Are you able to provide a full stack trace.

Numerous similar entries for an async job implies that you might have a failing job that is continuously being retried (a.k.a. spinning).

**Comment by ravdeepsingh22** [comment]
Image Variants 
`  ImageManipulator::defineVariant(
            'mediumvariant',
            ImageManipulation::make(function (Image $image) {
                $image->resize(256, null, function ($constraint) {
                    $constraint->aspectRatio();
                });
            })
        );
        ImageManipulator::defineVariant(
            'largevariant',
            ImageManipulation::make(function (Image $image) {
                $image->resize(512, null, function ($constraint) {
                    $constraint->aspectRatio();
                });
            })
        );`
Job Data 
`
{
variantNames: [
"mediumvariant",
"largevariant"
],
models: {
class: "Plank\Mediable\Media",
id: [
2219
],
relations: [
],
connection: "mysql"
},
forceRecreate: false,
job: null,
connection: null,
queue: null,
chainConnection: null,
chainQueue: null,
chainCatchCallbacks: null,
delay: null,
middleware: [
],
chained: [
]
} `


Stack Trace 
`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'azurefiles-mediable/uploaded_images-63101b-12-13-2020-1535-med' for key 'media_disk_directory_filename_extension_unique' in /var/www/html/mywebsite.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:115
Stack trace:
#0 /var/www/html/mywebsite.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(115): PDOStatement->execute()
#1 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(471): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(638): Illuminate\Database\Connection->runQueryCallback()
#4 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(472): Illuminate\Database\Connection->run()
#5 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(424): Illuminate\Database\Connection->statement()
#6 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#7 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2872): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#8 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1508): Illuminate\Database\Query\Builder->insertGetId()
#9 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1051): Illuminate\Database\Eloquent\Builder->__call()
#10 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1016): Illuminate\Database\Eloquent\Model->insertAndSetId()
#11 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(857): Illuminate\Database\Eloquent\Model->performInsert()
#12 /var/www/html/mywebsite.com/vendor/plank/laravel-mediable/src/ImageManipulator.php(140): Illuminate\Database\Eloquent\Model->save()
#13 /var/www/html/mywebsite.com/vendor/plank/laravel-mediable/src/Jobs/CreateImageVariants.php(57): Plank\Mediable\ImageManipulator->createImageVariant()
#14 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Plank\Mediable\Jobs\CreateImageVariants->handle()
#15 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#17 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#18 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#19 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#20 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#21 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#23 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(96): Illuminate\Bus\Dispatcher->dispatchNow()
#24 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#25 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(98): Illuminate\Pipeline\Pipeline->then()
#27 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(67): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#28 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#29 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\Queue\Jobs\Job->fire()
#30 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker->process()
#31 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->runJob()
#32 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\Queue\Worker->daemon()
#33 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Console\WorkCommand->runWorker()
#34 /var/www/html/mywebsite.com/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\Queue\Console\WorkCommand->handle()
#35 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#36 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#37 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#38 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#39 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#40 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#41 /var/www/html/mywebsite.com/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#42 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#43 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#44 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#45 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#46 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#47 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#48 /var/www/html/mywebsite.com/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#49 {main}
Next Doctrine\DBAL\Driver\PDO\Exception: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'azurefiles-mediable/uploaded_images-63101b-12-13-2020-1535-med' for key 'media_disk_directory_filename_extension_unique' in /var/www/html/mywebsite.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDO/Exception.php:18
Stack trace:
#0 /var/www/html/mywebsite.com/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php(117): Doctrine\DBAL\Driver\PDO\Exception::new()
#1 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(471): Doctrine\DBAL\Driver\PDOStatement->execute()
#2 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(671): Illuminate\Database\Connection->Illuminate\Database\{closure}()
#3 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(638): Illuminate\Database\Connection->runQueryCallback()
#4 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(472): Illuminate\Database\Connection->run()
#5 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(424): Illuminate\Database\Connection->statement()
#6 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#7 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2872): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#8 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1508): Illuminate\Database\Query\Builder->insertGetId()
#9 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1051): Illuminate\Database\Eloquent\Builder->__call()
#10 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1016): Illuminate\Database\Eloquent\Model->insertAndSetId()
#11 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(857): Illuminate\Database\Eloquent\Model->performInsert()
#12 /var/www/html/mywebsite.com/vendor/plank/laravel-mediable/src/ImageManipulator.php(140): Illuminate\Database\Eloquent\Model->save()
#13 /var/www/html/mywebsite.com/vendor/plank/laravel-mediable/src/Jobs/CreateImageVariants.php(57): Plank\Mediable\ImageManipulator->createImageVariant()
#14 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Plank\Mediable\Jobs\CreateImageVariants->handle()
#15 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#16 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#17 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#18 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#19 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#20 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#21 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#22 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#23 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(96): Illuminate\Bus\Dispatcher->dispatchNow()
#24 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#25 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#26 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(98): Illuminate\Pipeline\Pipeline->then()
#27 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(67): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#28 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#29 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\Queue\Jobs\Job->fire()
#30 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker->process()
#31 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->runJob()
#32 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\Queue\Worker->daemon()
#33 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Console\WorkCommand->runWorker()
#34 /var/www/html/mywebsite.com/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\Queue\Console\WorkCommand->handle()
#35 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#36 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#37 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#38 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#39 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#40 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#41 /var/www/html/mywebsite.com/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#42 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#43 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#44 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#45 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#46 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#47 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#48 /var/www/html/mywebsite.com/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#49 {main}
Next Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'azurefiles-mediable/uploaded_images-63101b-12-13-2020-1535-med' for key 'media_disk_directory_filename_extension_unique' (SQL: insert into `media` (`variant_name`, `original_media_id`, `disk`, `directory`, `filename`, `extension`, `mime_type`, `aggregate_type`, `size`, `updated_at`, `created_at`) values (mediumvariant, 2219, azurefiles, mediable/uploaded_images, 63101b-12-13-2020-1535-mediumvariant, jpg, image/jpeg, image, 15868, 2020-12-13 15:35:08, 2020-12-13 15:35:08)) in /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678
Stack trace:
#0 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(638): Illuminate\Database\Connection->runQueryCallback()
#1 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(472): Illuminate\Database\Connection->run()
#2 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php(424): Illuminate\Database\Connection->statement()
#3 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Query/Processors/Processor.php(32): Illuminate\Database\Connection->insert()
#4 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(2872): Illuminate\Database\Query\Processors\Processor->processInsertGetId()
#5 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php(1508): Illuminate\Database\Query\Builder->insertGetId()
#6 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1051): Illuminate\Database\Eloquent\Builder->__call()
#7 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(1016): Illuminate\Database\Eloquent\Model->insertAndSetId()
#8 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php(857): Illuminate\Database\Eloquent\Model->performInsert()
#9 /var/www/html/mywebsite.com/vendor/plank/laravel-mediable/src/ImageManipulator.php(140): Illuminate\Database\Eloquent\Model->save()
#10 /var/www/html/mywebsite.com/vendor/plank/laravel-mediable/src/Jobs/CreateImageVariants.php(57): Plank\Mediable\ImageManipulator->createImageVariant()
#11 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Plank\Mediable\Jobs\CreateImageVariants->handle()
#12 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#13 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#14 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#15 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#16 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(128): Illuminate\Container\Container->call()
#17 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Bus\Dispatcher->Illuminate\Bus\{closure}()
#18 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#19 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(132): Illuminate\Pipeline\Pipeline->then()
#20 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(96): Illuminate\Bus\Dispatcher->dispatchNow()
#21 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\Queue\CallQueuedHandler->Illuminate\Queue\{closure}()
#22 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(103): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#23 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(98): Illuminate\Pipeline\Pipeline->then()
#24 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(67): Illuminate\Queue\CallQueuedHandler->dispatchThroughMiddleware()
#25 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(98): Illuminate\Queue\CallQueuedHandler->call()
#26 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(406): Illuminate\Queue\Jobs\Job->fire()
#27 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(356): Illuminate\Queue\Worker->process()
#28 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\Queue\Worker->runJob()
#29 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(116): Illuminate\Queue\Worker->daemon()
#30 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(100): Illuminate\Queue\Console\WorkCommand->runWorker()
#31 /var/www/html/mywebsite.com/vendor/laravel/horizon/src/Console/WorkCommand.php(50): Illuminate\Queue\Console\WorkCommand->handle()
#32 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\Horizon\Console\WorkCommand->handle()
#33 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#34 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\Container\Util::unwrapIfClosure()
#35 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\Container\BoundMethod::callBoundMethod()
#36 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(610): Illuminate\Container\BoundMethod::call()
#37 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\Container\Container->call()
#38 /var/www/html/mywebsite.com/vendor/symfony/console/Command/Command.php(255): Illuminate\Console\Command->execute()
#39 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\Component\Console\Command\Command->run()
#40 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(971): Illuminate\Console\Command->run()
#41 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(290): Symfony\Component\Console\Application->doRunCommand()
#42 /var/www/html/mywebsite.com/vendor/symfony/console/Application.php(166): Symfony\Component\Console\Application->doRun()
#43 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\Component\Console\Application->run()
#44 /var/www/html/mywebsite.com/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\Console\Application->run()
#45 /var/www/html/mywebsite.com/artisan(37): Illuminate\Foundation\Console\Kernel->handle()
#46 {main}`

**Comment by frasmage** [comment]
Just missing the fields of Media#2219, can you output the values as they are in the database? Can you also double check for any existing variants of that entity at the same time, e.g. `where media.orginal_media_id = 2219`? Chances are you already have an entry for one or both of those variant names

**Comment by ubxtyrav** [comment]
@frasmage so i figured out the exact case for this error , 
I am trying to reupload same image 
`$media = $query
        ->toDestination($disk, $path)
        ->onDuplicateReplace()
        ->useFilename($name)
        ->upload();
`
This works fine for the original image , but gives an error while generating variants for duplicate image ,

`  CreateImageVariants::dispatch($media, ['appsmallvariant', 'appmediumvariant', 'applargevariant'], true);
   `
Have passed `true` for force recreate but looks like it is giving an error if an entry for variant already exists 

`PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'S3new_3-mediable-C3FBCB04-AF83-4722-A215-23ECB66D6F1F-appmediumv' for key 'media_disk_directory_filename_extension_unique' in /var/www/html`

**Comment by frasmage** [comment]
Thanks for helping pin it down. It seems there is a bug with the replace behaviour. It should probably delete the variants of the original file. I'll work on a fix when I find some time.

**Comment by ravdeepsingh22** [comment]
@frasmage Any ETA on the same please

**Comment by frasmage** [comment]
Hi there, sorry for the delay.

implemented a solution with #249 and release in 5.1.0. In order to avoid backwards compatibility issues, I've created a new duplicate mode instead of modifying the existing one.
