### ISSUE TITLE
Fake Png as SVG mimeType

### ISSUE THREAD

**Issue by Fed0t** [plank/laravel-mediable#246]
Hello,

I have problems with  detection of mimeType.

I try to upload a svg file with name 'xssimage.svg.png'

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<svg
onload="alert('XSS')"
xmlns="http://www.w3.org/2000/svg">
<polygon id="triangle" points="0,0 0,50 50,0" fill="#009900"
stroke="#004400"/>
</svg>
`

The problem on detecting the mimeType are on the plank/laravel-mediable
```
$media = MediaUploader::fromSource($request->file('image'))
            ->beforeSave(function (Media $model, SourceAdapterInterface $source) use ($doAsset){
                $mediaSource = $source->getSource();
                dd($source->mimeType(), $source->extension(), $mediaSource->clientExtension(), $mediaSource);

                $model->setAttribute('size', $source->size());
                $model->setAttribute('mime_type', $source->mimeType());
                $model->setAttribute('extension', $source->extension());
                $model->setAttribute('aggregate_type', $mediaSource->clientExtension());
                $model->setAttribute('upload_original_id', 'do');
                $model->setAttribute('filename', $doAsset);
            })->upload();
```
The dump of  
`dd($source->mimeType(), $source->extension(), $mediaSource->clientExtension(), $mediaSource);`
returns "image/png", "png", "png" but when I use the function of Laravel:
` dd($request->file('image')->getMimeType());`
The output is:
`"image/svg+xml"`

**Comment by frasmage** [comment]
closing as duplicate
