### ISSUE TITLE
Fake Png as SVG mimeType

### ISSUE THREAD

**Issue by Fed0t** [plank/laravel-mediable#247]
Hello,

I have problems with  detection of mimeType.

I try to upload a svg file with name 'xssimage.svg.png'

`<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<svg
onload="alert('XSS')"
xmlns="http://www.w3.org/2000/svg">
<polygon id="triangle" points="0,0 0,50 50,0" fill="#009900"
stroke="#004400"/>
</svg>
`

The problem on detecting the mimeType are on the plank/laravel-mediable
```
$attributes = $this->validate(
            $request,
            [
                'image' => 'required',
            ]
        );

$media = MediaUploader::fromSource($request->file('image'))
            ->beforeSave(function (Media $model, SourceAdapterInterface $source) use ($doAsset){
                $mediaSource = $source->getSource();
                
                dd($source->mimeType(), $source->extension(), $mediaSource->clientExtension(), $mediaSource);

                $model->setAttribute('size', $source->size());
                $model->setAttribute('mime_type', $source->mimeType());
                $model->setAttribute('extension', $source->extension());
                $model->setAttribute('aggregate_type', $mediaSource->clientExtension());
                $model->setAttribute('upload_original_id', 'do');
                $model->setAttribute('filename', $doAsset);
            })->upload();
```
The dump of 

`dd($source->mimeType(), $source->extension(), $mediaSource->clientExtension(), $mediaSource);` gives me "image/png", "png", "png" 

and when I use the function of Laravel:
` dd($request->file('image')->getMimeType());`
The output is:
`"image/svg+xml"`

So the laravel detects the file as real svg but plank not.How I should proceed.

Thanks!

**Comment by Fed0t** [comment]
I commented in mediable.php config the source adapter and this works fine right now with the laravel UploadedFile class.


` 'class' => [
//            Symfony\Component\HttpFoundation\File\UploadedFile::class => Plank\Mediable\SourceAdapters\UploadedFileAdapter::class,
            Symfony\Component\HttpFoundation\File\File::class => Plank\Mediable\SourceAdapters\FileAdapter::class,
            Psr\Http\Message\StreamInterface::class => Plank\Mediable\SourceAdapters\StreamAdapter::class,
        ],`

**Comment by frasmage** [comment]
Hi there,

Why do you have an SVGs with the wrong file extension? What is the use case of that? I can warn you that mismatched extensions and mime types could result in incorrect aggregate types.

So the `UploadedFileAdapter` calls the `getClientMimeType()` method on the uploaded file, which reads what was identified in the $FILES superglobal by apache/PHP.

By commenting that adapter out, the `FileAdapter` is picking up your uploaded files instead. This adapter and your example are calling `getMimeType()` which invokes the mime type guesser. This parses over the entire file contents to infer the type, so it is more accurate, but more time consuming, especially with very large files. The `FileAdapter` is designed for files originating from the local file system, where we don't have an alternative.  If this suits your use case, then go for it!

**Comment by M-Abdullahi** [comment]
Hey @Fed0t  Please close the issue if your problem was solved or provide feedback and how you can be assisted further
