### ISSUE TITLE
MediaUploader onDuplicateUpdate

### ISSUE THREAD

**Issue by szonov** [plank/laravel-mediable#248]
During developing often doing ```artisan migrate:fresh --seed```
and got situation when file exists in filesystem, but not recorded in media table.

I'm using ```MediaUploader::fromSource($imageSource)->...->onDuplicateUpdate()```;
and after refreshing database this uploading is not working, since:
1) file already exists
2) record does not exists
3) handleDuplicate in case  ON_DUPLICATE_UPDATE set $model->id = null (since no record in db)
4) handleDuplicate in case  ON_DUPLICATE_UPDATE set $model->exists = true;

as result $model->save() is not saved data to database.

for now as workaround I've set observer \Plank\Mediable\Media::observe(MediaObserver::class);
and in MediaObserver
```
public function saving(Media $media)
{
    if ($media->exists && !$media->id) {
        $media->exists = false;
    }
}
```
But I suppose that is more correct to fix it in  MediaUploader, 
instead of: ```$model->exists = true;``` it should be something like ```$model->exists = (bool)$model->{$model->getKeyName()}```

**Comment by frasmage** [comment]
Hi @szonov, 

Good catch! Fixed in 5.1.0
