### ISSUE TITLE
Migration files not being published

### ISSUE THREAD

**Issue by mojoblanco** [plank/laravel-mediable#253]
When I run the command for publishing vendor files, it only publishes the config file and not the migration file.

![image](https://user-images.githubusercontent.com/4370375/119803561-7aa7de80-bed7-11eb-99c4-5f75bf5f9d5c.png)

**Comment by frasmage** [comment]
Hi there,

The codebase no longer copies the migration files into your application directory automatically. Instead, it registers its own migration directory (vendor/plank/laravel-mediable/migrations) from the service provider.

If you need to override a migration file (e.g. change the column types), you can manually copy them into your application's migration directory. If you ensure that the file names are identical, then yours will take precedence.

I see that I forgot to update the readme to remove the indication that it should be copying the migration files, I'll fix that.

**Comment by mojoblanco** [comment]
Thanks for the clarification. 👍
