### ISSUE TITLE
Who change order mediable?

### ISSUE THREAD

**Issue by edmarr2** [plank/laravel-mediable#254]
Hi, I need to order the mediable, but I can't follow the documentation
 https://laravel-mediable.readthedocs.io/en/latest/mediable.html#media-order

**Comment by frasmage** [comment]
Hi @edmarr2, you will need to provide a more detailed description of what you are trying to do in order for me to help you.

**Comment by edmarr2** [comment]
i need change order of files in this collection, in front i change order but in backend i don't know who make if update or use prepand with syncMedia

**Comment by frasmage** [comment]
If you have a collection of media attached to a given tag, you can use syncMedia to change the order. For example: 

```
// if you have the following, which currently returns collection([Media#1, Media#2, Media#3])
$results = $user->getMedia('avatars');

// you can change the order by doing something like this:
$user->syncMedia([$results[2], $results[0], $results[1]], 'avatars');
// or
$user->syncMedia([$media3, $media1, $newMediaToAdd, $media2], 'avatars');
//etc.
```

**Comment by edmarr2** [comment]
ahh, thanks @frasmage
