### ISSUE TITLE
[QUESTION] How to pass options for MediaMover's methods?

### ISSUE THREAD

**Issue by siarheipashkevich** [plank/laravel-mediable#256]
Hi all,

Could you please assist how can I pass `options` due calling methods from `MediaMover`?

I need pass cache headers options when call `moveToDisk` method.

Thanks.

**Comment by frasmage** [comment]
Hi @siarheipashkevich,

I just put up a PR which adds an extra parameter for doing so. Could you please test that it works for your use case? Thanks

**Comment by siarheipashkevich** [comment]
Hi @frasmage thanks a lot. I'll check in the evening (Europe\Minsk timezone)

**Comment by siarheipashkevich** [comment]
@frasmage it is working.

Please merge PR. Thanks.

![Screenshot from 2021-09-07 21-18-23](https://user-images.githubusercontent.com/7753600/132392365-e94edebd-1eb4-482e-8e29-74d152ff805c.png)
