### ISSUE TITLE
Undefined Type with MediaUploader Facade?

### ISSUE THREAD

**Issue by JaredCostall** [plank/laravel-mediable#258]
I'm getting `undefined type` from intelephense in VSCode whenever I use the `MediaUploader` facade.

For example...

```
use MediaUploader;

MediaUploader::fromSource($file)
                    ->useFilename($name)
                    ->upload();
```

Does anyone know of a fix?

**Comment by frasmage** [comment]
I'm guessing it doesn't like this declaration?

https://github.com/plank/laravel-mediable/blob/master/src/Facades/MediaUploader.php#L13

My IDE has never had a problem with it, but feel free to open a PR removing the "mixed" statement.

**Comment by JaredCostall** [comment]
@frasmage thanks for your reply, also getting other intelephense errors such as:

>Non static method `defineVariant` should not be called statically.

Seems like issues whenever I'm using a facade. If anyone knows of a general fix?
