### ISSUE TITLE
Convert original uploaded files format?

### ISSUE THREAD

**Issue by JaredCostall** [plank/laravel-mediable#259]
I understand you can force variants to be a particular format by using `->outputJpegFormat()`.

Is there a way to convert original uploaded files to a particular format, e.g. user uploads a `gif` and the original is saved as a `jpg`.

I want to allow gifs to be uploaded, so it's not a validation issue.

**Comment by frasmage** [comment]
By default the original is always retained unmodified to be used as a basis for other images.  You can attach the original or variants directly to a model if you choose.

If you really want to get rid of the original model, you can call `makeOriginal()` which will detach it, you can then remove the initially created model

**Comment by JaredCostall** [comment]
@frasmage thank you for the information.
