### ISSUE TITLE
Update Eager Loading Documentation

### ISSUE THREAD

**Issue by JaredCostall** [plank/laravel-mediable#260]
The [Lazy Eager Loading docs](https://laravel-mediable.readthedocs.io/en/latest/mediable.html#lazy-eager-loading) state: 

>Variants can also be eager loaded this way.

```
<?php
// lazy eager load from a collection of Mediables
$posts->loadMediaAndVariants($tags);
$posts->loadMediaAndVariantsMatchAll($tags);

// lazy eager load from a single Mediable model
$post->loadMediaAndVariants($tags);
$post->loadMediaAndVariantsMatchAll($tags);
```

Yet the methods are actually called `loadMediaWithVariants()` and `loadMediaWithVariantsMatchAll()`. Note the `with` instead of `and`.

Perhaps the docs should be updated?

**Comment by frasmage** [comment]
Fixed, thanks for pointing that out!
