### ISSUE TITLE
How to install on the lumen?

### ISSUE THREAD

**Issue by va1hi9da9sh2ou0rz2ad1eh7** [plank/laravel-mediable#264]
I need to install on the lumen.

**Comment by frasmage** [comment]
This package depends on a number of components from the full Laravel framework which are not included with Lumen by default (Eloquent, Filesystem, etc.), so I generally assume it isn't likely to be used with Lumen.

As with any other Lumen extension, you would need to install the package through composer and then register the service provider

```php
$app->register(\Plank\Mediable\MediableServiceProvider::class);
```

Beyond that you will need to make sure to set up your database with the tables provided in the migration files of this package.
