### ISSUE TITLE
Uppercase extension is failing on aggregate types with strict type checking

### ISSUE THREAD

**Issue by sstraakenbroek** [plank/laravel-mediable#265]
When you are configuring to only allow the aggregate type of TYPE_PDF with `strict_type_checking` set to `true`. Then it's failing when you upload a file with uppercase extension. For example; dummy.PDF is failing but dummy.pdf is working fine.

```
'aggregate_types' => [
        Plank\Mediable\Media::TYPE_PDF => [
            'mime_types' => [
                'application/pdf',
            ],
            'extensions' => [
                'pdf',
            ],
        ],
    ],
```

The error you are getting is:

Plank\Mediable\Exceptions\MediaUpload\FileNotSupportedException
File with mime of `application/pdf` not recognized for extension `PDF`.

When you change the aggregate_types with uppercase extension, then it's working. But that isn't what you want to have.

```
'aggregate_types' => [
        Plank\Mediable\Media::TYPE_PDF => [
            'mime_types' => [
                'application/pdf',
            ],
            'extensions' => [
                'pdf',
                'PDF',
            ],
        ],
    ],
```

When you only use the `allowed_extensions`, then it's also working with only the 'pdf' in lowercase defined. 

```
'allowed_extensions' => [
    'pdf',
],
```

**Comment by zimsa** [comment]
The added line

`$extension = strtolower($extension)`

in method `verifyExtension` of class `MediaUploader` changes the extension from uppercase to lowercase.

We are using `MediaUploader::importPath($disk, $path)` for importing files from the local filesystem. The method doesn't work anymore if a files extension is written in capitals. The extension is converted to lowercase before the existence of the path is verified:

```
public function import(string $disk, string $directory, string $filename, string $extension): Media
{

  /* ... */

  $model->extension = $this->verifyExtension($extension);

  if (!$storage->has($model->getDiskPath())) {
      throw FileNotFoundException::fileNotFound($model->getDiskPath());
  }

  /* ... */
}
```
