### ISSUE TITLE
Q: Query Media by ID

### ISSUE THREAD

**Issue by cbka** [plank/laravel-mediable#267]
Hi and thanks for the package... 

maybe i am just lost in the trees but... 

`$media = Media::find($id); `

returns null even if the id exists... what am i missing ? 

Point is i need to get a media model by its ID and not by the relation... 

```
public function deleteMedia(Media $media) {
        dd($media); ->>returns null


        $media->delete();
        return redirect()->back();
    }
```

Thanks in advance , 

Cheers, 
Chris

**Comment by frasmage** [comment]
Hi there,

Media is an eloquent model like any other with a primary key that will work with `find()`.

I take it this deleteMedia method is a controller method? What does your route definition look like? How have you set up route paramaters and/or model bindings? What values are you passing into the URL?

**Comment by cbka** [comment]
Hi and thanks for the response ,

You are totally right, this is for a controller.

I tried several thing like hard coding the id in find 

$media = Media::find('3');
dd($media)---> returns null


Route looks sth like 

Route::post('/schulen/deleteMedia', [SchulenController::class, 'deleteMedia'])->name('schulen.deleteMedia');

In the form only the slug 'id' gets sent in post

The controller function looks sth like 



    public function deleteMedia(Request $request) {

        $media = Media::find($request->media_id);

        $media->delete();
        return redirect()->back();

}

**Comment by frasmage** [comment]
Well there's you problem. You don't have any `{id}` parameter in your route. I imagine you aren't getting `null`, but a 404 as the route doesn't know what to do with your URI.

**Comment by cbka** [comment]
Ah I see, thank you very much !
