### ISSUE TITLE
Deleting Media will not delete variants in DB and filesystem

### ISSUE THREAD

**Issue by cedricchavaudra** [plank/laravel-mediable#269]
Hello,

First of all, congratulations on your package, it is really very complete and very practical! 
In my application, at the update controller level I have the following code: 

```php
// Delete main media if already exists (for update without duplicate in DB and filesystem)
if ($ingredient->hasMedia(['main'])) {
    $ingredient->firstMedia(['main'])->delete();
}

// Upload media
$media = MediaUploader::fromSource($request->file('icon'))
    ->toDisk('public')
    ->toDirectory('ingredients')
    ->useHashForFilename()
    ->upload();

// Creating variants
CreateImageVariants::dispatch($media, ['icon', 'thumbnail'], true);

// Sync media
$ingredient->syncMedia($media, ['main']);
```

I would like to know if it is possible to just overwrite the old media (media entries in the database and files on the filesystem) during the update (from the second call) 

I tried setting "on_duplicate" to "ON_DUPLICATE_REPLACE_WITH_VARIANTS" but it doesn't seem to work. I'm guessing because I'm using the "useHashForFilename ()" method

For the moment the only solution (half functional) is to call
`` php
if ($ ingredient-> hasMedia (['main'])) {
             $ ingredient-> firstMedia (['main']) -> delete ();
         }
`` ``

before executing the rest of the code, it is not very elegant, and in addition it does not remove the variants of the media.

Do you have a solution? thank you.

**Comment by frasmage** [comment]
Hi there,

First of all, thank you for the compliment, I'm glad you like the package! 😄  

If I understand correctly, you are trying to replace the media that were uploaded to the model with a different file? If that is the case, this isn't what OnDuplicate behaviours are for. Those are instructions for how to handle file name collisions on disk (e.g. file uploaded with matching file name), which isn't going to happen . 

 This type of replace operation has a lot of potential variations in desired behaviour (e.g. retain originals, handling of other models attached to the media), so the package doesn't prescribe a single workflow. All of the pieces for what you need are there, just a matter of putting them together to suit your use case.

Most of what you wrote is sensible. I think all you are missing is deleting the original variants. You can achieve that by replacing your delete line with something like this. Side note, you might want to delete the original after you have uploaded the new one and generated its variants (the time consuming portion), so you minimize the race condition with some other request wants to load that image.

```php

// upload, generate variants 

if ($ingredient->hasMedia(['main'])) {
    $ingredient->firstMedia(['main'])->getAllVariantsAndSelf()->each(function(Media $variant) {
         $variant->delete()
    });
}
$ingredient->syncMedia($media, ['main']);
```
