### ISSUE TITLE
Q: is it possible to get model attached to media?

### ISSUE THREAD

**Issue by wilychris** [plank/laravel-mediable#280]
Hi @frasmage 
Is there a way to get the current model that has been attached to a media?
I think i need a way to get the value of column 'mediable_type' from table 'mediable'.

**Comment by frasmage** [comment]
If you know the class of the mediable model can use the following to fetch all models of that type attached to the media

```php
$media->models(MyModel::class)->get()
```

Otherwise, if you are trying to figure out the class, you might need to query the DB yourself, something like

```sql
SELECT mediable_type, mediable_id FROM mediable WHERE media_id = ?
```

**Comment by wilychris** [comment]
The later is my case, so i'll go with your second solution,
Thank you Sean for your time and thanks to everyone who has contributed to the library.
