### ISSUE TITLE
getTemporaryUrl Not working Laravel 9

### ISSUE THREAD

**Issue by sgtcoder** [plank/laravel-mediable#281]
With Flysytem 3 and Laravel 9 I am getting a Call to undefined method League\Flysystem\Filesystem::getAdapter() when using `$media->getTemporaryUrl();`

**Comment by frasmage** [comment]
hmm, seems like it is no longer possible to access the underlying Aws\S3\S3Client instance in Flysystem V2, though it looks like there is an alternative method available for doing this.

Could you help validate that #282 solves the issue for you?

**Comment by sgtcoder** [comment]
Confirmed using this works: `"plank/laravel-mediable": "dev-laravel-9-temporary-url as 5"`

**Comment by Krato** [comment]
Yes please. Can you release it? Thanks!
