### ISSUE TITLE
Mediauploader error: Using $this when not in object context

### ISSUE THREAD

**Issue by faridsa** [plank/laravel-mediable#283]
After a composer update in my project, plank/laravel-mediable installs v. 5.4.1 and any form with file upload fires that error

> Error
> Using $this when not in object context
> 
> Plank\Mediable\MediaUploader::fromSource
> vendor/plank/laravel-mediable/src/MediaUploader.php:118

This error is relate to de following function
```
public function fromSource($source): self
{
    $this->source = $this->factory->create($source);
    
    return $this;
}
```

My current specs are:
- PHP 7.4.28
- Laravel Framework 8.83.8
- MacOs 11.6.5 with Valet 2.18.10

**Comment by frasmage** [comment]
You aren't using the Facade but the implementation class itself. Make sure that you have properly registered the Facade in your app config, and that you are including it from the `\MediaUploader` namespace. alternatively access the Facade directly `Plank\Mediable\Facades\MediaUploader`.

**Comment by faridsa** [comment]
Thank your  for your kindly reply.
According to documentation I'm using in my controller

```
...
use Plank\Mediable\Facades\ImageManipulator;
use Plank\Mediable\HandlesMediaUploadExceptions;
use Plank\Mediable\MediaUploader;

class SlideController extends Controller
{
    use HandlesMediaUploadExceptions;

...
$slide = Slide::create($request->validated());
        if (! empty($request->desktop_image)):
            $desktop_image = MediaUploader::fromSource($request->desktop_image)->toDirectory('slides')->upload();
        $slide->attachMedia($desktop_image, 'desktop_image');
        endif;
...
}

```

This code was working fine till a couple of days ago, but now is firing that error, even if I call the facade using the whole path `Plank\Mediable\Facades\MediaUploader::fromSource($request->desktop_image)->toDirectory('slides')->upload();`

**Comment by frasmage** [comment]
so the `use` statement in your example is the issue since it is trying to statically access the implementation. 

`use \MediaUploader;` or `use Plank\Mediable\Facades\MediaUploader;` should work. If they don't, are you getting an error from the service container? You may not have registered the ServiceProvider properly, though Laravel should be able to auto-discover it from [composer.json](https://github.com/plank/laravel-mediable/blob/master/composer.json#L50-L58)

**Comment by faridsa** [comment]
Gotcha! it works now using your solution.
Thank you so much!
