### ISSUE TITLE
Streaming response with seekable

### ISSUE THREAD

**Issue by Surt** [plank/laravel-mediable#284]
Anyone have an a idea,

I'm using successfully the code suggested by the library 
```php
return response()->streamDownload(
                function () use ($resource) {
                    $stream = $resource->stream();
                    while ($bytes = $stream->read(1024)) {
                        echo $bytes;
                    }
                },
                $resource->basename,
                [
                    'Content-Type'   => $resource->mime_type,
                    'Content-Length' => $resource->size,
                    'Cache-Control'  => $cache

                ],
                'inline'
            );
``` 

My problem is that with a "Video" media the stream response is not seekable. this is, on an html video element I can't seek into parts of the video, only look at it secuentially.

**Comment by frasmage** [comment]
Designing a streaming server is outside of the scope of support of this package. That isn't to say that you can't combine the package with this function, but you will need to figure out how your application handles the seek events yourself. IIRC, the [range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Range) or [content-range](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Range) header is usually used for this purpose. You may need to adjust the stream handling to properly return to portions of the file that the browser is expecting.
