### ISSUE TITLE
Feature Request: use app locale for sanitizing path and filename with Str::ascii

### ISSUE THREAD

**Issue by marvinschroeder** [plank/laravel-mediable#285]
Would be great if the `Plank\Mediable\Helpers\File` uses the app()->locale() for sanitizing path and filename via Str::ascii, since 'en' is the default language. Or if there is a config option to define which locale/language to use.

Use case: support german words like "Schön" > "Schoen" ;)

**Comment by frasmage** [comment]
this behaviour is now released in v5.5.0

Cheers!
