### ISSUE TITLE
MediaUploader::importPath not working for upper case extensions

### ISSUE THREAD

**Issue by zimsa** [plank/laravel-mediable#290]
The added line

`$extension = strtolower($extension)`

in method `verifyExtension` of class `MediaUploader` changes the extension from uppercase to lowercase.

We are using `MediaUploader::importPath($disk, $path)` for importing files from the local filesystem. The method doesn't work anymore if a files extension is written in capitals. The extension is converted to lowercase before the existence of the path is verified:

```
public function import(string $disk, string $directory, string $filename, string $extension): Media
{

  /* ... */

  $model->extension = $this->verifyExtension($extension);

  if (!$storage->has($model->getDiskPath())) {
      throw FileNotFoundException::fileNotFound($model->getDiskPath());
  }

  /* ... */
}
```

_Originally posted by @zimsa in https://github.com/plank/laravel-mediable/issues/265#issuecomment-1165678902_

**Comment by frasmage** [comment]
Fixed in 5.6.0
