### ISSUE TITLE
Mediable relationship turning up empty for random relations

### ISSUE THREAD

**Issue by ayush123460** [plank/laravel-mediable#293]
There is a product model with the mediable trait, attaching/detaching/loading etc works fine. On certain model records, the media relationship comes up empty and therefore no tags are found either, but when looking at the database everything exists as it's supposed to be.

Product model uses UUIDs as the primary key.

Not sure how to debug this so please let me know if any additional logs/data is needed.

Edit: Looking at the database properly, some of the records in the `mediables` table have an outrageous `mediable_id` as follows:
![image](https://user-images.githubusercontent.com/13494534/176570321-be5b5044-e321-430b-a3a5-0df416803825.png)

**Comment by ayush123460** [comment]
From a short time tinkering with records and uuids, turns out the `mediable_id` is somehow converted from a uuid to an integer, thus breaking the relationship at times

For ex, `0012dffc-1e77-41a8-b5c6-e4cd00fdc337` converts to 12 :thinking:

**Comment by frasmage** [comment]
The default migration files provide integer keys. If you are using UUIDs as primary keys in your application, then you would need to apply a separate migration to change the various media_id, original_media_is and mediable_id columns to a type that can support UUIDs (e.g. CHAR, VARCHAR, etc.).

**Comment by ayush123460** [comment]
Yes, I totally forgot to check what database structure the package needs when it worked flawlessly during dev and in a staging environment 😅 props to mysql too I guess. From further testing I can confirm all my problems are exactly because of the ID field being 2 different types.

Thanks for the reply and the package!
