### ISSUE TITLE
Trait "App\Models\MediaUploader" not found

### ISSUE THREAD

**Issue by rapgithub** [plank/laravel-mediable#295]
my model has this: I cannot use in my controller MediaUploader because of this error! 
can someone send a sample of model and controller using mediable to find the issue? thanks

```
use Plank\Mediable\Mediable;

class StoreMedia extends Model
{
    use HasFactory;
    use Mediable; 
    use MediaUploader; //use the facade

```

also if I add this line to my model

```
use Plank\Mediable\MediaUploader;
```

I get this error:

```
App\Models\StoreMedia cannot use Plank\Mediable\MediaUploader - it is not a trait
```

any clues? 
thanks

**Comment by frasmage** [comment]
`MediaUploader` isn't a trait, it is a class and a facade meant to be called from your controller or services. Only `Mediable` is intended to be `use`'d like that.

e.g. 
```php
public function create(Request $request) {
    MediaUploader::fromSource($request->file(...))->toDestination(...)->upload();
}
```

**Comment by rapgithub** [comment]
so seeing your reply this means that the model does not have to include the class? 

do you have a sample for the model and controller because I am still having the same error! I followed the instructions online and same error all the time! I am using the laravel 9 version.

thanks for the tips!
