### ISSUE TITLE
Using external api for variants

### ISSUE THREAD

**Issue by JacquesLG** [plank/laravel-mediable#296]
Hello,

I'd like to know if it would be possible to create variants by sending and receiving images from an external API.

**Comment by frasmage** [comment]
Absolutely. The package's MediaUploader can convert a remote image in the
form of a URL, stream resource (e.g. guzzle response content) or buffered
image string into local files and models. You can similarly stream or
upload your local files to a remote endpoint. It is just up to you to wire
the 3rd party endpoint calls up to the package

**Comment by JacquesLG** [comment]
Hi,

Thanks for your answer, I may not have formulated my question correctly.

I am trying to use tinify's API to create variants.

Is something like this code proposal possible?

```
ImageManipulator::defineVariant(
    'thumbnail',
    Tinify::fromFile($image);  
);
```

Where Tinify would return an image to save to file as a variant.

**Comment by frasmage** [comment]
So `defineVariant` takes an `ImageManipulation` instance which takes a callback that will be passed an intervention image instance. In theory, you could manipulate the intervention image instance to point to the results of your tinify call. Alternatively, you could pass the tinify results to the `Uploader` and set the `original_media_id` attribute on the resulting media instance to indicate that it is a variant of another media.
