### ISSUE TITLE
User-Media Relationship

### ISSUE THREAD

**Issue by rhonz10** [plank/laravel-mediable#30]
Hi!

I'm building a media manager for a project where users can upload images and attach them to posts, and laravel-mediable is great for that requirement. However, is there a way for the users to see only their uploaded images?

What I was thinking is to modify the media table and add a foreign key to the users table. What I don't know is how to have the user_id inserted together with the rest of the media details. 

Any suggestions on how to achieve this?

Thanks.

**Comment by frasmage** [comment]
Hi @rhonz10,

Anything stopping you from just doing something like this?

```php
$media = MediaUploader::...->upload();
$media->user_id = $request->user()->getKey();
$media->save();
```

Granted, that is an extra query if that is relevant for your scale. You could always subclass the MediaUploader (don't forget to swap out the container binding) to perform that task during the regular upload process.

**Comment by rhonz10** [comment]
I'll check this out. Thanks!
