### ISSUE TITLE
Creating PDF thumbnails

### ISSUE THREAD

**Issue by booni3** [plank/laravel-mediable#302]
I realise the Image Manipulator is for images only. 

Can we hook into the upload to generate a variant for a file that cannot be pushed through the ImageManipulator?

In my case, I want to generate a thumbnail from a PDF and save it as an image variant.

**Comment by frasmage** [comment]
Great question! The image manipulation code that comes with the library
currently only supports images. That said, you can absolutely tie media
that you create manually together using the built-in variant system. E.g.

# upload the pdf using the MediaUploader as normal
# Generate the thumbnail using whatever mechanism you have available
# Create a Media record for the thumbnail (e.g. pass the file/stream from
the above step to the uploader)
# call `$thumnailMedia->makeVariantOf($pdfMedia, 'thumb')` to link them
