### ISSUE TITLE
Laravel 10

### ISSUE THREAD

**Issue by selfsimilar** [plank/laravel-mediable#304]
When trying to update my site to Laravel 10 I get the following error from this package "laravel/framework replaces illuminate/database and thus cannot coexist with it." Full error below:

```
Problem 1
    - Root composer.json requires laravel/framework ^10. -> satisfiable by laravel/framework[v10.0.0].
    - plank/laravel-mediable 5.8.0 requires illuminate/database ^8.83.3|^9.0 -> satisfiable by illuminate/database[v8.83.3, ..., v8.83.27, v9.0.0, ..., v9.52.0].
    - Only one of these can be installed: illuminate/database[v6.0.0, ..., v6.20.44, v7.0.0, ..., v7.30.6, v8.0.0, ..., v8.83.27, v9.0.0, ..., v9.52.0, v10.0.0], laravel/framework[v10.0.0]. laravel/framework replaces illuminate/database and thus cannot coexist with it.
    - Root composer.json requires plank/laravel-mediable ^5.8 -> satisfiable by plank/laravel-mediable[5.8.0].
```

I removed `illuminate/database` from `composer.json` and ran the unit tests successfully. I'm happy to create a PR if you think that's sufficient coverage.

**Comment by ls-sean-fraser** [comment]
5.4.0 released which adds Laravel 10 support

**Comment by selfsimilar** [comment]
Hmm, ok. I just tried to change the version number to the most recent since it was complaining earlier, and I guess I overshot by going to 5.8. Is there some documentation about what version number is current or compatible w different Laravel versions?

**Comment by selfsimilar** [comment]
5.4.0 added Laravel 9 support, not 10. 

https://github.com/plank/laravel-mediable/releases/tag/5.4.0

I don't think this package is compatible with Laravel 10, yet.

**Comment by ls-sean-fraser** [comment]
Oy, sorry. I got my signals crossed between different packages all receiving Laravel 10 requests/PRs at the same time. This one needs to be done as well. PR is welcome, otherwise I will try to work on it tonight if I can.

**Comment by frasmage** [comment]
support added in 5.9.0. Sorry again about the initial confusion!

**Comment by selfsimilar** [comment]
Thank you!

**Comment by sandip-b-7span** [comment]
Hi 
I am still getting issue in installation in laravel 10.
Here you can check the screenshot : 
![image](https://github.com/plank/laravel-mediable/assets/115146134/3cc5ba53-cc41-4b2b-9c2f-af586421d9b3)
