### ISSUE TITLE
Upload progress

### ISSUE THREAD

**Issue by dbateson** [plank/laravel-mediable#310]
Hi, Is there anyway to to get the upload progress of files uploaded to an s3 bucket?

**Comment by frasmage** [comment]
Hi @dbateson,

PHP is single-threaded so reporting on that is not trivial to implement. You would need to stream the file incrementally, periodically writing progress state to some cache (e.g. disk, Redis, etc.), which could be polled by a separate request from your frontend. This will make the upload slower.

Unfortunately, that isn't supported out of the box by this package. The `MediaUploader` will stream the whole file to the selected filesystem synchronously without stopping to report on progress. 

One approach that I've seen done in the past is to show upload progress from Javascript to PHP (easily measured) then call whatever manipulation/storage the backend is doing "processing" until the request completes.

**Comment by dbateson** [comment]
Ok thanks
