### ISSUE TITLE
How do I show image in filament ImageColumn?

### ISSUE THREAD

**Issue by veliborr** [plank/laravel-mediable#312]
Hello, how do I show my first image in my filament BikeResource

Tables\Columns\ImageColumn::make('image')

In my Bike controller I'm retrieving my first image:

```
public function index(Request $request)
    {
        $bikes= Bike::with(['media' => function($q){
                $q->wherePivot('tag', 'bikes')->wherePivot('order', '1');
            }])
            ->where('isLive', 1)
            ->where('pCena', null)
            ->orderBy('ord')
            ->orderByDesc('created_at')
            ->get();
        return Inertia::render('Bike', ['bikes' => $bikes]);
    }
```
    
and using it like this in vue

`<img  :alt="bike.media[0].filename"  :src="'./storage/images/' + bike.media[0].filename + '.' + bike.media[0].extension"  />`

**Comment by frasmage** [comment]
I'm not specifically familiar with filament. From the example that you provided, as you are only passing some of the path components (missing the directory component). When you render the data to return from your back end, are you able to invoke the `$media->getUrl()` method and include the result as an extra field on each record? That will generate the full public URL for each file. Looking at the the source code of Inertia, it seems to invoke toArray() on the models that you are passing, so perhaps you could override that to pass in the extra values that you need on the frontend.

**Comment by veliborr** [comment]
I solved it. Thank you.
