### ISSUE TITLE
How can I create svg variants for a given media

### ISSUE THREAD

**Issue by Stephan-MC** [plank/laravel-mediable#313]
Please I have difficulties trying to export some media as svg files. Anyone here with an idea ?

**Comment by frasmage** [comment]
What formats are you trying to convert from and to? 

This package's image manipulation feature is based on the Intervention Image library which can only convert between raster image formats (pixel based, e.g. jpg, png, gif, webp, etc.). SVG is a vector image format. There are ways to generate SVG's from raster images, you would need to find a library that can perform such a conversion. Once you figure that out, you can use the `$media->makeVariantOf($original, $variant_name)` method to link a new media record to the original.

**Comment by Stephan-MC** [comment]
Ok. Thanks.

will have a look
