### ISSUE TITLE
Uploading to S3 from remote url directly

### ISSUE THREAD

**Issue by georgefromohio** [plank/laravel-mediable#314]
Group, wonderful package - quick question... Is there a way to upload from a remote url directly to S3?

```php
MediaUploader::fromSource('https://...')->toDisk('s3')->upload();
```

Nothing shows up in the buckets. Is the intended use to first save it locally and then move it to s3? Otherwise, am I doing something wrong?

```php
MediaUploader::fromSource('https://...')->toDisk('local')->upload()->moveToDisk('s3', '/');
```

**Comment by frasmage** [comment]
Hello, the code above should work fine. There shouldn't be any reason to need to move it twice like you have in your second example.

1. make sure the "s3" disk is properly configured with the right path and credentials for the bucket
2. make sure the URL you are accessing is publicly available. if it requires authentication, you might want to use something like Guzzle to establish the connection and pass the body stream to the uploader
3. do you get any noticeable errors? Do you get a Media model back? If so, what values do you see in the database for that row?

**Comment by georgefromohio** [comment]
Aaah, the bucket was default set to `private` and the default visibility on the model was set to `public` working well since I switched that. Sorry about that. Thanks for the immediate response. Appreciate you @frasmage !
