### ISSUE TITLE
[Error] Attempted to lazy load [variants] on model [Plank\Mediable\Media] but lazy loading is disabled.

### ISSUE THREAD

**Issue by faridsa** [plank/laravel-mediable#316]
When working on local environment this error is trigged by the following code:

```
$patterns = Pattern::with('media')
    ->orderBy('name')
    ->get();
```

And even this code gives the same error

```
$patterns = Pattern::with('media')
    ->with('media.variants')
    ->orderBy('name')
    ->get();
```

Any way to solve it?

**Comment by frasmage** [comment]
Hi there, I can't seem to reproduce this. Replicating the two scenarios above don't throw any exceptions for me. I've tried disabling lazy loading for the entire test suite and don't get any failures.

Is it possible that you have something else in your codebase that could be attempting to read or modify the relations before the relations are eager loaded? Perhaps eloquent hook events such as `retrieved`
