### ISSUE TITLE
Unable to install on laravel 10.10

### ISSUE THREAD

**Issue by riju10121** [plank/laravel-mediable#317]
I am on laravel 10.10.1. I am getting this error when trying to install this package.

![image](https://github.com/plank/laravel-mediable/assets/95690272/abea1992-34ba-4268-807f-697a086d75d0)

Can you help me out?

**Comment by frasmage** [comment]
Hello! Apologies, I forgot to comment that this is fixed last week in 5.9.1

**Comment by sandip-b-7span** [comment]
Still i can not able to install in laravel10.
here you can check the error : 

![image](https://github.com/plank/laravel-mediable/assets/115146134/a740b812-edd3-49d0-bb3f-0c349e7254f6)
