### ISSUE TITLE
Slow syncing

### ISSUE THREAD

**Issue by martinEtflais** [plank/laravel-mediable#319]
Hello first of all thanks for a great package Im having quite a great experience so far but Im struggling with one problem. Im trying to sync products with theirs images files etc from api giving me around 180k products with all the files saved on the mounted nfs. This should be pretty fast considering there is no need to upload / move files but it takes more than 8hrs to complete the sync (was around 50minutes before adding file sync). Ive managed to half it down by not using mediauploader (which cannot handle duplicates from disk the same way like upload does unfortunatelly) and manually filling the database but this is still considerably slow. I feel like Im missing something there are no manipulations no variants just a pure save to DB... Can you give me some tips how to speed things up? This job should run like every 3-4 hours but this seems quite imposible right now and the number of products is about to grow so this is going to be a much bigger problem for me eventually. I can provide a piece of code if it helps. Thx in advance for any help

**Comment by frasmage** [comment]
Hi @martinEtflais,

A few thoughts:

- The MediaUploader is designed for ease of use for simple upload scenarios, syncing 180k in a single process is definitely more complex use case. It can absolutely work, but as you noted it is a little slower as there is a minor cost to the abstractions that make it easy to use, which adds up at that scale. You are probably better off writing a script that handles the uploader tasks that you actually need a way that is designed for your scale (as I think you have already done)
- Do you really need to resync every single file every few hours? Are you not able to compare a file hash/checksum to see if the contents of the file have changed and skip it if it hasn't? That should cut the execute time down a lot
- The Eloquent save() method (which MediaUploader uses) will execute a separate INSERT/UPDATE query per row, requiring a roundtrip to the database for each, which adds up if saving hundreds of thousands of rows one by one. If you batch your process and perform a [bulk upsert](https://laravel.com/docs/10.x/eloquent#upserts) , you can drastically cut down on network time.
