### ISSUE TITLE
MySQL Version Requirements?

### ISSUE THREAD

**Issue by simplethemes** [plank/laravel-mediable#32]
Is there a minimum supported version of MySQL for this package? Running 5.6.28 I get the following error when attempting to attach a Mediable:

````SQLSTATE[42000]: Syntax error or access violation: 1140 Mixing of GROUP columns (MIN(),MAX(),COUNT(),...) with no GROUP columns is illegal if there is no GROUP BY clause (SQL: select max(`order`) as aggregate from `media` inner join `mediables` on `media`.`id` = `mediables`.`media_id` where `mediables`.`mediable_id` = 3 and `mediables`.`mediable_type` = App\Tower and `tag` = thumbnail order by `order` asc)````

**Comment by simplethemes** [comment]
Just to confirm, here is my controller function:

````    public function files(Request $request) {
        $files = $request->file('file');
        $tower = Tower::find($request->id);
        $media = MediaUploader::fromSource($files)->toDisk('uploads')->upload();
        $tower->attachMedia($media,'thumbnail');
        return $media;
    }````

**Comment by frasmage** [comment]
What storage engine are you using? I am not able to reproduce this with my setup (InnoDB).

[The code in question](https://github.com/plank/laravel-mediable/blob/master/src/Mediable.php#L441) is simply running the `max()` method of the Laravel query builder.

**Comment by jdhmtl** [comment]
Sounds like it might be related to [ONLY_FULL_GROUP_BY](https://dev.mysql.com/doc/refman/5.6/en/sql-mode.html#sqlmode_only_full_group_by)

**Comment by frasmage** [comment]
I suspect the automatically applied `ORDER BY` is to blame. @simplethemes, do you still get the same issue if you comment out the line [Mediable.php:47](https://github.com/plank/laravel-mediable/blob/master/src/Mediable.php#L47)? 

If that fixes it, I will need to find a way to make applying the order clause automatic for things like `load()`, but provide a way to disable for aggregate functions.

**Comment by borisdamevin** [comment]
I have the same problem on my application.

**Comment by frasmage** [comment]
Rewrote the method which pulls the highest value. Query no longer contains unnecessary junk. I rewrote the method to be able to check multiple tags with a single query.

This bug made me notice an issue where multiple media passed to the same `attachMedia()` or `syncMedia()` call would receive the same order value. `attachMedia()` has been rewritten to address this.
