### ISSUE TITLE
Getting Issue in laravel 10 while install plank / laravel-mediable version 5.9

### ISSUE THREAD

**Issue by sandip-b-7span** [plank/laravel-mediable#320]
![image](https://github.com/plank/laravel-mediable/assets/115146134/150c88fc-d177-42d1-9b13-4e6140576020)

**Comment by frasmage** [comment]
current version is [5.9.1](https://github.com/plank/laravel-mediable/releases/tag/5.9.1https://github.com/plank/laravel-mediable/releases/tag/5.9.1) not 9.10. Also that white warning is indicating packagist can't be reached so you may have out of date information.
