### ISSUE TITLE
Documentation is not clear how to use the package

### ISSUE THREAD

**Issue by khanakia** [plank/laravel-mediable#323]
I do not find anywhere in the documentation or on GitHub readme file that i have to include `use Mediable` 

It's a road blocker for the new user because of incomplete documentation.

```php
use Plank\Mediable\Mediable;
class Contact extends Model
{
    use HasFactory;
    use Mediable;
}
```

**Comment by guidipolito** [comment]
It's the first thing in
handling media > attaching media

Do you think It would be better as an example on getting started?

**Comment by khanakia** [comment]
Yes, I see now i did not see it before I went too many pages.

Yes, that would be great to have a Quick Introduction on how to get started. instead of going through the whole docs.

Check this for reference: https://laravel-livewire.com/docs/2.x/quickstart

**Comment by frasmage** [comment]
Added quickstart section to the installation page documentation (in #343 branch)

**Comment by frasmage** [comment]
Version 6.0.0 has been released.
