### ISSUE TITLE
PHPStan - Add template to MediableCollection

### ISSUE THREAD

**Issue by TheoDVC** [plank/laravel-mediable#325]
I encountered a problem when using PHPStan / Larastan, and was able to correct it by adding the following to the MediableCollection.

I'm leaving this here for people encountering this error and for reference either in a pull request or for later.

```php
/**
 * Collection of Mediable Models.
 * 
 * @template TKey of array-key
 * @template TModel of Model
 * @extends Collection<TKey, TModel>
 */
class MediableCollection extends Collection
{
```

**Comment by frasmage** [comment]
This is implemented in the branch for the upcoming major version release.

**Comment by frasmage** [comment]
Version 6.0.0 has been released.
