### ISSUE TITLE
Move media to root directory

### ISSUE THREAD

**Issue by richardhedges** [plank/laravel-mediable#328]
When uploading media, I'm able to leave the directory as default, which leaves the directory column _empty_.

If I upload media to a directory, and wish to move it to the root (i.e. _empty_ directory), using the `move` method, I see the following error: `Plank\Mediable\Media::move(): Argument #1 ($destination) must be of type string, null given`.

As far as I can see there's no valid method to move a media item back to the disk's root directory.

**Comment by frasmage** [comment]
Have you tried passing empty string (`''`) to the directory argument?
