### ISSUE TITLE
Call to undefined method Plank\Mediable\ImageManipulation::toPngFormat()

### ISSUE THREAD

**Issue by khanakia** [plank/laravel-mediable#332]
I am using this example from the docs https://laravel-mediable.readthedocs.io/en/latest/variants.html#image-manipulation-callback

and getting the error `Call to undefined method Plank\Mediable\ImageManipulation::toPngFormat()`

![Screenshot 2023-10-05 at 4 30 48 PM](https://github.com/plank/laravel-mediable/assets/2174170/dd49635e-3c74-49f0-83c7-ddc7f9f32565)

**Comment by frasmage** [comment]
looks like there is a typo in the docs. The method should be named `->outputPngFormat()`

**Comment by khanakia** [comment]
Can you update the docs please?

**Comment by frasmage** [comment]
docs corrected in upcoming major version branch

**Comment by frasmage** [comment]
Version 6.0.0 has been released.
