### ISSUE TITLE
Files are not removed from disk on deleting the variants

### ISSUE THREAD

**Issue by khanakia** [plank/laravel-mediable#333]
I want to delete all the variants by deleting the Media and using the below command. 
It deletes the variants and media from the Database and also deletes the only Media from the disk but does not delete the variants from the disk.

```php
$media->variants()->delete();
$media->delete();
```

**Comment by frasmage** [comment]
I appears that the collection delete method doesn't delete the files since it uses a query builder under the hood. If you want to remove the files you should delete the variants in a foreach loop

**Comment by khanakia** [comment]
May be we can do something about that ?

**Comment by frasmage** [comment]
Upon further inspection, this isn't the collection class, but the laravel relationship entity. It is normal behaviour that deleting directly from the relationship clears the records in the database without trigger any model events (the models are never loaded into memory). No intention to change this behaviour at this time.
