### ISSUE TITLE
Import changes visility on original file

### ISSUE THREAD

**Issue by Sparclex** [plank/laravel-mediable#335]
When trying to import from a [ready only](https://laravel.com/docs/10.x/filesystem#scoped-and-read-only-filesystems) disk I discovered that the uploader always updates the visibility of the original file. This does of course not work with a read only filesystem. Is there a reason for that?

See: 
https://github.com/plank/laravel-mediable/blob/master/src/MediaUploader.php#L683

Edit: 
I just looked at the corresponding commit and realized that this is a feature, since it allows to change the visibility on import. The problem is, that by default it would change it to public for every imported file. Would it be possible to keep the existing visibility when using the import method?

**Comment by frasmage** [comment]
Hi there,

Yes, this is an old feature that has a default value. IIRC, when I first wrote this package years ago, visibility wasn't a defined field on the disk config, though now it is. Reading the value from the disk config seems like a more reasonable baseline, so I am adding the enhancement flag to this issue. 

In the meantime, feel free to use the [visibility](https://laravel-mediable.readthedocs.io/en/latest/uploader.html#visibility) methods in your code to set the value you expect for that upload

**Comment by Sparclex** [comment]
I would be happy to create a PR for this. I think currently of two solutions:

```php
MediaUploader::keepVisibility()->importPath($disk, $path);
```

Or since this parameter would only make sense on the `import`/ `importPath` method.

```php
MediaUploader::importPath($disk, $path, visibility: null | 'private' | 'public');
MediaUploader::import($disk, $directory, $filename, $extension, visibility: null | 'private' | 'public');
```

> In the meantime, feel free to use the [visibility](https://laravel-mediable.readthedocs.io/en/latest/uploader.html#visibility) methods in your code to set the value you expect for that upload

When using the existing visibility method, it would still send some sort of change request to the filesystem which would lead to an exception in a read only filesystem.

**Comment by frasmage** [comment]
I have implemented a fix for this in the branch for the upcoming major version release. `MediaUploader::import()` will only update visibility if one is declared as configuration

**Comment by frasmage** [comment]
Version 6.0.0 has been released.
