### ISSUE TITLE
Support `intervention/image` ^3.0

### ISSUE THREAD

**Issue by siarheipashkevich** [plank/laravel-mediable#337]
<img width="1393" alt="image" src="https://github.com/plank/laravel-mediable/assets/7753600/b2232a98-12c7-49df-9f0d-705c0477a878">

**Comment by weogrim** [comment]
That will be great, @frasmage can we count on that? Or maybe we can help you in this?

**Comment by uncrackable404** [comment]
Hi, I also join @weogrim's request, I find that it could be useful to have support for version 3 of intervention image. Could something be done about it?

**Comment by weogrim** [comment]
Hi @frasmage. Any news on supporting v3? Do you have plans to support new version? Can we do something to support you? Or maybe you like see PR to accept ?

**Comment by frasmage** [comment]
Hi all, sorry about the silence. Our family grew over the last few months!

I am working on a version 6.0 that will include this compatibility

**Comment by frasmage** [comment]
I have implemented this compatibility in the branch for the upcoming major version release

**Comment by siarheipashkevich** [comment]
When do you plan to release?

**Comment by frasmage** [comment]
Reviewing previous feature requests for anything else worth changing in this major version. Hoping to release in the next week

**Comment by frasmage** [comment]
current progress on v6 is available here: #343

**Comment by frasmage** [comment]
Version 6.0.0 has been released.

**Comment by weogrim** [comment]
@frasmage firstly, congrats on family growing. All the best! 

Thank you very much on working on v6, nice work. Your package saves me hours of work 😁.
