### ISSUE TITLE
base64  uploading

### ISSUE THREAD

**Issue by KFTco** [plank/laravel-mediable#341]
Hi
is there any direct guid to upload base64 files ?
It seems upladoing fromString only works with encoded file from Intervention and it does not work with base64 encoding.

**Comment by KFTco** [comment]
I solved 
Actually your fromString detects base64 image as a text/plain
before sending data to fromString I did some transformation as below:
```php
        $file= preg_replace('/^data:[^;]+;base64,/', '', $file); // $file is a base64 image which is sent to backend via ajax
        $file= base64_decode($file);
```

**Comment by frasmage** [comment]
I have implemented native handling for data URLs in the branch for the upcoming major version release

**Comment by KFTco** [comment]
@frasmage 
Glad to help
there are some new features like accessing models from Media easier ,and also storing variant without adding row in the table .
I will open some new issues if it is possible

**Comment by frasmage** [comment]
Version 6.0.0 has been released.

Feel free to open feature requests or your own PRs for the suggestions you implied above
