### ISSUE TITLE
Change Facade 

### ISSUE THREAD

**Issue by lucassmacedo** [plank/laravel-mediable#344]
Hi. How can i change MediaUploader facede, i need to do some changes to mult tenant, o i need to add tenant_id on PopulateModel Method.

**Comment by frasmage** [comment]
You don't need to override anything. the MediaUploader exposes a [beforeSave](https://laravel-mediable.readthedocs.io/en/latest/uploader.html#alter-model-before-upload) callback that can be used to apply additional attributes to the model
