### ISSUE TITLE
New migration is not published when using the provider.

### ISSUE THREAD

**Issue by TheoDVC** [plank/laravel-mediable#345]
Hello !

While upgrading to v6, I had a conflict due to having a custom table name for my media table.
Then i tried to publish this new migration (```2024_03_30_000000_add_alt_to_media```), it did not appear, and it is indeed missing from the Provider.

This should be fixable by adding the following to the provider :

```php
if (empty(glob($this->app->databasePath('migrations/*_add_alt_to_media.php')))) {
        $this->publishes([
            $root . '/migrations/2024_03_30_000000_add_alt_to_media.php' => $this->app->databasePath('migrations/'.date('Y_m_d_His', time()).'_add_alt_to_media.php'),
    ], 'mediable-migrations');
}
```

Thank you !

**Comment by frasmage** [comment]
Good catch, oversight on my part.

**Comment by frasmage** [comment]
6.0.3 tagged with the fix

**Comment by siarheipashkevich** [comment]
@frasmage 

<img width="1708" alt="image" src="https://github.com/plank/laravel-mediable/assets/7753600/9de9aa32-97ae-4eb8-88c6-2c5cd2636516">

When I'm trying to migrate after upgrading

**Comment by frasmage** [comment]
Interesting, Mysql doesn't allow default on TEXT, while sqlite won't use the default value without it. I've moved the default to the model in 6.0.4
