### ISSUE TITLE
Intervention Image Error

### ISSUE THREAD

**Issue by sgtcoder** [plank/laravel-mediable#346]
When installing Laravel 11 with Plank Mediable 6, I get this error:
```Unresolvable dependency resolving [Parameter #0 [ <required> Intervention\Image\Interfaces\DriverInterface|string $driver ]] in class Intervention\Image\ImageManager```

The fix I had to do was force `intervention/image` to be 2 vs the latest 3.
```
"intervention/image": "2.*",
```

**Comment by edux04** [comment]
I have the same issue,  Laravel 11 and  PHP 8.3.

**Comment by frasmage** [comment]
Hi there, so this isn't a bug with the package, it's just that Laravel doesn't know which driver to use when building Intervention image class without you telling it. It isn't really up to this package to pick for you, as you may have other code using the library already in place.

Adding the following to a service provider would be sufficient:

```php
// for GD
$app->bind(Intervention\Image\Interfaces\DriverInterface::class, \Intervention\Image\Drivers\Gd\Driver::class);

// for Imagick
$app->bind(Intervention\Image\Interfaces\DriverInterface::class, \Intervention\Image\Drivers\Imagick\Driver::class);
```

Preferably, you can use the [intervention/image-laravel](https://image.intervention.io/v3/introduction/frameworks#laravel) package to configure intervention/image, then Mediable will be able to load it from the container already set up.

I'm sure that others will run into similar issues, so I will add a note about this to the documentation. That you for bringing it to my attention

**Comment by sgtcoder** [comment]
It works fine on Plank Mediable 5 and also on Image Intervention version 2.

We shouldn't need to make all these changes to get it to work.

**Comment by frasmage** [comment]
That is a change in the intervention/image package, not this one. Version 2 of intervention/image would automatically assume the use of GD as a driver, if no other was specified. Version 3 no longer makes that assumption, and requires a driver to be explicitly provided.

You are welcome to pin your application's composer.json to use `"intervention/image": "^2.0"` if you prefer that one. This package is compatible with both.

**Comment by sgtcoder** [comment]
I am using Imagick with v2 and somehow it works.

Are you able to put that in your composer requirements?

So everyone doesn't have to run through this same issue?

**Comment by frasmage** [comment]
Some manual configuration was always necessary to use imagick:
- Do you have a config/image.php file configuring which driver to use, such as the one described in [this documentation](https://image.intervention.io/v2/introduction/installation#integration-in-laravel)? Previously the provider was built into the intervention/image package. With V3 this provider is extracted out into the `intervention/image-laravel` extension.
- The [docs](https://laravel-mediable.readthedocs.io/en/latest/variants.html) of the this package suggested an alternative from prior to that provider being available

I don't think it make sense to require it (manual installation steps necessary), but I will add the `intervention/image-laravel` to the composer "suggest" list to provide the reminder. I will also update the docs accordingly with V3 instructions.

**Comment by sgtcoder** [comment]
I actually was unaware that Plank was using GD by default or why it is even used in the first place?

I do use Imagick post processing to crop, compress, and scale the image. I know Plank doesn't do this.

**Comment by frasmage** [comment]
Tagged 6.0.2 with composer suggest and [new documentation](https://laravel-mediable.readthedocs.io/en/latest/variants.html)

**Comment by frasmage** [comment]
plank/mediable uses intervention/image as it is available in the Laravel service container, it doesn't configure that 3rd party package for you. If you were previously doing no configuration, then you were using GD which was the default of that package. 

Yes, the GD extension is capable of [cropping](https://www.php.net/manual/en/function.imagecrop.php) and [resizing](https://www.php.net/manual/en/function.imagescale.php) images.

**Comment by sgtcoder** [comment]
Installing that package throws a new error
```
Illuminate\Container\EntryNotFoundException 

Intervention\Image\ImageManager
```

**Comment by sgtcoder** [comment]
OMG, thank you! I ran the composer update and it finally installed successfully and ran the package:discover script.

**Comment by frasmage** [comment]
glad it worked! Apologies for the back and forth on this. There was a bit of a chicken and egg situation in the bootstrapping order that I wasn't aware of
