### ISSUE TITLE
LocalUrlGenerator: strpos is not the correct way to determine if a path isPubliclyAccessible

### ISSUE THREAD

**Issue by hiendv** [plank/laravel-mediable#35]
```php
    public function isPubliclyAccessible()
    {
        return strpos($this->getAbsolutePath(), public_path()) === 0;
    }
```
Symbolic link should be considered.
See more: https://laravel.com/docs/5.3/filesystem#the-public-disk

**Comment by frasmage** [comment]
Right, I had forgotten about that.

I have added an approach to handling symlinked storage disks in ce41effc27e62904e265f34587dad2bf57bbf520 and updated the [docs](http://laravel-mediable.readthedocs.io/en/latest/configuration.html#disk-visibility) to explain how to use it.

Thank you for bringing this to my attention!
