### ISSUE TITLE
Demo

### ISSUE THREAD

**Issue by blondie63** [plank/laravel-mediable#365]
Is there any demo that uses this library?
Just to understand what it does exactly... :)

**Comment by frasmage** [comment]
There is no live demo app. This library is intended to make file uploads, manipulations and associations to Eloquent models easier. I am not particularly interested in maintaining and securing a demo server that lets anyone upload random files.

You can review the [documentation](http://laravel-mediable.readthedocs.io/en/latest/) to get a sense of the feature set of this library.

**Comment by blondie63** [comment]
ok thanks
