### ISSUE TITLE
how to set url path folder domain order

### ISSUE THREAD

**Issue by thandonguocmo2020** [plank/laravel-mediable#40]
I'm working on 3 orther folder servers
Backend: domain a == api
frontend: domain b == call api
media   : domain c ?

---

$media->getUrl();   // errors url 

Help me !

**Comment by frasmage** [comment]
Hi, @thandonguocmo2020,

I am happy to help, but I don't understand what your issue is. I need you to provide me with some more information. 

How are your filesystem disks set up?
What are the attributes of that media instance?
What error message are you receiving?

**Comment by thandonguocmo2020** [comment]
help me please!!! how to set upload file to outside project. Exaple, in laravel 5.2.  Code processes uploading, normally image will be uploaded inside.
I want it to upload outside in the same level folder. Example: 

Exam: I want to use URL IMAGE similar with  URL BASE 64 and one folder the same position level with  Project.

by one method similar your library:
$media->getURL(). How to use it when I call getURL(). finally I did not receive good result  because media folder lie on Another sever.

**Comment by frasmage** [comment]
Hi @thandonguocmo2020,

I've read through your request a dozen times and I am still not sure what you are asking. 

I can only assume that your issue is a server infrastructure one, which is generally beyond the scope of what I can really help you with – how you set up your hardware is really up to you. Perhaps host your uploads disks on an NFS mount that is visible to all of your servers or use a cloud-based host (S3)?

**Comment by thandonguocmo2020** [comment]
Thank you. let me  one more question:
Your library can handle additional tasks like http://image.intervention.io/getting_started/installation edit the file : size; color...

If it is "ok" the perfect fruit.

**Comment by thandonguocmo2020** [comment]
You can combine two libraries, making it a perfect.

**Comment by frasmage** [comment]
Hi @thandonguocmo2020,

Sorry, I had missed your last question. The question of tying the package to image editing has come up before, and while this is absolutely possible, the implementation to bind the two is up to you. See [this thread](https://github.com/plank/laravel-mediable/issues/10) which might provide some insight in how to approach the problem.
