### ISSUE TITLE
not working laravel 5.3.19

### ISSUE THREAD

**Issue by kniaz-tolya** [plank/laravel-mediable#41]
`                                                                          
  [ErrorException]                                                        
  The use statement with non-compound name 'MediaUploader' has no effect  
                                                                         
`

**Comment by frasmage** [comment]
Hi there, 

this doesn't sound like a bug in the package. Remember, you do not need "use" statements for facades in non-namespaced files. just remove the use statement.

If you believe this is incorrect, could you provide more information, such as a sample of the code that is causing the error? If this error is occurring in file in the mediable package, could you please provide the file name and line.

Let me know if this solves your issue.

Thanks!

**Comment by kniaz-tolya** [comment]
I did all the instructions as described

![2016-10-18 12 58 06](https://cloud.githubusercontent.com/assets/4132867/19464908/18ef83f2-953b-11e6-8130-b71978076b06.png)

**Comment by frasmage** [comment]
Hi there,

It sounds like one of your migration or seed files has the line `use
MediaUploader;`, as I suggested. Remove that line.

`storage/logs/laravel.log` should indicate which file caused the error.

**Comment by kniaz-tolya** [comment]
An error has disappeared, I tried to re-install the module, thank you help
