### ISSUE TITLE
Create image duplicates and upload  

### ISSUE THREAD

**Issue by devillom** [plank/laravel-mediable#43]
Please give me example to upload new image with another sizes
```  
                    if (!$user->hasMedia('avatar_' . $width . 'x' . $height)) {
                        $img = Image::make($user->firstMedia('avatar')->getUrl());
                        if ($crop) {
                            $img->fit($width, $height);
                        } else {
                            $img->resize($width, $height, function ($constraint) {
                                $constraint->aspectRatio();
                            });
                        }
                    }
                  $media = MediaUploader::fromSource($img)
                  ->useHashForFilename()
                  ->toDestination('cloud', 'user/avatars/thumb/')
                ->upload();


```

**Comment by devillom** [comment]
upload from file name ?

**Comment by frasmage** [comment]
Hi @devillom,

You might be interested in the `MediaUploader::import()` method ([docs](http://laravel-mediable.readthedocs.io/en/latest/uploader.html#importing-files)). I would recommending that do whatever modifications you intend to the file, have your image processor save the file somewhere on the filesystem disk, and then use the import method to generate a new `Media` record for it.

Other than that, how you integrate the package with other libraries is up to you.

I hope this helps.

**Comment by devillom** [comment]
Hi, @frasmage 
Thanks! 
 I wrote a function something like this :)
`
    public function getAvatarThumb($size = 25, $options = null)
    {
        if (is_string($options)) {
            $options = ['default' => $options];
        } elseif (!is_array($options)) {
            $options = [];
        }

        if ($this->hasMedia('avatar')) {
            $original_id = $this->firstMedia('avatar')->id;
            $tagname = 'avatar_' . $original_id . '_' . $size;

            if ($this->hasMedia($tagname)) {
                return $this->firstMedia($tagname)->getUrl();
            } else {
                $img = Image::make($this->firstMedia('avatar')->getUrl());
                $img->fit($size);
                $imgData = (string)$img->encode('jpg', 71);
                $filename = md5($this->id . time() . $size);
                $fullpath = 'user/avatars/thumb/' . $filename . '.jpg';
                $result = Storage::disk(config('filesystems.default'))->put($fullpath, $imgData);
                if (!$result) return $this->getNoAvatarUrl($size, $options);
                $meta = Storage::disk(config('filesystems.default'))->getMetaData($fullpath);

                $media = new Media();
                $media->disk = config('filesystems.default');
                $media->filename = $meta['filename'];
                $media->directory = $meta['dirname'];
                $media->extension = $meta['extension'];
                $media->mime_type = $meta['mimetype'];
                $media->aggregate_type = 'image';
                $media->size = $meta['size'];
                $media->save();

                $this->attachMedia($media, $tagname);
                return $this->firstMedia($tagname)->getUrl();
            }

        } else {
            return $this->getNoAvatarUrl($size, $options);
        }
    }
`

**Comment by frasmage** [comment]
Hi @devillom, that seems like a workable solution.
