### ISSUE TITLE
Question about Postgres Support

### ISSUE THREAD

**Issue by rydurham** [plank/laravel-mediable#45]
Hello,

Thank you for this fantastic package! 

I have run into a Sql Query exception and I am not sure if it is actually a bug or if I am doing something wrong on my end.    When attempting to run ```$model->attachMedia($media, 'tag');```  I get this error: 

```
Illuminate\Database\QueryException with message 'SQLSTATE[42601]: Syntax error: 7 ERROR:  syntax error at or near "order"
LINE 1: select `tag`, max(`order`) as aggregate from "mediables" whe...
	^ (SQL: select `tag`, max(`order`) as aggregate from "mediables" where "mediable_type" = App\Author and "mediable_id" = 1 and "tag" in (headshot) group by "tag")'
```

This only happens when using Postgres; it works fine when I try it with Mysql.   Am I doing something wrong?

**Comment by frasmage** [comment]
Hi @rydurham,

I had not run the tests using postgres, only MySQL and SQLite. That said, I can see the problem from your error message. I will try to post a fix later tonight. 

Thanks for reporting this!

**Comment by rydurham** [comment]
Awesome - thank you!
