### ISSUE TITLE
What's the best way to compress an image while uploading?

### ISSUE THREAD

**Issue by kaju74** [plank/laravel-mediable#50]
Hi,

First, I love this package - it's fantastic and very easy to use. But I'm a little bit confused about how to manipulate an image while uploading it (e.g. size it down to a max. resolution). I'm also using the very popular intervention image library, so this one can be used for the file compression. 

So, what's the best way to do this?

I know, I could upload the file using the Image:Class of intervention and put the image string to the media class (fromString), but doing so I'll pass all the validation stuff supported by it.

Regards,
Marc

**Comment by frasmage** [comment]
Hi @kaju74,

There are any number of ways that you could integrate the two packages, so it is really up to you to come up with a solution that suits the needs of you project.

the `MediaUploader` accepts a [number of different inputs](http://laravel-mediable.readthedocs.io/en/latest/uploader.html#source-files) beyond the be the `UploadedFile` from the request. You should be able to use Intervention first to apply your modifications, then pass the manipulated image to the uploader, with `MediaUploader::fromSource($image->getCore)`. It will still perform all of the validation.

Alternatively, you can have Intervention output the image at the intended destination on the disk, then use [`MediaUploader::import()`](http://laravel-mediable.readthedocs.io/en/latest/uploader.html#importing-files).

**Comment by kaju74** [comment]
I've checked that out, but as soon as I use $image->getCore, I'll get the following error:

Could not recognize source, `gd` provided.

Did I had to use a special intervention api command to generate a compatible output?

**Comment by frasmage** [comment]
@kaju74, right, my bad. That method returns a GD resource handle, not a file handle, which is what the uploader is able to process.

Instead, have Imagine output somewhere to to disk (tmp?) and pass the file path to the uploader.

**Comment by kaju74** [comment]
This would do the trick...but there's one local problem.

Example:

$file = $request->file('image');
$tmp = $file->getPath() . '/' . $file->getClientOriginalName();
$image = Image::make($file)->resize(300, 200)->save($tmp);
$media = MediaUploader::fromSource($tmp)->....

This works fine on my live server. As soon as I try this on my developer maschine (Windows 10, XAMPP), I'll got an error:

ConfigurationException in ConfigurationException.php line 34:
Could not recognize source, `C:\xampp\tmp/xyz.jpg` provided.

Any idea?

**Comment by frasmage** [comment]
Ya, I know exactly what that is. The default config only anticipates the path syntax for unix/linux/posix. Windows follows a different pattern.

In `config/mediable.php` add something the following to the `source_adapters[patterns]` array
```
'^[a-zA-Z]:\\' => Plank\Mediable\SourceAdapters\LocalPathAdapter::class
```
