### ISSUE TITLE
File with whitespace in filename does not upload

### ISSUE THREAD

**Issue by ArtworkAD** [plank/laravel-mediable#53]
Hey guys,

I try to upload files like this 

```
$file2 = MediaUploader::fromSource(Input::file('file2'))->useHashForFilename()->toDestination('uploads', '')->upload();
$entry->attachMedia($file2, 'file2');
```

This works for files that have no whitespace. However when a file is named e.g. _Bildschirmfoto 2016-12-28 um 15.25.17_ it throws an error:

<img width="886" alt="bildschirmfoto 2016-12-31 um 14 12 32" src="https://cloud.githubusercontent.com/assets/524580/21577666/62695096-cf63-11e6-8440-890d1dae0187.png">

**Comment by frasmage** [comment]
Hi @ArtworkAD,

I ran the test suite with a file with spaces in its name and that did not cause any issues. Works as expected for me.

For uploaded files, the most common cause of that error is that the file you are attempting to upload is larger that your servers `upload_max_filesize` and/or `post_max_size` ini variables. This causes PHP to reject the input and not place the file in tmp, hence the file not found error. Try increasing those limits or compressing your file.

Let me know if this fixes your issue.

Sean

**Comment by ArtworkAD** [comment]
@frasmage `upload_max_filesize` was at 2M. Thanks for the hint :1st_place_medal:
