### ISSUE TITLE
about the config on_duplicate 

### ISSUE THREAD

**Issue by ibmsoft** [plank/laravel-mediable#54]
current the are three config for on_duplicate
the replace is first delete the finded record and then upload again

i just want  return the find record,how to carray out this?

**Comment by frasmage** [comment]
Hi @ibmsoft,

What is the use case of this? 

I would recommend simply running a query yourself before uploading or after catching an error. For example:

```php
try {
    $source = $request->file('file');
    $media = MediaUploader::fromSource($source)
    ->onDuplicateError()
    ->toDestination($disk, $directory)
    ->upload();
}catch(FileExistsException $e){
    Media::inDirector($disk, $directory)
    ->whereFilename($source->getClientOriginalName)
    ->whereExtension($source->getClientOriginalExtension)
    ->get();
}
```

**Comment by ibmsoft** [comment]
@frasmage thanks
your solution is good
