### ISSUE TITLE
Specified key was too long; max key length is 1000 bytes

### ISSUE THREAD

**Issue by XGhozt00** [plank/laravel-mediable#57]
I get this when running the migrations:

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `media` add u
  nique `media_disk_directory_filename_extension_unique`(`disk`, `directory`, `filename`, `extension`))

  [Doctrine\DBAL\Driver\PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes

Something with this line;
$table->unique(['disk', 'directory', 'filename', 'extension']);

**Comment by frasmage** [comment]
Hi there, that is a limitation with the MyISAM storage engine.  See #16 for options to remedy.
