### ISSUE TITLE
getUrl for multiple media

### ISSUE THREAD

**Issue by Bahram9** [plank/laravel-mediable#58]
hi 
after attaching some media to a model how can I retrieve the media url 
      `$files = $request->file('files');`
   ` foreach ($files as $file) {`
      `  $media = MediaUploader::fromSource($file)->upload();`
       ` $task->attachMedia($media,'image');`
    `  }`

and here too
`$tasks = Task::withMedia('image')->get();`

**Comment by frasmage** [comment]
Hi @Bahram9,

Retrieving paths and URLs from media is explained in the [documentation](http://laravel-mediable.readthedocs.io/en/latest/media.html#media-paths-urls).

In your case, you might do something like this
```
$tasks = Task::withMedia('image')->get();
foreach($tasks->getMedia('image') as $media) {
    $url = $media->getUrl();
    // ...
}`
```
