### ISSUE TITLE
Bad method call exception 'getForeignKey()' upon detaching media tags

### ISSUE THREAD

**Issue by cheelahim** [plank/laravel-mediable#59]
### Description
There is an issue with `Plank\Mediable\Mediable::detachMediaTags()` because it attempts to invoke an undefined method `getForeignKey()` which leads to error:
`Call to undefined method Illuminate\Database\Query\Builder::getForeignKey()`. 
This function is also called in `vendor/plank/laravel-mediable/src/Mediable.php:79`. 

Potentially the other function should called instead: `Illuminate\Database\Eloquent\Relations\BelongsToMany::getQualifiedForeignKeyName()`

### Versions
* Laravel Framework 5.4.11
* plank/laravel-mediable 2.4.1

**Comment by frasmage** [comment]
Hi @cheelahim,

I am aware of that bug and am already working on a fix. Hoping to get it out by the end of the day. 

Laravel 5.4 renamed a bunch of public methods on the relationship classes without aliasing and deprecating the old ones first, or even noting the change in the changelog (bad Taylor!). As such, I didn't get a chance to anticipate the change.

**Comment by frasmage** [comment]
Released a new patch version to address this. Should work for 5.3 and 5.4 for now, will work on restoring full compatibility with older versions soon.
