### ISSUE TITLE
getUrl() in Laravel 5.1 with latest version of laravel-mediable

### ISSUE THREAD

**Issue by karmendra** [plank/laravel-mediable#60]
When I run getUrl() function on Laravel 5.1 with local file-system and s3 as well I get following error.
`$file_url = $media->getUrl();`

> BadMethodCallException in PluggableTrait.php line 85:
> Call to undefined method League\Flysystem\Filesystem::url

Is there any previous version that will work fine with Laravel 5.1?

**Comment by frasmage** [comment]
Hi @karmendra,

Yes, it has come to my attention that there have been some breaking changes in accross versions of the Laravel framework itself. The package originally listed `laravel/framework ~5.0` as a minimum, but I have come to learn that was much too optimistic. The most recent release lists laravel 5.3 or greater and I am working on restoring compatibility with 5.2 and eventually 5.1.

5.2 compatibility shouldn't take too long as only eager loading is failing, I'm not yet sure what incompatibilities exist in 5.1 as the test support package that I am using  (orchestra/testbench 2.2) doesn't seem to be compatible with it.

I will keep you posted.

**Comment by karmendra** [comment]
Thanks for your response, I will wait for 5.1 compatibility specially this issue. I will report as and when I come across issues in 5.1 for this awesome package. For me even though newer versions on laravel have so many cool features, version 5.1 is with LTS.

**Comment by frasmage** [comment]
I appreciate your patience! Working on it.

**Comment by frasmage** [comment]
@karmendra Update on this: I have restored compatibility with laravel 5.2 in the latest release (5.4.3). 

The bug you reported above is due to the fact that the `FilesystemAdapter::url()` method was only added in Laravel 5.2.15. I have swapped out calling that function for direct access to the underlying S3 client, which now works. 

That said, composer won't pull in the latest release with 5.1 yet, as the composer.json currently requires "~5.2" (what I know for sure is compatible). As a stopgap solution, you could copy the `S3UrlGenerator` class from the latest release into your namespace and assign it in your `config/mediable.php`'s `'url_generators'` array. That should solve that particular issue.

Will start on 5.1 soon.

**Comment by karmendra** [comment]
@frasmage Thanks for this, I will try this out. by the way this also need a fix in `LocalUrlGenerator` class.

As a workaround I was using following instead of `$media->getUrl()`

`$file_url = Storage::disk('s3')->getAdapter()->getClient()->getObjectUrl('your-s3-bucket-name'), $directory_name . '/' . $filename);`


I was just thinking if it is possible to have a function `$media->getAdapter()` returning instance of FilesystemAdapter. Ignore this if it doesn't make sense, it was just a thought, may not make sense from your perspective as my perspective is limited.

Thanks again.

**Comment by karmendra** [comment]
Just saw your code change, It work on 5.1, as I mentioned it needs a fix in `LocalUrlGenerator` as well.

Another observation is when the file is uploaded to S3 it is uploaded with the wrong/default mime type instead of the uploaded files mime type, I am not sure if it is related to this package or the aws sdk. If you think you can force the mime type in this package, I can open another issue for that.

Best Regards.

**Comment by frasmage** [comment]
Hi @karmendra,

Can you give me more context about what is not working regarding LocalUrlGenerator? That one does not use the `FilesystemAdapter::url()` method, it instead uses `Illuminate\Routing\UrlGenerator::asset()` to properly prepend the current scheme, host and path (I also occasionally swap out that class in the container to also append cache busting with that method). What error are you getting?

Regarding the mime type, the disk is irrelevant when determining the mime type. What mechanism are you using during upload? What are you getting vs. what are you expecting?

it is possible to override the mime with 

```php
$media->mime_type = 'image/jpeg';
$media->save();
```
