### ISSUE TITLE
Storing hash filename and original filename

### ISSUE THREAD

**Issue by munettt** [plank/laravel-mediable#63]
Hi,

thanks for the great package. I'm wondering if there is a way for me to store both the original filename and a hashed filename?

thanks

**Comment by frasmage** [comment]
Hi @munettt,

Well, you probably only want to have the file on disk once, so pick one or the other to be the actual name of the file. You can easily add additional columns to your table if you need them

```
$media = MediaUploader::fromSource(...)
    ->useFilename(...)
    ->upload();

$media->hash = md5_file($media->getAbsolutePath());
$media->save();
```

**Comment by munettt** [comment]
Thank you very much!
