### ISSUE TITLE
Syntax error or access violation: 1071 Specified key was too long; 

### ISSUE THREAD

**Issue by chandank** [plank/laravel-mediable#65]
Getting the following error at the last step of installation when doing a `php artisan migrate` using Laravel 5.4.15, MySql 5.6, PHP 7.1.2

```
[Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (SQL: alter table `media` add unique `media_disk_directory_filename_extension_unique`(`disk`, `directory`, `filename`, `extension`))

  [PDOException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
```

I already have the following set up in my AppServiceProvider.php:

```
use Illuminate\Support\Facades\Schema;

function boot()
{
    Schema::defaultStringLength(191);
}
```

**Comment by frasmage** [comment]
Hi @chandank,

This is a know limitation of the MyISAM storage engine. Your options:

- Switch to InnoDB
- Reduce the size of the disk, directory, filename, and extension columns from 255 to <200
- Drop the unique constraint altogether. Results in faster inserts, but slower selects by path.

**Comment by chandank** [comment]
@frasmage I'm already limiting it to 191 with no difference. Also tried using utf8 vs utf8mb4. Guess I'll look into using InnoDB.
