### ISSUE TITLE
On replace media action, created_at date changes

### ISSUE THREAD

**Issue by AsyncPiMaker** [plank/laravel-mediable#67]
Laravel 5.4, replace media, via config/mediable.php
'on_duplicate' => Plank\Mediable\MediaUploader::ON_DUPLICATE_REPLACE,

From controller:
$media = MediaUploader::fromSource($file)->
				toDestination('public', $path)->
				upload();

I also tried forcing replace:
$media = MediaUploader::fromSource($file)->
				toDestination('public', $path)->
				onDuplicateReplace() ->
				upload();

Either method, when file uploaded after first time, created_at value in database table media changes. Unless I am missing something, only updated_at should change?

**Comment by frasmage** [comment]
Hi @AsyncPiMaker,

The current intended behaviour is to delete the previous file and media record (clearing its attachments), then create a new one. You might notice the ID changes as well. Perhaps there might be a need for an ON_DUPLICATE_UPDATE flag to update the existing record instead, maintaining attachments.

**Comment by AsyncPiMaker** [comment]
The UPDATE option would be very helpful. Thanks for the help and great package!
