### ISSUE TITLE
Wrong media url generation.

### ISSUE THREAD

**Issue by manish-tal** [plank/laravel-mediable#68]
Library generating wrong url for media files

It should generate url as http://localhost/mediable_test/public/storage/media/95510839133c8100288fbf061548acf3.jpg but  it is generating http://localhost/mediable_test/public/storage/storage/media/95510839133c8100288fbf061548acf3.jpg.
uneccessary including two "storage" included in url.
my code is as
for adding media
```
$user = \App\User::first();
$defaultImage = new \Symfony\Component\HttpFoundation\File\File(storage_path("app/file.jpg"));
$thumbnail = \MediaUploader::fromSource($defaultImage)
            ->toDestination('public', 'media')
            ->useHashForFilename()->onDuplicateIncrement()
            ->upload();
$user->attachMedia($thumbnail, 'thumbnail');
```
and for getting url
```
$user = \App\User::first();
$thumbnail = $user->firstMedia('thumbnail');
$url = $thumbnail->getUrl();
//$url value coming as http://localhost/mediable_test/public/storage/storage/media/95510839133c8100288fbf061548acf3.jpg.
```
Using default [filesystem config](https://gist.github.com/manish-tal/7ea0f221789e124e65310fd6de0d94ec)

**Comment by manish-tal** [comment]
solved reffering to docs:
http://laravel-mediable.readthedocs.io/en/latest/configuration.html
adding "prefix" key in public storage with value "" (empty string).

 ```
'public' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
            'prefix'=>''
        ],
```

but still with laravel default config it is not working.

**Comment by manish-tal** [comment]
reopening as it is not working with default laravel config

**Comment by frasmage** [comment]
Hi @manish-tal,

Trying to figure this out, I haven't been able to exactly recreate this. Might have something to do with localhost instead of proper virtual host, but I can't think of why that should matter. Can you give me the output value of each of the following?

```php
public_path()
config('filesystems.disks.public.root')
config('filesystems.disks.public.url')
$media->directory
$media->getDiskPath()
$media->getAbsolutePath()
$media->getUrl()
```

What does your storage symlink look like?
