### ISSUE TITLE
Non-static method

### ISSUE THREAD

**Issue by borisdamevin** [plank/laravel-mediable#7]
Hi,

I call package with `use Plank\Mediable\MediaUploader;`, but I have this error `Non-static method Plank\Mediable\MediaUploader::fromSource()`.

One idea ?
Thank you.

**Comment by frasmage** [comment]
Hi Boris, the code in the documentation assumes that the MediaUploader is loaded from the service container, usually by the Facade (make sure to register it in your `config/app.php`):
```php
use MediaUploader; //use the facade, which will provide a fully loaded instance
MediaUploader::fromSource()...;
```

or 

``php
app(Plank\Mediable\MediaUploader::class)->fromSource()...;
app('mediable.uploader')->fromSource()...;
```

You can also instantiate it yourself, but that requires providing the dependencies yourself.

Hope this helps.

**Comment by RomkaLTU** [comment]
Same here. Not working on Laravel 5.5

**Comment by frasmage** [comment]
@RomkaLTU, did you try one of the solution posted above? 

The `MediaUploader` facade has the same class name as the full `Plank\Mediable\MediaUploader` class, you can't use both in the same file without aliasing one or the other.

**Comment by RomkaLTU** [comment]
Yes it works with `use MediaUploader` but thats very confusing as phpStorm reporting undefined class.

**Comment by frasmage** [comment]
That is because PhpStorm doesn't know how to read Laravel facades by default (unrelated to this package in particular). Have you tried approaches like https://github.com/barryvdh/laravel-ide-helper?

**Comment by RomkaLTU** [comment]
Yes of course it's don't know I understand that, but compared to other packages this is confusing as I can't use "auto use". And yes I'm using ide helper.
