### ISSUE TITLE
Lower case file extension - how?

### ISSUE THREAD

**Issue by kaju74** [plank/laravel-mediable#70]
I run into a duplicate entry error due of mixed file extensions (lower case vs. upper case):

If I upload an image on my iPhone, the file extension willl be ".JPG". If I upload the same image with lower case extension, the above error occurs.

Is there a way to "normalize" (i.e. lower case the extension) the filename to use?

**Comment by frasmage** [comment]
Hi @kaju74,

I'm not sure I fully understand your issue. Is the issue that you are uploading `example.jpg` and `example.JPG` and they are colliding or they are not colliding? The case sensitivity depends on your operating system and/or hard drive configuration. 

Are you getting a database error? That would mean your db collation (`*_ci` for case insensitive) is not the same as your disk. So the filename passes disk validation, but the database is not passing the unique constraint.

I can see some logic in massaging extensions into lower case, but that would not stop the same issue from occurring with a case like `Hello.jpg` and `hello.jpg`. I would not want to restrict all filenames to lowercase as uppercase characters are valid.

One approach you could take would be to change the collation of the media table to something case sensitive (e.g. `ALTER TABLE media CONVERT TO CHARACTER SET utf8 COLLATE utf8_bin;`, or `utf8_mb4` -> `utf8_mb4_bin`, `latin_1` -> `latin_1_general_cs` etc.). Note there is a side effect with `*_bin`  where `ORDER BY` will sort uppercase and lowercase versions of the same character separately (e.g. ABCabc).

Alternatively apply some logic to the filename and apply it with `MediaUploader::useFilename($name)` to make it less likely to collide.

I hope this helps

**Comment by kaju74** [comment]
Thank you for your reply, but the problem is the column "extension" in the media table. I use the funtion "MediaUploader::useFileName(...)", but if you put in the file extension, too, it won't be used for the table column...instead I'll get "myfilename.jpg" for the name and "JPG" for the extension column. 

It seems, iOS upload images with upper cased file extensions!

Is there a way to intercept the way the filename & extension names are created? For example, a callback proc or a filter function...

Best regards,
Marc

**Comment by frasmage** [comment]
What type of source are you using? `$request->file(...)`? That uses `Symfony\Component\HttpFoundation\File\UploadedFile::getClientOriginalExtension()` to retrieve the filename.

You would have two options:

- Reconstruct the `UploadedFile` object that you are passing to the uploader with lowercase information:

```php
$orig = $request->file('image');
$filename = strtolower($orig->getClientOriginalName()); //you could split just extension, but I know you are overriding the filename anyways
$source = new UploadedFile(
    $orig->getPath(), 
    $filename, 
    $orig->getMimeType(), 
    $orig->getSize(),
    $orig->getError()
);
MediaUploader::fromSource($source);
```

You could also extend the `\Plank\Mediable\SourceAdapters\UploadedFileAdapter` class, override the `extension()` method and update `config/mediable.php` to point `UploadedFile` to your new adapter.

For example:
```php
public function extension()
    {
        return strtolower($this->source->getClientOriginalExtension());
        // this should also work
        // $this->source->guessExtension()
    }
```

Hope this helps

**Comment by kaju74** [comment]
I'll try that out asap. Here's my code:

`    /**
     * Update pivot relations.
     *
     * @param \Illuminate\Http\Request $request
     */
    public function updateRelationships(Request $request)
    {
        // sync media
        if ($file = $request->file('image')) {

            $tmp = $file->getPath() . '/' . $file->getClientOriginalName();
            Image::make($file)
                ->resize(720, 480)
                ->save($tmp);

            /**
             * Upload image to default disk.
             *
             * @var Media $media
             */
            $media = MediaUploader::fromSource($tmp)
                ->useFileName($this->slug)
                ->onDuplicateReplace()
                ->toDirectory('images/pages')
                ->upload();

            // sync details with model
            $this->syncMedia($media, 'image');
        }
    }
`

So I use the name of the model's slug as the filename (so, the extension is not part of the filename)...but the column will be uppercase (if using an iPhone to upload the image). 

Marc

**Comment by frasmage** [comment]
That looks fine. You would need to edit `LocalPathAdaptor`, and not `UploadedFileAdapter`.

Since you are editing the file beforehand, option 3 would be to just save it to a different spot in tmp with a lowercase extension before handing off to the uploader.

Let me know if you need any further assistance
