### ISSUE TITLE
Call to undefined method move()

### ISSUE THREAD

**Issue by beatwiz** [plank/laravel-mediable#75]
Hello!

Sorry for disturbing you with such a trivial matter and thanks in advance for all the hardwork put into this package. Maybe I am reading the documentation sideways, but ive tried everything to no avail.

Essentially I am trying to query Media::whereBasename('abc.jpg'); and then ->move('new_directory') 

But I keep getting Call to undefined method move()

I am using:

use Plank\Mediable\Media;

What am I missing?

**Comment by frasmage** [comment]
Hi @beatwiz,

`Media::whereBasename()` is an Eloquent query scope, meaning it creates or modifies a query builder, in this case adding some `where()` conditions. It does not execute the query or fetch the Media record. As with any other query builder, you need to call `->get()` or `->first()` (as appropriate), before you can actually use any methods of the model.

In short you were calling move on the query builder, not the media model.

**Comment by beatwiz** [comment]
Hi! Thank you for your reply. I was indeed calling ->get() but running into the newbie mistake of not selecting the first value on the collection. Found that as soon as I tried ->first() :) 

*faceagainstdesk*

Thanks!
