### ISSUE TITLE
Exception Error While Importing Files 

### ISSUE THREAD

**Issue by shijupoothotta** [plank/laravel-mediable#78]
config/mediable
   ```
 'default_disk' => 'uploads',
    'allowed_disks' => [
        'uploads',
    ],
```
File system:
```
  'uploads' => [
            'driver' => 'local',
            'root' => storage_path('app/uploads'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],

```
Code to Import File
```
$disk=Storage::disk('local');
$path = 'uploads\about-img.jpg';
$media = MediaUploader::importPath($disk,$path);
dd($media->getUrl());

```
Error
![image](https://user-images.githubusercontent.com/2807290/29702023-cddcb7a8-898c-11e7-9501-f768771766d3.png)

**Comment by shijupoothotta** [comment]
Code in Import File Changed to 
```
$disk=Storage::disk('local');
$path = 'uploads\about-img.jpg';
```
```
$disk='uploads';
$path = 'about-img.jpg';
```

**Comment by shijupoothotta** [comment]
Code to attach media:
```
public function attach() {
        $disk='uploads';
        $path = 'about-img.jpg';
        $media = MediaUploader::importPath($disk,$path);
        var_dump($media);
        $post =  new Post;
        $post->first()->get();
        var_dump($post);
        $post->attachMedia($media, ['gallery', 'featured']);
    }
```
Error:
![image](https://user-images.githubusercontent.com/2807290/29706100-43c2b952-899e-11e7-8c0b-f8183749d0f0.png)

**Comment by frasmage** [comment]
Hi @shijupoothotta,

Yes, the `$disk` argument should match the key that you registered the filesystem disk under, not the driver (you could have many using the same driver).

In your attachment test, the reason for your error is that the `$post` does not exist yet in the database, so its ID is null. Whenever assigning relationships, you need to make sure that the superior record (in this case `$post`) is saved to the db before you try to attach a dependent record (`$media`) to it.

```
$media = MediaUploader::importPath($disk,$path);
$post = Post::create($attributes); // create() will actually save the model
$post->attachMedia($media, ['gallery', 'featured']);
```
