### ISSUE TITLE
How to Check Duplicate Media ?

### ISSUE THREAD

**Issue by shijupoothotta** [plank/laravel-mediable#79]
I have already uploaded files using elfinder. To link to db, I used MediaUploader::importPath. 
But, when trying to associate the same file to another model or during model update, I am getting 'Duplicate Entry Error".

Tried but not working.

`'on_duplicate' => Plank\Mediable\MediaUploader::ON_DUPLICATE_REPLACE,`
`
```
public function attachMedia($model, $filename,  $attribute) {
        $media = MediaUploader::importPath($this->disk, $filename);
        if ($model->hasMedia('featured')) {
            $model->syncMedia($media, [$attribute]);
        } else {
            $model->attachMedia($media, [$attribute]);
        }
    }
```

How can I check media existence before 
`        $media = MediaUploader::importPath($this->disk, $path);`

**Comment by frasmage** [comment]
@shijupoothotta, Could you provide the complete exception message and/or stack trace?

Based on the way your code is written, is it possible that you have multiple models to attach to the same media file? If the media has already been imported to the database and you try to import it again, importPath() will encounter an SQL error from the UNIQUE constraint on disk/path/filename/extension.

**Comment by shijupoothotta** [comment]
`$media = MediaUploader::importPath($this->disk, $path);`
Yes it is the SQL error from the UNIQUE constraint on disk/path/filename/extension.

What if I want to attach the same file to another post. I could not find a function that returns the media object for an existing file.

Instead of inserting another row if it already exists. the model ca be searched and returned.
Or another function can be defined to do the task.

**Comment by frasmage** [comment]
have you tried `Media::forPathOnDisk($disk, $path)->first()`?

**Comment by shijupoothotta** [comment]
Thanks, I was looking for that. It solved the issue.

 ```
public function attachMedia($model, $filename,  $attribute) {
        $media = Media::forPathOnDisk($this->disk, $filename)->first();
        if(!isset($media))
            $media = MediaUploader::importPath($this->disk, $filename);
        if ($model->hasMedia('featured')) {
            $model->syncMedia($media, [$attribute]);
        } else {
            $model->attachMedia($media, [$attribute]);
        }
    }
```
