### ISSUE TITLE
Original file name when saved with a hashed filename

### ISSUE THREAD

**Issue by pet1330** [plank/laravel-mediable#82]
It there an easy way get the name of the original file name (i.e. what the uploading user named the file) yet still save the file on disk with a hashed name?

**Comment by frasmage** [comment]
Hi @pet1330,

If you hash or otherwise set the destination filename, the original name is not stored anywhere by default, it would be up to you to store the data during the upload process.

```$media = $mediable->upload();
$media->original_name = $request->file('upload')->getClientOriginalName();
$media->save();
// assuming you added an "original_name" column to the media table in the database
```

**Comment by pet1330** [comment]
Yeah, that is what I am currently doing, I just wanted to check that I hadn't missed anything.

Thanks!
