### ISSUE TITLE
How to Build a Media Management Interface Like Your Admin

### ISSUE THREAD

**Issue by shinichi2510** [plank/laravel-mediable#87]
Firstly, i wanna say thank for fantastic package.

I would like to ask how i can build media management interface like in admin for plankdesign.com.

Thanks

**Comment by frasmage** [comment]
Hi @shinichi2510,

Thank you, I'm glad you are enjoying my handiwork!

There is no single right or wrong way to design a media manager interface. There are lots of options at your disposal:

- does it display files in a list or grid
- do you show all files at a time or allow directory navigation
- can files be upload by drag and drop, or just a `<input type="file">`
- can files be moved by drag and drop? How does the user navigate
- how does the user select which files to assign to a field
- etc.

Think about what the needs of your project are and what features might be useful. The flexible nature of the mediable package should make it easy to adapt to your project.

The interface naturally has two major components: the front end interface (HTML/JS) and a backend controller (PHP), with ajax communication between them. The frontend should be able query the backend for available files to display and send it uploaded/moved/deleted files.

When I built Plank's CMS a few years ago, I originally used jQuery for the frontend, though if I were to rebuild it today, I would probably use something like Vue.js or React instead. 

Best of luck!
