### ISSUE TITLE
How to replace the Media class with an own one?

### ISSUE THREAD

**Issue by kaju74** [plank/laravel-mediable#88]
Hi,

I've tryed to extend the Media class with an own one with more functionality (i.e. storing external meta data like the image auhor, ...). So I created a new class:

**class MetaMedia extends Media**

I've configured (mediable.php) it like:

**'model' => \App\MetaMedia::class**

After that, I got the following error:

**Table 'xyz.meta_media' doesn't exist**

So I've included the following line in my model:

**protected $table = 'media';**

After that, I got:

**Column not found: 1054 Unknown column 'mediables.meta_media_id' in 'field list' (SQL: select `media`.*, `mediables`.`mediable_id` as `pivot_mediable_id`, `mediables`.`meta_media_id` as `pivot_meta_media_id`, `mediables`.`tag` as `pivot_tag`, ...**

What to do now?

Regards,...

**Comment by frasmage** [comment]
Hi @kaju74,

Your steps look correct. It looks like Eloquent is inferring the foreign key itself from the class name not the table name here:

```php
public function getForeignKey()
    {
        return Str::snake(class_basename($this)).'_'.$this->primaryKey;
    }
```

You can force the foreign key by extending the `Mediable` trait and overriding its `media()` relationship.

```php
trait MetaMediable
{
    use Mediable;

    public function media()
    {
        return $this->morphToMany(config('mediable.model'), 'mediable', null, null, 'media_id')
            ->withPivot('tag', 'order')
            ->orderBy('order');
    }
}
```

Then use your trait on your models instead of the default.

**Comment by kaju74** [comment]
Thank you very much - works like a charm...
