### ISSUE TITLE
Mutator

### ISSUE THREAD

**Issue by borisdamevin** [plank/laravel-mediable#9]
Hi,

I do not put up a mutator to update the `filename` before the record in the database.

One can not use the mutators?

Thank you.

**Comment by borisdamevin** [comment]
I found my answer directly using the controller, but it forces me to create a more complex system.

Can we use the mutators to another model to override MediaUploader?

**Comment by frasmage** [comment]
Hi @borisdamevin,

I'm not sure what you mean by mutator or what you are trying to do exactly. Are you referring to `MediaUploader::setFilename()`?

**Comment by borisdamevin** [comment]
Using this : [Accessors & Mutators](https://laravel.com/docs/5.2/eloquent-mutators#accessors-and-mutators)

Yes, `MediaUploader::setFilename()` works for changing name, but not for override the text format.

**Comment by frasmage** [comment]
By text format are you referring to the `extension` or MIME type of the media? By design that is inferred automatically. The source should be 

Can you give me an example of your use case? I'm still not clear as to what you are having trouble achieving.

**Comment by borisdamevin** [comment]
Sorry for the bad explanation.

I restart, how use can use the `Plank\Mediable\Media::class` on this own MediaManager model for get and use this function and override options ?

**Comment by frasmage** [comment]
Sadly, I am still not sure what you are trying to accomplish. Your profile says you are from France, try communicating your intentions in French if that is easier for you. 

Also, you had mentioned
> I found my answer directly using the controller, but it forces me to create a more complex system.

Could you provide me with a sample of this code? It would make it easier to see what you are doing.

**Comment by borisdamevin** [comment]
Finally I found a better way with reflexion.
