### ISSUE TITLE
Ability to use MediaUploader class to replace an existing model

### ISSUE THREAD

**Issue by ryankilf** [plank/laravel-mediable#95]
I think all we'd need to do is change 

public function upload(?Media $media)

and if it's supplied, use that model instead of the result of makeModel().

Does that sound like a reasonable thing to do?

**Comment by ryankilf** [comment]
I have written the code to actually do this (i've ended up **really** needing this), but may need help creating the appropriate tests for it.

**Comment by frasmage** [comment]
#96
