### ISSUE TITLE
Using Model that extends Plank\Mediable\Media

### ISSUE THREAD

**Issue by hineios** [plank/laravel-mediable#97]
First of all, great package! Thank you.
I'll be using it in my next project but I've hit a bump and would appreciate your input/help.

I would like to use my own model `App\Media` (which extends `Plank\Mediable\Media`, of course) to store a name for the media record (for example, I also plan on adding more stuff).

Yes, I could use the existing filename field for that, but I want to use the hash of the file as the filename and also don't want to deal with renaming the file.

It seems pretty much straightforward, implement the class that extends the native `Media` class, add the name column to the DB, and start using that class.
However when I try to create a `App\Media` using the `MediaUploader::fromSource` method I get an error from the DB because there is no default method for the `name` column (and I can understand why it happens).

The thing is, do I also need to extend `MediaUploader` class to deal with this? Or can I make the `MediaUploader::fromSource` method aware of the extra parameters? I failed to find this on the docs or issues here at Github...

Thanks in advance.

**Comment by frasmage** [comment]
Hi @hineios,

Glad to hear you enjoy my package!

You can absolutely extend the `Media` class (don't forget to register your subclass in the `mediable.php` config file).

For what you are asking, your best bet might be to extend the `MediaUploader`. Note, if the bind your subclass to the Laravel service container using the `'mediable.uploader` key, the uploader Facade should continue to work.

Alternatively, you could make your database column nullable so the initial upload doesn't fail, and then fill in a value by editing the media record returned by the uploader.

I hope this helps!

**Comment by hineios** [comment]
Hey @frasmage, thanks for your reply.

I'll definitely go with extending `MediaUploader`.
I'm gonna try it up and get back to you, hopefully I'll get something that can help somebody else in the future.

**Comment by hineios** [comment]
Well, it works!
More or less.
The uploader Facade does continue to work.

However, as I have overwritten the `import()` and `upload()`, when I call some of the `private` methods of `Plank\Mediable\MediaUploader` I get an error saying that I can't call them (well, they are private, it's expected).

So, I see two options:
I'll make my fields nullable in the DB and update them after all the Mediable library work is done, as you suggested. However, I'd like to avoid this as I would be doing two queries to create one record (its not **that** problematic, but still...).

Or, if you are willing to, I'll bake a PR where those methods become `protected` instead of `private` and it should work (I've tried it locally by directly altering your files and it does work).

Well, I guess it now depends on what you want for your package 😄.
Or maybe you have a third, magic solution?

**Comment by frasmage** [comment]
Oh, right! I forgot all members are private. Yes, that probably won't change (as soon as I make things public/protected it becomes a breaking change if I want to rework any of the internals).

For the time being, the secondary query might be your best course of action.

Perhaps a feature that could added to the next major version would be to add a `beforeSave()` method that could be passed a callback that would be called somewhere in the process. Method could be passed the media record and the sourceadapter, allowing the developer to apply additional changes to the record before it is saved to the database

**Comment by hineios** [comment]
Yes, that would be very interesting indeed!

Thanks for all your help!

**Comment by frasmage** [comment]
Glad to help. I will close this and open a separate "enhancement" task for the callback method.
