### ISSUE TITLE
Add some kind of beforeSave() callback to MediaUploader

### ISSUE THREAD

**Issue by frasmage** [plank/laravel-mediable#98]
Add a mechanism to make adjustments to the `Media` record before it is saved to the database, e.g.

```php
$mediaUploader->beforeSave(function(Media $media, SourceAdapter $source) {
    $media->foo = 'bar';
});
```

**Comment by sebdesign** [comment]
I'd love to have some events before/after saving media or file system operations.

**Comment by frasmage** [comment]
@sebdesign after saving, it just returns the media record, so you probably don't need a callback to manipulate it 😉
